blog/2022-05-31-media-player-updates.md, docs/core/entity/media-player.md
Document changes in https://github.com/home-assistant/core/pull/72566 and https://github.com/home-assistant/core/pull/72406
=> Document media player changes

blog/2022-06-07-dataflow-constants-deprecation.md, docs/data_entry_flow_index.md
Add blog post for https://github.com/home-assistant/core/pull/72955
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/72955
=> Add FlowResultType enum to data entry flow

docs/core/platform/application_credentials.md
Add documentation for application credentials translations for descriptions and description placeholders.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/73014
=> Add application credentials translation documentation

docs/api/supervisor/endpoints.md
Documentation for https://github.com/home-assistant/supervisor/pull/3678
=> Add extended store addon info

docs/integration_setup_failures.md, sidebars.js
Document how to handle integration setup failures
=> Document how to handle integration setup failures

docs/integration_quality_scale_index.md
Propose an exception handling criteria for Silver integration quality where integrations should throw `HomeAssistantError` on operations like service or entity methods in general. Motivated by [discussion](https://github.com/home-assistant/core/issues/72401#issuecomment-1136776609) about `continue_on_error` from automations.
=> Propose an exception handling criteria for Silver integration quality

docs/integration_quality_scale_index.md
We now document how to handle setup failures, so lets link the integration quality page to it.
Also adds handling expired credentials to platinum quality
=> Link handling setup failures to integration quality scale and add expired credentials

docs/integration_setup_failures.md
Fix typo in integration setup failures
=> Fix typo in integration setup failures

docs/integration_quality_scale_index.md
This needed to be postfixed with .md for it to be found
by the parser
=> Fix links to integration_setup_failures

blog/2022-06-13-unsafe_reloads_during_entry_setup.md
Add blog post about unsafe config entry reloads during setup
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/73387
=> Add blog post about unsafe config entry reloads during setup

docs/core/entity/climate.md
Fix a few small issues with the climate entity documentation.
- The return type of `min_temp` and `max_temp` was incorrectly listed as `int` instead of `float`.
- The description of `HVACMode.HEAT_COOL` was describing it as a supported feature rather than as a current operating mode, which was inconsistent with the descriptions of the rest of the modes.
- Fix an instance of inconsistent capitalization of "HVAC".
=> Minor fixes to climate entity documentation

blog/2022-06-14-number_entity_refactoring.md, docs/core/entity/number.md
Document NumberEntity refactoring + add a developer blog post
=> Document NumberEntity refactoring

docs/integration_fetching_data.md
This change in documetation with work `DataUpdateCoordinator`.
Add missing import and change def params.
https://github.com/home-assistant/core/blob/0f4080bca3960ce205b5906094519cd1f3bd97bb/homeassistant/helpers/update_coordinator.py#L160
=> Fix sample update data coordinator

docs/creating_integration_manifest.md
- Move "Custom requirements during development & testing" and "Custom integration requirements" to be sub-sections of "Requirements" instead of "Loggers"
- Fix a typo under "Custom integration requirements"
=> Small fixes to creating_integration_manifest.md

docs/core/entity/number.md
=> Document RestoreNumber

docs/core/entity/weather.md
Update Weather Entity page to reflect changes to using native attributes
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/73441 https://github.com/home-assistant/frontend/pull/12947
=> Update weather of native values

blog/2022-06-27-weather_entity_refactoring.md
Add blog post about WeatherEntity refactoring
=> Add blog post about WeatherEntity refactoring

docs/core/entity/weather.md
Update text from feedback in #1376 
=> Weather - improve text

docs/auth_api.md
Fix a small typo on the Authentication API page.
=> Fix minor typo in auth_api.md

docs/core/entity/weather.md
Add more units for wind speed
https://github.com/home-assistant/core/pull/74175
https://github.com/home-assistant/frontend/pull/13028
=> Add more wind speed units

docs/development_tips.md
The example here is only major.minor it should be major.minor.patch. Home assistant requires all 3 or the custom component will not load.
Reference:
https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes/#versions
=> Fix manifest version tag example

docs/add-ons/configuration.md
The codenotary option is listed twice. I removed the option with less information value.
=> Codenotary option was listed twice

docs/config_entries_config_flow_handler.md, docs/creating_integration_manifest.md, docs/network_discovery.md
Document bluetooth discovery
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/74653
=> Document bluetooth discovery

blog/2022-07-08-generic-store.md
Add blog post for https://github.com/home-assistant/core/pull/74617
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/74617
=> Store is now a Generic class

blog/2022-07-08-config_entry_forwards.md
Fix typo in Waiting for config entry platforms
=> Fix typo in Waiting for config entry platforms

docs/development_testing.md
Some components are strict with the event loop. This PR adds instructions for devs that encounter `RuntimeError: Event loop is closed`
=> Add instructions for pytest asyncio-mode

docs/network_discovery.md
Update bluetooth for additional matchers and API calls:
- `address` matcher
- `bluetooth.async_discovered_service_info`
- `bluetooth.async_address_present`
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/74773
=> Update bluetooth for additional matchers and API calls

docs/core/entity/media-player.md
Update media player documentation
Core PR: https://github.com/home-assistant/core/pull/72593
=> Update media player documentation

docs/creating_integration_manifest.md
"It's" should be "its" in this context.
=> Small grammar fix

docs/creating_integration_manifest.md
Change manufacturer_data_first_byte to manufacturer_data_start in bluetooth docs
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/75379
=> Change manufacturer_data_first_byte to manufacturer_data_start in bluetooth docs

docs/network_discovery.md
Document `bluetooth.async_get_scanner`
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/75637
=> Document bluetooth.async_get_scanner

docs/creating_integration_manifest.md
Update bluetooth matchers to support service_data_uuid
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/75687
=> Update bluetooth matchers to support service_data_uuid

docs/network_discovery.md
=> Add Bluetooth best practices

docs/add-ons/tutorial.md
=> replace Dos with DOS

docs/network_discovery.md
Since 0.15 supports passive mode there is a new
BluetoothScanningMode argument to avoid a breaking
change in the future
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/75941
=> Document changes for bleak 0.15

docs/development_guidelines.md
Replace "Instead of order the imports manually" with "
Instead of ordering the imports manually".
The page on formatting had a spelling and/grammer error that this PR aims to fix.
=> Fix spelling/grammer error.

docusaurus.config.js
Hey, developer docs use the footer provided by docusaurus itself. It works great with wider logos like one used on official docs but not so much with square logos like the one used in these docs
https://docusaurus.io
https://developers.home-assistant.io/
A footer that is 650px high and takes more than half of my monitor looks just outrageous. This PR changes it to a much smaller size:
=> Reduce footer logo size

docs/api/supervisor/endpoints.md
- Correct the example response data.
=> Fix store addons addon api response

docs/network_discovery.md
Add mention of device re-discovery.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/76005
=> Add mention of async_rediscover_address

blog/2022-08-08-bluetooth-api-changes.md
As suggested in https://github.com/home-assistant/core/pull/76384, notify developers of upcoming changes to the `PassiveBluetoothProcessorCoordinator` API.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/76384
=> Blog on PassiveBluetoothProcessorCoordinator

docs/core/entity/sensor.md
- Add duration sensor device class.
- We seem to have missed the docs when adding it to core source.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/70543
=> Add sensor duration device class

docs/creating_integration_manifest.md
I just wanted to fix a minor miswording in the docs.
=> Update supported brands result

docs/api/supervisor/endpoints.md
Document new auto update option for https://github.com/home-assistant/supervisor/pull/3769
- Link to relevant existing code or pull request: https://github.com/home-assistant/supervisor/pull/3769
=> Document supervisor auto update option

docs/network_discovery.md
Document USB APIs
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/77006
=> Document USB APIs

blog/2022-08-24-globally_accessible_hass.md
Add blog post about core.async_get_hass()
=> Add blog post about core.async_get_hass()

blog/2022-08-25-issue_registry_moved_to_helpers.md
Add blog post moving of the issue registry to helpers
=> Add blog post moving of the issue registry to helpers

docs/creating_integration_manifest.md
Document local_name matching restrictions
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/77372
=> Document local_name matching restrictions

docs/frontend/architecture.md
=> Fix minor typo in architecture.md

docs/core/entity/media-player.md
Add list of expected states for a media player
* Should we include ON and UNKNOWN they are quite similar in meaning?
- Related to issue https://github.com/home-assistant/core/issues/77294
=> Add list of states to media player developer docs

docs/core/platform/repairs.md, docs/issue_registry_index.md, sidebars.js
=> Document the issue registry

docs/api/supervisor/endpoints.md, docs/api/supervisor/models.md
Document new Supervisor API and model changes introduced in https://github.com/home-assistant/supervisor/pull/3818
- Link to relevant existing code or pull request: https://github.com/home-assistant/supervisor/pull/3818
=> Document new suggestions for issue api

docs/bluetooth.md
Small fixes for the bluetooth docs
=> Small fixes for the bluetooth docs

docs/core/entity/sensor.md
Add the new device class `moisture` to the dev docs. 
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/77666
=> Add moisture device_class

docs/add-ons/configuration.md
Fix a typo in `docs/add-ons/configuration.md`
=> Fix typo in docs/add-ons/configuration.md

docs/issue_registry_index.md
=> Document issue registry issue persistence

docs/translations.md
Since we have moved to discussions, the old link is wrong.
=> Update link to GitHub to request a new language

blog/2022-09-06-media-player-repeat-mode-deprecation.md, docs/core/entity/media-player.md
Linked to https://github.com/home-assistant/core/pull/77872 and https://github.com/home-assistant/core/pull/77941
=> Replace constants with enums in media-player

blog/2022-09-16-bluetooth-unavailable-api-changes.md, docs/bluetooth.md
Change signature of async_track_unavailable callback to provide additional information
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/78545
=> Change signature of async_track_unavailable callback to provide additional information

docs/add-ons/presentation.md
Updating the doc to add CodeNotary.  https://github.com/home-assistant/supervisor/blob/main/supervisor/addons/utils.py#L39
- [x ] Document existing features within Home Assistant
=> Add addon signing

docs/core/entity/sensor.md
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/77951
=> Add generic distance device_class

docs/core/entity/sensor.md
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/77960
=> Add generic volume device_class

docs/core/entity/sensor.md
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/77953
=> Add generic speed device_class

docs/core/entity/sensor.md
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/78993 or https://github.com/home-assistant/core/pull/79185
=> Add generic weight device class

docs/core/entity/sensor.md
Add comment around weight device class
Linked to https://github.com/home-assistant/core/pull/79201 and https://github.com/home-assistant/developers.home-assistant/pull/1476#pullrequestreview-1123513412
=> Add comment around weight device class

blog/2022-09-28-new_sensor_device_classes.md
Add blog post about new sensor device classes
=> Add blog post about new sensor device classes

blog/2022-09-28-deprecate-conversion-utilities.md
Deprecating unit conversion utilities
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/78957
=> Deprecating unit conversion utilities

docs/creating_integration_brand.md, sidebars.js
=> Document brand files

blog/2022-09-22-statistics_refactoring.md, blog/2022-09-29-statistics_refactoring.md
Add blog post about long term statistics changes
=> Add blog post about long term statistics changes

docs/config_entries_config_flow_handler.md
Update the OAuth reauth example with simpler example, and removes a TODO.
=> Update OAuth reauth with simpler example

blog/2022-09-29-statistics_refactoring.md
Adjust blog post for statistics changes after the `state_unit_of_measurement` column was removed
=> Adjust blog post for statistics changes

docs/core/entity/sensor.md
=> Update sensor.md, to make it easier to find the section about choosing state class

docs/documenting/standards.md
=> Rewording of a sentence in standards.md

blog/2020-10-10-add-options-to-SelectEntityDescription
Linked to https://github.com/home-assistant/core/pull/78882
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/78882
=> Add blog post for SelectEntityDescription

docs/creating_integration_brand.md
The minimal example on the page "Grouping integrations by brand" has a tailing comma, while the two other examples don't. If I'm not mistaken, tailing commas are not allowed in JSON, so this MR removes it.
=> Fix tailing comma in JSON snippet on Grouping integrations page

blog/2022-10-14-deprecate-unit-system.md
=> Blog post for deprecated unit system features

docs/api/supervisor/endpoints.md
Document new option added in https://github.com/home-assistant/supervisor/pull/3814
- Link to relevant existing code or pull request: https://github.com/home-assistant/supervisor/pull/3814
=> Document new options for supervisor backups

blog/2022-10-21-code-owner-commands.md
Add blog about new code owner commands.
Marked as draft until we have an example comment by the bot.
=> add blog about code owner commands

docs/api/supervisor/endpoints.md
=> Add missing store endpoints

docs/api/supervisor/endpoints.md
Add documentation for enhanced logging endpoints.
- Link to relevant existing code or pull request: https://github.com/home-assistant/supervisor/pull/3291
=> Add documentation for enhanced logging endpoints

docs/frontend/external-authentication.md
Improve grammar to make the docs easier to read.
=> Minor grammar improvements in front end developer docs

docs/creating_integration_manifest.md
Adds documentation for integrations v2.1.
Currently in a draft state, as this is under development and discussion.
=> Integrations v2.1: Differentiating hubs, devices and services

docs/creating_integration_manifest.md
Add documentation for "Virtual integrations", that are part of Integrations v2.1
Core PR: https://github.com/home-assistant/core/pull/80613
This PR needs a dev blog as well, but I will create a separate PR for that (one dev blog for all Integrations v2.1 changes).
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/80613
=> Integrations v2.1: Virtual integrations

docs/creating_integration_manifest.md
Process review comment by @MartinHjelmare in https://github.com/home-assistant/developers.home-assistant/pull/1506#pullrequestreview-1152396992
=> Process review comments in virtual integrations

blog/2022-10-24-hubs-devices-services-virtual-integrations.md
Adds a blog post about the changes around Integration v2.1
=> Add blog post about integrations v2.1

docs/core/entity/sensor.md
Linked to https://github.com/home-assistant/core/pull/80886
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/80886
=> Add WATER sensor device class

docs/creating_integration_manifest.md
As per https://github.com/home-assistant/core/pull/80945
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/80945
=> Make iot_standards in virtual integrations a list

docs/core/entity/sensor.md
Add wind_speed sensor device class
Linked to https://github.com/home-assistant/architecture/discussions/775 and https://github.com/home-assistant/core/pull/79789
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/79789
=> Add wind_speed sensor device class

docs/device_registry_index.md
=> Use the typed dataclass DeviceInfo

docs/core/entity/sensor.md
Linked to https://github.com/home-assistant/architecture/discussions/810 and https://github.com/home-assistant/core/pull/79779
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/79779
=> Add precipitation_intensity sensor device class

docs/integration_quality_scale_index.md
The `diagnostics` platform is really helpful with debugging issues users might have and has been a valuable tool in finding the needles in those haystacks.
This PR adds the diagnostics as a requirement to the gold integration quality scale.
The reason for gold, is that gold is about generic integration quality, while platinum is more performance orientated.
After a discussing with some people, for existing integration having the gold scale, we thought to keep them at their existing scale and "grandfather" those in.
=> Add diagnostics to integration QA scale gold requirements

blog/2022-10-26-new-unit-enumerators.md
=> Introducing new unit enumerators

docs/add-ons/tutorial.md
=> Minor typo fix

src/pages/index.js
https://github.com/home-assistant/developers.home-assistant/pull/1522 changed the default TZ to UTC and added a note.
This PR changes the TZ to the one set in the browser with a fallback to UTC.
[`BrowserOnly`](https://docusaurus.io/docs/docusaurus-core/#browseronly) is what makes this posible.
Revival of #1523
=> Use TZ from browser

docs/api/supervisor/endpoints.md
Document new `/os/boards/{board}` APIs added to supervisor in https://github.com/home-assistant/supervisor/pull/3984 (and being updated in https://github.com/home-assistant/supervisor/pull/3990).
- https://github.com/home-assistant/supervisor/pull/3984
- https://github.com/home-assistant/supervisor/pull/3990
=> Document `/os/boards/{board}` endpoints

docs/data_entry_flow_index.md
Documents how integration authors can enable browser autofill in their data entry flows.  Requires merging home-assistant/core#81060.
Because it didn't really fit well into the existing doc, I took the liberty of rearranging the "Show Form" section and organizing into sub-headings.  I think it reads more clearly now.
- Link to relevant existing code or pull request: home-assistant/core#81060
=> Add Autofill to data entry flow

blog/2022-11-16-statistics_refactoring.md
Add blog post about long term statistic API changes
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/82131
=> Add blog post about long term statistic API changes

docs/config_entries_config_flow_handler.md, docs/development_testing.md
Removes documentation around using `tox`, as support for it is being removed here:
<https://github.com/home-assistant/core/pull/76582>
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/76582
=> Not to Tox

docusaurus.config.js
It seems this was included in https://github.com/home-assistant/developers.home-assistant/pull/412
=> Remove Inc

docs/add-ons/configuration.md
=> Explain the dockerfile arch handling

package.json, yarn.lock
Removes `@mdx-js/react` as a direct dependency, it's dependent on our theme (`@docusaurus/preset-classic`).
more info: <https://github.com/home-assistant/developers.home-assistant/pull/1498/files#r1031614341>
Replaces #1498
=> Remove @mdx-js/react

docs/api/supervisor/endpoints.md
The variable should be a boolean and does something different than stated in the docs.
- [ x] Spelling or grammatical corrections, or rewording for improved clarity
=> Fix wrong type and description of ingress_panel

docs/core/entity/text.md
Adds documentation for the new text entity
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/79454
=> Add `text` entity developer docs

docs/architecture_index.md
=> Minor edit for readability

blog/2022-10-28-more-unit-enumerators.md, blog/2022-11-28-more-unit-enumerators.md
=> Add more unit enumerators

docs/data_entry_flow_index.md
Document https://github.com/home-assistant/core/pull/82491
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/82491
=> Document add_suggested_values_to_schema

docs/api_lib_index.md, docs/creating_integration_manifest.md, docs/frontend/development.md
Document the proposed `--skip-pip-packages` flag. It allows Home Assistant to manage all dependencies and exclude specific ones, instead of excluding all with `--skip-pip`.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/82758
=> Document `--skip-pip-packages` for more granular package installation control

docs/internationalization/core.md
Update core translation documentation to document translations for device automations and repairs issues
=> Update core translation documentation

docs/core/entity/calendar.md
Add documentation for calendar entity create/delete including recurring events.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/79601
- From architecture discussion https://github.com/home-assistant/architecture/discussions/797
=> Add documentation for calendar entity create/delete

docs/internationalization/core.md
Document `entity` section in `strings.json`
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/82701
=> Document entity section in strings.json

docs/core/entity.md
Document entity `translation_key` property
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/82701
=> Document entity translation_key property

docs/internationalization/core.md
=> Correct entity translation example

blog/2022-12-01-entity_translations.md
=> Add blog post about new entity translations

docs/add-ons/configuration.md
=> Fix minor typo in addon developer docs

docs/add-ons/tutorial.md
=> Fix minor typo in addons tutorial

docs/core/entity/number.md, docs/core/entity/sensor.md
Linked to https://github.com/home-assistant/core/pull/83360
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/83360
=> Add cm to precipitation units

blog/2022-12-07-entity-color-changes.md
Add blog post for entity state color changes.
I didn't mention the new variables as they are not officially supported. User can see them by looking a the front end theme documentation (there is a link to `ha-styles.ts`)
=> Add blog post for entity state color changes

blog/2022-12-07-entity-color-changes.md
Add missing CSS variable for state color changes
=> Add missing CSS variable for state color changes

blog/2022-12-07-unit_system_changes.md
=> Fix broken links in latest dev "unit system" blog post

docs/core/entity/number.md, docs/core/entity/sensor.md
Linked to https://github.com/home-assistant/core/pull/83376
=> Add new data size device class

docs/core/entity/number.md, docs/core/entity/sensor.md
Linked to https://github.com/home-assistant/core/pull/83377
=> Add new data rate device class

docs/core/entity/number.md, docs/core/entity/sensor.md
Linked to https://github.com/home-assistant/core/pull/83452
=> Add new irradiance device class

docs/core/entity/number.md, docs/core/entity/sensor.md
Linked to https://github.com/home-assistant/core/pull/83453
=> Add new sound pressure device class

blog/2022-12-08-multi-pan-rollback.md
add post about disabling multi-pan.
=> Add multi-pan post

blog/2022-12-01-entity_translations.md
=> Points to correct /docs URL

docs/add-ons/configuration.md
Add `matter` and `otbr` to the list of possible discovery services.
- Link to relevant existing code or pull request: https://github.com/home-assistant/supervisor/pull/4040, https://github.com/home-assistant/supervisor/pull/4002
=> Add Matter and OTBR to possible service discovery

docs/config_entries_config_flow_handler.md
in *Unique IDs* section, the `strings.json` example require one more closing curly brace to be valid json
=> Add a mising closing curly brace

docs/core/entity/number.md, docs/core/entity/sensor.md
Linked to https://github.com/home-assistant/core/pull/84029
=> Add CCF to volume units

docs/core/entity/number.md, docs/core/entity/sensor.md
Linked to https://github.com/home-assistant/architecture/discussions/843
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/84386
=> Remove lumen from Illuminance units

docs/internationalization/core.md
Document entity attribute translations
- https://github.com/home-assistant/core/pull/77028
- https://github.com/home-assistant/core/pull/83386
=> Document entity attribute translations

docs/core/entity/calendar.md
Add documentation for update APIs for calendar entities
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/84141
=> Add update APIs for Calendar Entities

blog/2022-12-05-more-unit-enumerators.md
Add more units deprecation to blog post:
=> Add more units deprecation to blog post

docs/api/rest.md
API CURL MQTT authentication example fix.
Current example is misleading/wrong for the authentication part of the API, introduced the `Authorization: Bearer XxxXXxx` as elsewhere.
=> Update rest.md, fix inconsistent example for API CURL

docs/core/entity/calendar.md
Fix copy/paste mistakes in calendar update docs from PR #1590
=> Fix copy/paste mistakes in calendar update docs

docs/internationalization/custom_integration.md
fixes an outdated Link to the ‘translations’ folder in the front end repository. 
=> fix: correct outdated link

docs/core/entity/number.md, docs/core/entity/sensor.md
Add mA to SensorDeviceClass.CURRENT
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/84492
=> Add mA to SensorDeviceClass.CURRENT

docs/development_testing.md
=> Fix typo in the development testing

docs/core/entity/calendar.md
Reverts home-assistant/developers.home-assistant#1601 there are a few things conflated in here that I want to separate.
=> Revert "Update timezone requirements for calendar events"

blog/2023-01-02-db-schema-v32.md
Add blog post about db schema v32
=> Add blog post about db schema v32

docs/core/entity/sensor.md
Update SensorDeviceClass.PRECIPITATION documentation
=> Update SensorDeviceClass.PRECIPITATION documentation

docs/creating_integration_manifest.md
fixed missing comma in manifest json
fixed missing comma in json code
- Link to relevant existing code or pull request: https://github.com/home-assistant/developers.home-assistant/commit/59df487ca1beaa5e4979b028aababb94cd4473e9
=> fixed json in creating_integration_manifest.md

blog/2022-06-02-update_coordinator-context.md, docs/integration_fetching_data.md
Adjust documentation to show use of data update coordinator context to limit the data an update coordinator grabs from the API.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/72702
=> Adjust development documentation with context

docs/development_environment.mdx
Since some people (like me and others) experience issues with the default Dev Container debugging, which doesn't work out-of-the box - new developers may think that debugging is not supported by the dev container out-of-the-box. This description is to indicate that normally debugging doesn't need any additional actions to be taken to enable it. 
I also mentioned the way to debug remote instances, which may be very helpful for the developers, also in case of issues with the default debugging without enabling `debugpy`. 
If I had such description I wouldn't loose almost 2 hours of googling trying to find out what is supported and what are the options, so I hope thanks to this people will avoid this.
As above. This is not covered by the docs, and people may think debugging in devcontainer is …
=> Add notes about debugging HA in Dev Container

docs/core/entity.md, docs/core/entity/binary-sensor.md, docs/core/entity/button.md, docs/core/entity/camera.md, docs/core/entity/cover.md, docs/core/entity/humidifier.md, docs/core/entity/number.md, docs/core/entity/sensor.md, docs/core/entity/switch.md, docs/core/entity/update.md
As pointed out here in this external issue:
https://github.com/rrooggiieerr/homeassistant-xyscreens/issues/1#issuecomment-1370192100
We don't reflect the use of out device class enums properly in our dev docs.
This PR adjusts it in a similar fashion as we did with entity features.
=> Replace device class strings with enums in dev docs

docs/core/entity/number.md, docs/core/entity/sensor.md
Update allowed units for power factor sensor device class to allow `None`. Also add `None` to the air quality index sensor device class.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/85181
=> Update allowed units for power factor sensor device class

docs/voice/intent-recognition/supported-languages.md, docs/voice/overview.md
- Capitalize Conversation integration
- Clarify on voice overview which part does not work yet
- Link to intent progress report
=> Tweak voice stuff

docs/config_entries_config_flow_handler.md, docs/network_discovery.md
Updates the oauth2 URL in the integration config flow page
=> Update two URLs to avoid redirect

docs/config_entries_config_flow_handler.md
This addition makes it more clear that the config entry migration is triggered by a change of the schema version and how to define this schema version
=> Add schema version to example config flow

blog/2023-01-12-bluetooth-adapters.md, docs/bluetooth.md
Update instructions for integrations that use bluetooth adapters
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/85723
=> Update instructions for integrations that use bluetooth adapters

docs/core/conversation/custom_agent.md, docs/voice/overview.md, sidebars.js
Document the custom conversation agent feature.
=> Document custom conversation agent

docs/voice/intent-recognition/contributing.md, docs/voice/intent-recognition/template-sentence-syntax.md, docs/voice/intent-recognition/test-syntax.md
Update contributing docs to make it easier to understand.
=> Update voice contribuiton docs

docs/internationalization/core.md
Add selectors select for backend backend localization
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/85531 https://github.com/home-assistant/frontend/pull/15064
=> Add selectors select for backend backend localization

docs/internationalization/core.md
=> Address late review of selectors translation

docs/voice/intent-recognition/template-sentence-syntax.md
Adds documentation on how to use a list to get specific numbers for an intent, like 100 % from the word maximum and how this can be used to set brightness of a light.
- [ x] Document existing features within Home Assistant
=> Added example of list in sentence syntax

docs/core/entity.md
Add a missing `/`  at the beginning of a doc link
=> Fix internationalization link in entity.md

docs/api/native-app-integration/sending-data.md
Docs for https://github.com/home-assistant/core/pull/86239
=> Document the mobile app webhook for conversation

docs/core/bluetooth/bluetooth_fetching_data.md
Rephrase ActiveBluetoothCoordinator docs
https://github.com/home-assistant/developers.home-assistant/pull/1635/files#r1082275329
=> Rephrase ActiveBluetoothCoordinator docs

docs/voice/contributing-your-voice.md, sidebars.js
Add a page about how to contribute your voice.
=> Add "contributing your voice" page

blog/2023-01-20-cover-intent-deprecated.md, docs/intent_builtin.md
Cover is now a deprecated intent. Previously it was rendered based on the intents repo. It has been removed there and now hardcoded while it's deprecated.
=> Add cover to deprecated intents

docs/development_environment.mdx
Python 3.9 support has been dropped. Python 3.11 is not supported yet, so only 3.10 is possible at the moment. 
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/85456
=> Update python version in development docs

blog/2023-01-24-conversation-updates.md, docs/core/conversation/custom_agent.md
Add blog post for https://github.com/home-assistant/core/pull/86484 and https://github.com/home-assistant/core/pull/86592
=> Add blog post about breaking changes to conversation integration

blog/2023-01-25-sensor_rounding.md
Add blog post about sensor rounding
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/86074
=> Add blog post about sensor rounding

docs/core/entity/number.md, docs/core/entity/sensor.md
Document K as a valid unit for temperature sensor and number
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/86073
=> Document K as a valid unit for temperature sensor and number

docs/core/entity/number.md, docs/core/entity/sensor.md
Add MJ and GJ energy types
GJ is already in core but missing from the docs, adding MJ.
- Link to relevant existing code or pull request: https://github.com/home-assistant/home-assistant.io/pull/25862
https://github.com/home-assistant/core/pull/86055
=> Add MJ and GJ energy types

blog/2022-12-08-multi-pan-rollback.md
add a note for people reading the multi-pan blog linked from HA 
=> Add note to multi-pan blog

docs/core/entity/sensor.md
=> Fix typo in sensor documentation

blog/2023-02-06-translations-files-removed-from-core.md
Blog to go with change: https://github.com/home-assistant/core/pull/87543
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/87543
=> Blog: Translation files removed from Core repository

blog/2023-01-25-sensor_rounding.md, blog/2023-02-08-sensor_presentation_rounding.md
=> Fix a couple of broken links

docs/creating_integration_manifest.md
manifest now have to be ordered to pass CI test. So I have reorganized the ones here so that if someone uses them for development, they will be correct.
=> Update Manifest order

docs/integration_fetching_data.md
This clarifies the update interval documentation by adding an explicit statement about the minimum allowed update interval to avoid guesswork.
See https://github.com/home-assistant/core/pull/87399#issuecomment-1430006236
=> Add note about minimum allowed update interval

docs/config_entries_config_flow_handler.md
This clarifies the connection between the `step_id` and its callback to make it easier to understand the "magic" happening behind the scenes.
=> Clarify config flow step definitions

docs/frontend/custom-ui/custom-card.md
The link to boilerplate is outdated. The HACS link just links to the same boilerplate. Both can be removed.
Fixes #1627
=> Remove advanced card resources as they are outdated

blog/2023-02-20-snapshot-testing.md, docs/development_testing.md
Add basic docs/blog/reference for snapshot testing in our Core Python codebase.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/88323
=> Add snapshot testing

blog/2023-02-21-deprecated-callback-removed.md
It will avoid confusion for readers
=> Correct typo in code example

blog/2023-02-07-introducing-PR-drafting-in-reviews.md, docs/review-process.md, sidebars.js
This PR adds a page to developer documentation concerning the general review process with Home Assistant repositories.
It is based on the new PR drafting methods and general Q&A around our pull requests & reviews.
=> Add generic page on the PR review process

docs/core/entity/sensor.md
=> Remove outdated comments about statistics

docs/creating_platform_code_review.md, docs/integration_fetching_data.md
This just names the second parameter to `add_entities` for easier discoverability.
=> Use named kwarg for add_entities' update_before_add parameter

docs/documenting/standards.md
Process review feedback provided in https://github.com/home-assistant/developers.home-assistant/pull/1710
=> Process Terminology Tooltips feedback

docs/internationalization/core.md
Correct JSON terminology in core translations docs
=> Correct JSON terminology in core translations docs

docs/internationalization/core.md
Document translation of entity names
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/88242
=> Document translation of entity names

docs/config_entries_config_flow_handler.md
Fix Markdown link
Documentation typo fix
- n/a
=> Fix Markdown link (config_entries_config_flow_handler.md)

docs/core/entity/calendar.md
Update CalendarEvent timezone requirements to specify that they must have a timezone, but it does not have to be UTC.
Related discussion: https://github.com/home-assistant/architecture/discussions/853
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/89533
=> Update CalendarEvent timezone requirements

docs/frontend/custom-ui/custom-card.md
Added a link to the docs for the hass object in the API section of the document.
I propose adding a hyperlink to the documentation for the hass object in the custom card documentation.
When I was developing my own custom card I did not find that doc until after it would have been useful, by putting a hyperlink there it makes it easier to find the information one will need when developing a custom card.
=> added link to the docs of the hass object in custom-card.md

docs/voice/pipelines/index.md, sidebars.js
Document WebSocket API for running pipelines.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/90004
=> Add documentation for pipeline WebSocket API

docs/review-process.md
=> Fix typo in review process

blog/2022-03-23-entity_name_translations.md, docs/core/entity.md, docs/internationalization/core.md
Add blog post about translatable entity names + improve docs
=> Add blog post about translatable entity names + improve docs

docs/api/supervisor/endpoints.md, docs/api/supervisor/models.md
Document API changes made in https://github.com/home-assistant/supervisor/pull/4202
- Link to relevant existing code or pull request: https://github.com/home-assistant/supervisor/pull/4202
=> Data disk APIs use UDisks2 info

docs/config_entries_config_flow_handler.md
Clarify documentation of `async_migrate_entry`
=> Clarify documentation of async_migrate_entry

docs/config_entries_index.md
Add link to config entry migration
=> Add link to config entry migration

docs/dev_101_services.md
Add line breaks to services.yaml example; without this a horizontal scroll bar is added
=> Add line breaks to services.yaml example

docs/dev_101_services.md
=> Document service filters

docs/dev_101_services.md
=> Clarify service field filter

docs/dev_101_services.md
Modify service field filter documentation
Core PR: https://github.com/home-assistant/core/pull/90728
=> Modify service field filter documentation

docs/core/entity/sensor.md
See https://github.com/home-assistant/core/pull/90018
=> Add ms as valid duration sensor unit type

blog/2023-04-13-new_limits_for_add_ons.md
Add blog post about OS 10 and new add-on limits (number of file descriptors).
=> Add blog post about OS 10 and new add-on limits

docs/core/entity/light.md
The light entities brightness should be in range 1..255.
=> Light entity brightness to be in range 1..255

docs/core/entity/stt.md
We're adding an stt entity in the next release which will replace the legacy stt provider interface.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/91230
=> Add speech to text entity

docs/voice/overview.md
Voice Assistant integration has been renamed.
=> Rename Voice Assistant to Assist Pipeline

docs/add-ons/configuration.md
Documents the ability for setting `NET_RAW`
- Link to relevant existing code or pull request: https://github.com/home-assistant/supervisor/pull/4242
=> Add-on support for NET_RAW privileges

docs/core/entity/tts.md
We're adding a tts entity in the next release. The existing tts provider interface is considered legacy.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/91692
=> Add text to speech entity

docs/voice/pipelines/index.md
=> Update pipeline docs

docs/voice/pipelines/index.md
Docs for https://github.com/home-assistant/core/pull/92100
=> correct pipeline event data for run-start

docs/voice/pipelines/index.md
Small fixes for Assist pipeline websocket API docs
=> Clean up and small fixes for assist pipeline docs

README.md
Updates the URLs in the readme file.
=> Update URLs in readme

blog/2023-04-30-statistics_impossible_values.md
Add a blog post for Statistics WebSocket API changes
related core PR https://github.com/home-assistant/core/pull/92095
=> Add a blog post for Statistics WebSocket API changes

docs/core/entity/time.md
Adds documentation for the new time entity
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/81949
=> Add `time` entity developer docs

docs/creating_integration_manifest.md
I get an error if I copy and paste this example directly to a file.
=> Minor edit - remove 'comma'

docs/api/supervisor/endpoints.md, docs/api/supervisor/models.md
Document new APIs added in https://github.com/home-assistant/supervisor/pull/4269
- Link to relevant existing code or pull request: https://github.com/home-assistant/supervisor/pull/4269
=> Document new APIs around network mounts

docs/voice/language-leaders.md
Mention that quality is also important for language leaders.
=> Update language leader to include quality

docs/intent_builtin.md
- List supported and deprecated intents in introduction
- in case people do not scroll and don't realize there are deprecated intents there.
- It should also make it more obvious that currently only 4 intents are used.
- Add information that slots are optional
- List possible slot combinations
- information based on intent documentation on github: https://github.com/home-assistant/intents/blob/main/intents.yaml
- [] Document existing features within Home Assistant
=> List supported and deprecated intents in introduction

docs/device_automation_trigger.md
Fix some example code errors in device_automation_trigger.md
=> Fix some example code in device_automation_trigger.md

docs/api/rest.md
`filter_entity_id` changed to be required since we removed support for doing an unbound select.
related change https://github.com/home-assistant/core/pull/90992
potential solution for anyone who still needs to do this https://github.com/home-assistant/core/pull/92640
=> Update rest documentation for filter_entity_id as its required

blog/2023-05-07-job-home-assistant-core.md
Add a post to promote the job opening for HA core developer.
=> Add job blog

docs/development_environment.mdx
=> add info on how to open command palette

docs/core/entity/sensor.md
Adds documentation for https://github.com/home-assistant/core/pull/92973
Parent PR has been merged already.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/92973
=> Add sensor device class volatile_organic_compounds_parts

docs/api/supervisor/endpoints.md
Document new options added in https://github.com/home-assistant/supervisor/pull/4289
- Link to relevant existing code or pull request: https://github.com/home-assistant/supervisor/pull/4289
=> Document new backup location options

docs/add-ons/configuration.md
- Link to relevant existing code or pull request: https://github.com/home-assistant/supervisor/pull/4259
=> Add support for CAP_BPF and CAP_PERFMON privileges on addons

docs/voice/pipelines/index.md
The Assist pipeline docs document event types for completed steps ending with `-finish`, but [it should be `-end`](https://github.com/home-assistant/core/blob/051d631504c739b8b40fe91907865e12b8d355dd/homeassistant/components/assist_pipeline/pipeline.py#L232-L243).
Also fixes a line break in the same table.
=> Fix Assist pipeline event types

docs/core/entity/tts.md
Update tts entity documentation
core PR: https://github.com/home-assistant/core/pull/93450
=> Update tts entity documentation

docs/network_discovery.md
=> Fix typo in network discovery example

docs/api/supervisor/models.md
Include share as mount usage option as per https://github.com/home-assistant/supervisor/pull/4318
- Link to relevant existing code or pull request: https://github.com/home-assistant/supervisor/pull/4318
=> Include share as mount usage option

docs/core/entity/datetime.md
Adds documentation for the new datetime entity
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/81943
=> Add `datetime` entity developer docs

docs/internationalization/core.md
Updates the structure to reflect the change made in:
- https://github.com/home-assistant/core/pull/89702
- https://github.com/home-assistant/frontend/pull/15820
=> Update entity component state (attributes) translations structure

docs/frontend/development.md
Updates the URLs in the frontend development page.
=> Update URLs in frontend development page

docs/core/bluetooth/bluetooth_fetching_data.md
Fix DataUpdateCoordinator link in bluetooth docs
=> Fix DataUpdateCoordinator link in bluetooth docs

docs/core/entity/light.md
Update light documentation with color_temp in K
This updates documentation according to https://github.com/home-assistant/core/pull/79591
=> Update light documentation with color_temp in K

docs/core/entity.md
Very minor typo fix in example code. The property `_attr_device_class` was missing an `s` at the end.
=> Fix minor typo in example code

docs/core/entity/image.md
Document image entity
Core PR: https://github.com/home-assistant/core/pull/90564
=> Document image entity

docs/core/entity/climate.md
Documents the new preheating HVAC action.
Backend PR: https://github.com/home-assistant/core/pull/94677
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/94677
=> Add preheating HVAC action to climate

docs/core/entity/sensor.md
The enum in the code has CO2 and CO instead of CARBON_DIOXIDE and CARBON_MONIXIDE.
My preferred way would actually be to change the code to have fully written names, since OZONE, NITROUS_OXIDE and another one are also fully written.
=> Align SensorDeviceClass page with code

docs/core/entity/weather.md
Adds Dewpoint to Weather entity component
As per decision in https://github.com/home-assistant/architecture/discussions/787
Core PR: https://github.com/home-assistant/core/pull/95072
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/95072
=> Add dew point to Weather entity component

docs/core/entity/weather.md
Add Cloud coverage in Weather
From decision in https://github.com/home-assistant/architecture/discussions/905
Core PR: https://github.com/home-assistant/core/pull/95068
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/95068
=> Add Cloud coverage in Weather

docs/core/entity/weather.md
As per decision in https://github.com/home-assistant/architecture/discussions/779
Core PR: https://github.com/home-assistant/core/pull/95064
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/95064
=> Add humidity in Weather forecast

docs/core/entity/button.md
Add documentation for the new `identify` button device class.
Architectural proposal/approval: https://github.com/home-assistant/architecture/discussions/934
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/95244
=> Add identify device class to button

docs/core/entity.md
Clarify translated entity names are preferred
=> Clarify translated entity names are preferred

docs/frontend/development.md
Followup to https://github.com/home-assistant/frontend/pull/17040
- Link to relevant existing code or pull request: https://github.com/home-assistant/frontend/pull/17040
=> Update frontend editable install command

docs/core/entity/image.md
Add fetch from image url option to image entity.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/95301
=> Add fetch from image url option to image entity

docs/dev_101_services.md
Add documentation for services supporting response data.
Future documentation will be required when `services.yaml` is extended with ability to describe return values.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/94401
- Architecture discussion: https://github.com/home-assistant/architecture/discussions/777#discussioncomment-6127898
=> Add documentation for services with response data

docs/development_testing.md
Removes example code on the dev testing page because both flake8 and isort were replaced by ruff in core. See https://github.com/home-assistant/core/pull/89863 and https://github.com/home-assistant/core/pull/94302.
Perhaps we should also add an example for `ruff` and other linter commands that are also run during `pre-commit`?
=> Remove example commands for flake8 and isort

docs/data_entry_flow_index.md
Currently, the `async_remove` callback method is not documented, but it plays a vital role when working with long-lived tasks in conjunction with the progress system in the Config Flow.
The `async_remove` method provides a way to handle the removal of the flow and is particularly useful when dealing with tasks that take a significant amount of time to complete. By implementing this method in the FlowHandler class, we can ensure proper cleanup of any resources or tasks associated with the flow when the user closes the flow or when the flow is canceled by the user. But doing so we need to explain to the developer that it is possible.
Link to documentation: https://developers.home-assistant.io/docs/data_entry_flow_index/#show-progress--show-progress-done
=> Explain `async_remove` in the Config Flow

docs/core/platform/repairs.md
Minor; `IssueSeverity` enum value isn't referenced from a correct import.
=> Fix incorrect reference to IssueSeverity

docs/core/entity/image.md
=> Update image entity documentation

docs/core/entity/image.md
=> Improve image entity documentation

docs/core/entity/humidifier.md
Add `action` attribute to Humidifier
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/95131
=> Add `action` attribute to Humidifier

docs/core/entity.md
=> Document that some entities are named by their device class

blog/2023-06-28-entity-name-changes.md
Add blog post about entity name changes
=> Add blog post about entity name changes

blog/2023-06-28-service-description-filters.md
Add blog post about service description filters
=> Add blog post about service description filters

docs/creating_component_index.md
Without a file `manifest.json` and some keys the integration can't be found.
Add `manifest.json`.
=> Make minimal integration working again

docs/core/entity/vacuum.md
Alphabetize vacuum documentation
=> Alphabetize vacuum documentation

docs/core/entity/vacuum.md
Update vacuum dev docs:
- Remove documentation of deprecated flags and services for the `VacuumEntity` base class
- Add missing documentation of services for the `StateVacuumEntity` base class
=> Update vacuum dev docs

blog/2023-06-28-service-description-filters.md
=> Tweak service filter blog post

docs/development_testing.md
=> Fix word duplication in testing instructions

blog/2023-07-07-action-event-custom-cards.md
Add blog post for action event for custom cards
=> Add blog post for action event for custom cards

docs/core/entity/media-player.md
Document the MEDIA_ENQUEUE media_player feature flag
Core PR: https://github.com/home-assistant/core/pull/95905
=> Document MEDIA_ENQUEUE media_player feature flag

docs/core/entity/media-player.md
Document the MEDIA_ANNOUNCE media_player feature flag
Core PR: https://github.com/home-assistant/core/pull/95906
=> Document MEDIA_ANNOUNCE media_player feature flag

docs/dev_101_services.md
Update documentation for filtering services by supported features with the additional syntax introduced by https://github.com/home-assistant/core/pull/95854
=> Update documentation for filtering services by supported features

blog/2023-07-10-vacuum-updates.md
Add blog post about recent vacuum changes
=> Add blog post about recent vacuum changes

docs/add-ons/testing.md
Correct port in the documentation
=> Wrong port in the docs

blog/2023-07-10-vacuum-updates.md
Fix bracket mix up. Now the link should be working
=> Fix bracket mix up

docs/voice/pipelines/index.md
While working on native Assist for the Android app, the documentation didn't explain how to send the speech data. As this is currently the only use of binary WebSocket messages in Home Assistant's WebSocket API and you can't just start sending data and expect it to be processed, I figured it was worth documenting.
- WS binary handling (handler ID): https://github.com/home-assistant/core/blob/d7755a92c31dd3efb28119fd5f65bc1dd0cb0d6f/homeassistant/components/websocket_api/connection.py#L123-L140
- Binary data coming in to Assist pipelines: https://github.com/home-assistant/core/blob/d7755a92c31dd3efb28119fd5f65bc1dd0cb0d6f/homeassistant/components/assist_pipeline/websocket_api.py#L130-L140
=> Document sending Assist pipeline speech data

docs/device_automation_index.md
Document `secondary` flag for device automations
Core PR: https://github.com/home-assistant/core/pull/70278
Frontend PR: https://github.com/home-assistant/frontend/pull/12496
=> Document secondary flag for device automations

docs/creating_integration_manifest.md
=> Fixed typos in creating_integration_manifest.md

docs/core/entity/event.md
Add developer documentation for the event entity
- Link to architectural proposal: https://github.com/home-assistant/architecture/discussions/929
- Link to code base pull request: https://github.com/home-assistant/core/pull/96797
- Link to frontend pull request: https://github.com/home-assistant/frontend/pull/17332
- Link to brands pull request: https://github.com/home-assistant/brands/pull/4555
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/28263
- Link to developer documentation pull request: https://github.com/home-assistant/developers.home-assistant/pull/1849
=> Add event entity

blog/2023-057-21-change-naming-mqtt-entities.md
Explain the changes in MQTT entity naming.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/95159
=> Blog post on MQTT entity naming changes

docs/dev_101_services.md
Fix Supporting Response Data example to resolve syntax error.
https://github.com/home-assistant/core/blob/2023.7.3/homeassistant/core.py#L1802
https://community.home-assistant.io/t/zha-toolkit-a-big-set-of-zigbee-commands-on-top-of-zha-zigpy/373346/149?u=pdecat
=> docs: fix Supporting Response Data example

docs/frontend/custom-ui/custom-view.md
To add cards, the event is `ll-create-card` but the docs says `ll-add-card`.
=> Update custom-view.md to correct event for adding cards

docs/core/entity/weather.md
SSIA
Core PR: https://github.com/home-assistant/core/pull/96951
Decision: https://github.com/home-assistant/architecture/discussions/924
=> Add uv_index to weather entity component

docs/core/entity/scene.md
The documentation for the `scene` entity is missing in the developer documentation.
Links to https://github.com/home-assistant/home-assistant.io/pull/28262
=> Add scene entity developer documentation

docs/core/entity/number.md, docs/core/entity/sensor.md
Document the new _pH_ device class for sensor and number entities.
- This PR fixes or closes issue: _None_
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/95928
=> Document new pH device class for sensor and number

docs/frontend/design.md, sidebars.js
Add the design portal so it can easily be found by new frontend developers.
=> Add info about design portal to frontend dev docs

docs/frontend/extending/adding-more-info-dialogs.md
Corrects information.
The code structure must have been changed since this was written.
=> Correct instructions to add more-info-content

docs/core/entity/water-heater.md
Add turn on/off service for the `water_heater` entity
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/94817
=> Add turn on/off service for water_heater entity

docs/device_registry_index.md
Add documentation for the device info categorization that was implemented in https://github.com/home-assistant/core/pull/95641.
- Link to relevant existing code or pull request: https://github.com/home-assistant/architecture/discussions/936 https://github.com/home-assistant/core/pull/95641
=> Add documentation for device info categorization

docs/voice/intent-recognition/template-sentence-syntax.md
Documents new sentence template syntax that was added to hassil 1.2 (already merged in HA). This includes wildcards and local expansion rules.
=> Update template syntax for hassil 1.2

docs/development_environment.mdx
=> Update python version to 3.11

docs/core/entity/weather.md
Extends the developer page for weather to adapt forecast to the three new buckets `forecast_daily`, `forecast_hourly` and `forecast_twice_daily`
Architecture decision: https://github.com/home-assistant/architecture/discussions/781
Core PR: https://github.com/home-assistant/core/pull/75219
Frontend PR: https://github.com/home-assistant/frontend/pull/15028
Blog PR: #1809
=> Three modes for weather

docs/core/entity/weather.md
=> Sort weather documentation

docs/integration_quality_scale_index.md
Add docs link to parallel_updates requirement
=> Add docs link to parallel_updates requirement

docs/core/entity/water-heater.md
Correct water_heater turn off methods. Late review on #1852
=> Correct water_heater turn off methods

docs/development_environment.mdx
- This PR fixes or closes issue: fixes #1878
=> Fix dev environment URL

docs/review-process.md
Not sure about the language but I think it would be good to point out the ADR's and that their PR's need to comply with those.
=> Add ADR to the PR review process

docs/development_testing.md
Correct instructions for invoking pip:
- We no longer use the legacy resolver
- There's no need to specify the constraints fil on the command line, it's included by requirements_all.txt
=> Correct instructions for invoking pip

blog/2023-08-23-sensor-updates.md
Add blog post about numerical sensors can't be NaN or inf
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/98110
=> Add blog post about numerical sensors can't be NaN or inf

docs/core/platform/repairs.md
This PR adds a overview of the different issue severity levels and provides a short description when to use.
=> Add description of issue severities

docs/add-ons/configuration.md, docs/add-ons/security.md, docs/api/supervisor/endpoints.md
https://github.com/home-assistant/supervisor/pull/4152
https://github.com/home-assistant/frontend/pull/15505
https://github.com/home-assistant/core/pull/88472
=> Updates docs for remote-user

docs/core/entity/stt.md, docs/core/entity/wake_word.md
Documents the `WakeWordDetectionEntity`
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/blob/dev/homeassistant/components/wake_word/__init__.py
=> Document wake word detection entity

docs/config_entries_index.md
I found it difficult to find the documentation related to handling setup failures because it wasn't references in the Config Entry section. After asking in Discord and getting a link to it, I thought it was useful to connect the two pages.
=> Reference the setup failures documentation as part of the config entry lifecycle documentation

docs/core/entity/camera.md
https://github.com/home-assistant/core/pull/96991/ refactors the `Camera` entity so that `Stream` images are grabbed directly by `Camera` instead of by the camera integrations that use this feature. In order for `Camera` to know whether or not to use this behavior, the new `Camera` attribute `use_stream_for_stills` was added. Integrations that wish to use `Stream` to generate stills can set this attribute and it will be checked at runtime when an image is requested.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/96991/
=> Update camera stream documentation

docs/core/entity/air-quality.md
Align documented `air_quality` attributes with implementation
=> Align documented air_quality attributes with implementation

blog/2023-08-29-homeassistant-changed-signature.md
=> Add blog post about new signature of HomeAssistant

docs/core/entity/sensor.md
Sensor entity: atmospheric pressure: add mmHg to units
- related change in user documentation: https://github.com/home-assistant/home-assistant.io/pull/28781
- 
- Link to relevant existing code or pull request: https://github.com/home-assistant/home-assistant.io/pull/28781
=> Sensor entity: atmospheric pressure: add mmHg to units

docs/config_entries_config_flow_handler.md
SSIA as mentioned in https://github.com/home-assistant/core/pull/97837
=> Change logger to debug for config entry migration

docs/api/supervisor/endpoints.md
Document new freeze and thaw APIs created for external backups/snapshots in https://github.com/home-assistant/supervisor/pull/4538
- Link to relevant existing code or pull request: https://github.com/home-assistant/supervisor/pull/4538
=> Document new freeze and thaw APIs in supervisor

blog/2023-09-12-ws-entity-source-simplified.md
Add blog post about changes in WS command entity/source
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/99439
=> Add blog post about changes in WS command entity/source

docs/creating_integration_file_structure.md
Add a explanation about the `coordinator.py` to the integration file structure section.
=> Add coordinator.py to file structure explanation

docs/core/entity/lawn-mower.md
Align documented lawn_mower attributes with implementation and improve formatting
=> Align documented lawn_mower attributes with implementation

docs/core/entity/alarm-control-panel.md
Align documented alarm_control_panel attributes with implementation and improve formatting
=> Align documented alarm_control_panel attributes with implementation

docs/core/entity/calendar.md
Align documented calendar attributes with implementation and improve formatting
=> Align documented calendar attributes with implementation

docs/core/entity/camera.md
Align documented camera attributes with implementation and improve formatting
=> Align documented camera attributes with implementation

docs/core/entity/event.md
Align documented event attributes with implementation and improve formatting
=> Align documented event attributes with implementation

docs/core/entity/climate.md
Align documented climate attributes with implementation and improve formatting
=> Align documented climate attributes with implementation

docs/core/entity/cover.md
Align documented cover attributes with implementation and improve formatting
=> Align documented cover attributes with implementation

docs/core/entity/device-tracker.md
Align documented device_tracker attributes with implementation and improve formatting
=> Align documented device_tracker attributes with implementation

docs/core/entity/humidifier.md
Align documented humidifier attributes with implementation and improve formatting
=> Align documented humidifier attributes with implementation

docs/core/bluetooth/api.md
Just noticed a missing `,` in the example code.
=> Fix typo in Bluetooth code example

docs/core/entity/light.md
Align documented light attributes with implementation and improve formatting
=> Align documented light attributes with implementation

docs/core/entity/image.md
Align documented image attributes with implementation and improve formatting
=> Align documented image attributes with implementation

docs/core/entity/fan.md
Align documented fan attributes with implementation and improve formatting
=> Align documented fan attributes with implementation

docs/core/entity/binary-sensor.md
Align documented binary_sensor attributes with implementation and improve formatting
=> Align documented binary_sensor attributes with implementation

docs/core/entity.md
Document how to exclude state attributes from recording
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/100239
=> Document how to exclude state attributes from recording

blog/2023-09-15-excluding-state-attributes-from-recording.md, blog/2023-09-20-excluding-state-attributes-from-recording.md
Blog post on how to exclude state attributes from recording
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/100239
=> Blog post on how to exclude state attributes from recording

docs/core/bluetooth/api.md
Add docs for new bluetooth APIs in https://github.com/home-assistant/core/pull/100774.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/100774
=> Add new bluetooth APIs for working with unavailability timeout

docs/data_entry_flow_index.md
Explain difference between options and data in the config flow.
=> Explain difference between options and data in the config flow

blog/2023-10-01-hacktoberfest-2023.md
Add a small dev blog on Hacktoberfest (so it can be linked from the release notes for 2023.10).
=> Add dev blog on Hacktoberfest 2023

blog/2023-10-03-conversion-functions-cleanup.md
The unit conversion functions were deprecated and have now been removed.  This blog post explains what has happened and what to do if someone still has code using the old functions.
- Link to relevant existing code or pull requests:  
- https://github.com/home-assistant/core/pull/78957
- https://github.com/home-assistant/core/pull/101200
- https://github.com/home-assistant/core/pull/101199
- https://github.com/home-assistant/core/pull/101204
- https://github.com/home-assistant/core/pull/101347
- https://github.com/home-assistant/core/pull/101350
=> Create blog post for clean up of deprecated unit conversion functions

docs/core/entity/datetime.md
Align documented datetime attributes with implementation and improve formatting
=> Align documented datetime attributes with implementation

docs/core/entity/date.md
Align documented date attributes with implementation and improve formatting
=> Align documented date attributes with implementation

docs/api/supervisor/endpoints.md
Document new APIs added for green baord in https://github.com/home-assistant/supervisor/pull/4556
- Link to relevant existing code or pull request: https://github.com/home-assistant/supervisor/pull/4556
=> Document new endpoints for green board

docs/api/supervisor/endpoints.md, docs/api/supervisor/models.md
Document the existing jobs API in supervisor. Also include changes made my https://github.com/home-assistant/supervisor/pull/4514
- Link to relevant existing code or pull request: https://github.com/home-assistant/supervisor/pull/4514
=> Document jobs api

docs/api/websocket.md
Add URL example to WebSocket API documentation
Not an experienced web sockets dev - spend 20 minutes trying to find documentation for what the default URL endpoint for the WebSockets API was. Couldn't find it in the Home Assistant UI, or anywhere in the docs. The only place I could find it was by reverse engineering the frontend using Chrome dev tools. A simple example like you have on the REST API page will go a long way towards getting new folks started...
=> Add URL to WebSocket API documentation

docs/voice/pipelines/index.md
Document Assist pipeline API changes for wake word detection
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/96380
=> Add wake word to Assist pipeline docs

docs/voice/pipelines/index.md
The Assist pipeline documentation currently describes the wake word stage using `wake` as the enum value, but [this should be `wake_word`](https://github.com/home-assistant/core/blob/dev/homeassistant/components/assist_pipeline/pipeline.py#L366) ([used here](https://github.com/home-assistant/core/blob/dev/homeassistant/components/assist_pipeline/pipeline.py#L473)).
=> Fix Assist pipeline wake word stage enum value

docs/internationalization/core.md
=> just a : was missing

docs/core/entity/todo.md
Add todo component developer documentation. The todo component contains a `TodoListEntity` and defines a `TodoItem` for items in the list.
- Link to architecture proposal: https://github.com/home-assistant/architecture/discussions/962
- Link to core pull request: https://github.com/home-assistant/core/pull/100019
- Link to frontend pull request: https://github.com/home-assistant/frontend/pull/17883
=> Add todo component developer documentation

docs/add-ons/configuration.md
SSIA
- This PR fixes or closes issue: relates to https://github.com/home-assistant/supervisor/issues/4644
=> Add note about removing options

docs/integration_quality_scale_index.md
Point this link at the new home for architecture discussions. See home-assistant/architecture#496
=> Fix architecture repo link

blog/2023-10-12-country_selector.md
Add blog post on new Country selector
core PR: https://github.com/home-assistant/core/pull/100963
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/100963
=> Blog country selector

docs/add-ons/configuration.md
=> Fix note markdown in add-on configuration section

docs/add-ons/configuration.md
Document new options added for config collection from users in addons added in https://github.com/home-assistant/supervisor/pull/4650
Also put a blurb explaining how and why an addon developer might use this new feature.
- Link to relevant existing code or pull request: https://github.com/home-assistant/supervisor/pull/4650
=> Document new addon config folder options

docs/core/entity/todo.md
Update todo move item API with new changes to reference the previous uid.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/102795
=> Update todo move item API to reference previous uid

docs/core/entity.md
- Add docs about how to implement entity descriptions. :tada: 
=> Add entity description docs

docs/core/entity/image.md
Clarify image entity documentation
The background is a discussion with @Lash-L 
=> Clarify image entity documentation

docs/core/entity/remote.md
- Explain that a remote entity can either be a physical device or a virtual device.
=> Add remote entity representation description

blog/2023-11-06-public-addon-config.md
Blog post announcing new public addon config folder created in https://github.com/home-assistant/supervisor/pull/4650
=> Add blog post for public addon config folder

blog/2023-11-06-public-addon-config.md
=> Correct mention of all_addon_configs option

docs/api/websocket.md
Updates docs based on this change: https://github.com/home-assistant/core/pull/98610
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/98610
=> Update docs for call_service WS API

blog/2023-11-16-service-exceptions-and-translations.md
Improve title on blog article exception handling
=> Improve title on blog article exception handling

docs/frontend/custom-ui/custom-card.md
Mention that a `documentationURL` key can be added to the window.customCards object. 
=> Update custom-card.md - add documentationURL

docs/internationalization/core.md
Improve example raising `ServiceValidationError`, late review on https://github.com/home-assistant/developers.home-assistant/pull/1961
=> Improve example raising ServiceValidationError

blog/2023-11-30-service-exceptions-and-translations.md, docs/core/platform/raising_exceptions.md
Update blog and docs on exception handling
=> Update blog and docs on exception handling

docs/add-ons/presentation.md
Adds info on stable and beta addon versions.
- ~~This PR fixes or closes issue: fixes #~~
- ~~Link to relevant existing code or pull request:~~
=> Adds info on stable and beta addon versions

docs/core/entity/todo.md
Add To-do list item due and description field developer documentation.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/104128
=> Add To-do list item due and description field developer documentation

docs/api/rest.md
- Update the REST API `/api/services/<domain>/<service>` endpoint docs. We've removed the 10 second timeout.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/104709
=> Remove rest api service timeout

docs/intent_builtin.md
Update list of supported intents. This change uses the `supported` property from `intents.yaml` so the list will stay up to date in the future.
=> Update supported intents

blog/2023-12-11-entity-description-changes.md
Add blog post about changes in entity descriptions as requested in PR https://github.com/home-assistant/core/pull/105211
=> Add blog post about changes in entity descriptions

docs/core/entity.md
Document how entity properties are consumed
This adds back some of the changes from https://github.com/home-assistant/developers.home-assistant/pull/1908, which was later reverted by https://github.com/home-assistant/developers.home-assistant/pull/1909 after we also reverted the caching of entity properties.
=> Document how entity properties are consumed

docs/core/entity.md
Improve formatting of entity property documentation
=> Improve formatting of entity property documentation

docs/core/entity/media-player.md
Align documented `media_player` properties with the implementation and improve formatting
=> Align documented media_player properties with implementation

docs/core/entity/media-player.md
Document media player volume_step property
Core PR: https://github.com/home-assistant/core/pull/105574
Note:
This PR depends on (and currently includes) https://github.com/home-assistant/developers.home-assistant/pull/2011
=> Document media player volume_step property

docs/core/entity.md
Document undocumented entity properties which are meant to be implemented by integrations
=> Document undocumented entity properties

docs/config_entries_config_flow_handler.md
Add blog post about config entry minor version
Core PR: https://github.com/home-assistant/core/pull/105479
=> Document config entry minor version

blog/2023-12-19-constant-deprecation.md
SSIA
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/105736
=> Add constant deprecation blog post

docs/core/entity.md
Add warning about changing device_class etc for entities
=> Add warning about changing device_class etc for entities

blog/2023-11-30-service-exceptions-and-translations.md
Adjust language in blog post about exception handling during service calls
For background see this discussion: https://github.com/home-assistant/core/pull/89800#discussion_r1413226004
=> Adjust language in blog post about exception handling during service calls

docs/core/bluetooth/api.md
Update Bluetooth docs for async_register_scanner changes
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/106145
=> Update Bluetooth docs for async_register_scanner changes

docs/bluetooth.md
These are no longer needed as the internals takes care of these steps.
=> Remove Bluetooth best practices that are now automatically handled

docs/core/entity/todo.md
Change update semantics of To-do items to allow clearing existing values for the extended fields.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/106208
=> Change update semantics of To-do items

blog/2023-12-18-config-entry-minor-version.md
Add blog post about config entry minor version
Core PR: https://github.com/home-assistant/core/pull/105479
=> Add blog post about config entry minor version

blog/2023-12-28-support-feature-magic-numbers-deprecation.md
Add blog post for deprecating supported features magic numbers
=> Add blog post for deprecating supported features magic numbers

blog/2023-12-18-config-entry-minor-version.md
LInk to confige entry migration docs does not work, this fixes it
=> Fix link to Configentry migration docs in blog post

docs/core/entity/todo.md
Fix a typo for the todo list delete item function
=> Fix todo list delete item typo

docs/data_entry_flow_index.md
Update documentation for FlowHandler.async_show_progress
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/107668
=> Update documentation for FlowHandler.async_show_progress

docs/documenting.md
Because git is git.. you always create a fork when making changes. But then the documentation said that it didn't create a fork which is simply incorrect.
https://github.com/home-assistant/home-assistant.io/issues/30568#issuecomment-1887702314
Fixed text so that it does say it will create a fork.
-->
=> Update documenting.md to fix a correction about fork creation

docs/data_entry_flow_index.md
=> Update documentation for `async_show_progress`

blog/2024-01-11-async-show-progress-changes.md
Add blog post about changes to `FlowHandler.async_show_progress`
=> Add blog post about changes to `FlowHandler.async_show_progress`

docs/development_environment.mdx
Add an instruction how to get the debugging of tests to work with `vscode` in Dev Container.
=> Add instructions to fix debugging tests with vscode

docs/voice/intent-recognition/template-sentence-syntax.md
Document [HASSIL local lists](https://github.com/home-assistant/hassil/pull/94)
- Link to relevant existing code or pull request: https://github.com/home-assistant/hassil/pull/94
=> Local lists in HASSIL

docs/add-ons/configuration.md
The value `int(0, 20)` of the example is not valid per the regex used to enforce this type of value. It should be `int(0,20)`.
=> Fix a typo in the example that does not match regex

docs/config_entries_index.md, docs/creating_platform_code_review.md, docs/dev_101_hass.md
Change some remaining `add_devices` or `async_add_devices` to `add_entities` or `async_add_entities`
=> Change remaining (async) add_devices to add_entities

blog/2024-01-19-entity-translations-placeholders.md
Add blogpost about translation placeholders
cc @mib1185 
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/104453 https://github.com/home-assistant/developers.home-assistant/pull/1989
=> Add blogpost about translation placeholders

blog/2024-01-19-icon-translations.md, docs/core/entity.md
Adds developer documentation + blog about icon translations.
Core PR: <https://github.com/home-assistant/core/pull/103294>
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/103294
=> Add icon translations documentation

blog/2024-01-19-icon-translations.md, docs/dev_101_services.md
The addition of icon translations, also added support for service icons.
This was missed in the previous PR that added icon translations to the docs.
=> Add missing service icon documentation

docs/development_submitting.md
Add note about the fact that the first PR someone submits requires approval before CI gets run and to just sit tight and someone will eventually approve it.
=> Add note about CI not running on first PR

blog/2024-01-22-async_services_for_domain.md
Add blog post for new async_services_for_domain
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/108671
=> Add blog post for new async_services_for_domain

docs/core/entity/light.md
Coorect typos
] iso }
and add "s" to supported_color_modes in some locations
=> Correct typos in lightentity docs

docs/core/entity/number.md, docs/core/entity/sensor.md
Add volume flow rate
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/106077
=> Add volume flow rate device class

blog/2024-01-24-climate-climateentityfeatures-expanded.md, docs/core/entity/climate.md
Add to ClimateEntity doc
Add blog post
Core PR: https://github.com/home-assistant/core/pull/101673
=> New ClimateEntityFeature for turn on turn off

blog/2024-01-30-ha-state-icon-properties-changes.md
Add blog post for ha-state-icon properties changes
=> Add blog post for ha-state-icon properties changes

docs/frontend/custom-ui/custom-strategy.md
Update documentation with the new format for strategies.
- This PR fixes or closes issue: fixes https://github.com/home-assistant/developers.home-assistant/issues/2062
=> Update strategies documentation

docs/core/entity/climate.md
Appears as `NONE` is missing in the preset options
=> Add NONE preset option in climate

docs/core/entity/light.md
Document light color_mode when rendering effects according to architecture discussion https://github.com/home-assistant/architecture/discussions/960
Core PR: https://github.com/home-assistant/core/pull/108737
=> Document light color_mode when rendering effects

blog/2024-01-23-light-color-mode-changes.md
Add blog post about changes to light color mode
Architecture discussion: https://github.com/home-assistant/architecture/discussions/960
Core PR: https://github.com/home-assistant/core/pull/108737
=> Add blog post about changes to light color mode

blog/2024-01-30-ha-state-icon-properties-changes.md
=> Fix code block in ha-state-icon properties changes blog post

blog/2024-01-24-climate-climateentityfeatures-expanded.md
Since https://github.com/home-assistant/core/pull/109195 has been merged, we should add this note
CC @gjohansson-ST 
=> Add note to ClimateEntityFeature blog post about disable flag

docs/add-ons/tutorial.md
Adding the refresh webpage as step to add your new add-on. 
So you don't need to search why it did not appeared to the list.
I was just trying to add my first add-on and it was not showing. After some digging of i did something wrong. It was just the need of refreshing the page. There was noting wrong with my setup, 
With this simple add i hope other have do not need to worry as much for the first time.
=> Add the refresh webpage as step to add your new add-on

docs/core/entity.md
Improvements in documentation as suggested by @MartinHjelmare in <https://github.com/home-assistant/developers.home-assistant/pull/2047#pullrequestreview-1860917431>
=> Fix review comments on icon translations documentation

docs/core/entity/sensor.md
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/108505
=> Add sensor example - weight of pellets for sensor with total amount

docs/operating-system/update-system.md, sidebars.js
Document the update system used in Home Assitant. This aims to help developers to understand our update system and use it also during development, so they can test development builds and iterate quickly.
=> Document Home Assistant OS update system

docs/config_entries_config_flow_handler.md
=> Document config entry unique ID must be a string

docs/config_entries_config_flow_handler.md, docs/config_entries_index.md
Document ConfigEntry objects must not be mutated by integrations and adjust examples which set version and minor version in migration handlers
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/110077
=> Document ConfigEntry objects must not be mutated by integrations

blog/2024-02-12-light-color-mode-mandatory.md
Add blog post about light color mode becoming mandatory
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/110336
=> Add blog post about light color mode becoming mandatory

docs/dev_101_hass.md
The links to the state and event bus docs are broken. Some others are too, but I don't know where all the info is. I'm fixing what I can.
=> Fix broken links

blog/2024-02-12-async_update_entry.md
Add blog post about directly altering ConfigEntry objects
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/110023
=> Add blog post about directly altering ConfigEntry objects

docs/api/supervisor/endpoints.md, docs/api/supervisor/models.md
Document changes to API and models as part of https://github.com/home-assistant/supervisor/pull/4802
- Link to relevant existing code or pull request: https://github.com/home-assistant/supervisor/pull/4802
=> Document new backup option and model changes in backup/restore

docs/add-ons/configuration.md
Document new option added to addon config in https://github.com/home-assistant/supervisor/pull/4832
- Link to relevant existing code or pull request: https://github.com/home-assistant/supervisor/pull/4832
=> Document new breaking_versions field for addons

docs/internationalization/core.md
Adjust documentation of core translations:
- The "state" key has been removed and replaced with "entity" and "entity_component"
In addition, the following sections are undocumented:
- application_credentials
- config_panel
- system_health
I'm not sure if this is a mistake or a conscious choice?
=> Adjust documentation of core translations

blog/2024-02-28-device-name-translations.md
Add blog post about device name translations
=> Add blog post about device name translations

docs/api/supervisor/endpoints.md
Document `remove_config` option added to addon uninstall in https://github.com/home-assistant/supervisor/pull/4913
- Link to relevant existing code or pull request: https://github.com/home-assistant/supervisor/pull/4913
=> Document remove config on uninstall option

docs/api/supervisor/endpoints.md
Document new device wipe API added in https://github.com/home-assistant/supervisor/pull/4934
- Link to relevant existing code or pull request: https://github.com/home-assistant/supervisor/pull/4934
=> Document device wipe API

docs/internationalization/core.md
Document device translations
Core PR: https://github.com/home-assistant/core/pull/110711
=> Document device translations

docs/development_checklist.md
=> Minor grammar fix in development_checklist.md

blog/2024-03-05-platform_entity_translations_deprecation.md
Add blog post about removing support for translations in `strings.<platform_name>.json`
=> Add blog about support for strings.platform_name.json will be removed

docs/development_testing.md
Remove the reference to `black` from the Development testing page.
=> Remove black from the Development testing page

blog/2024-03-09-import_executor_default.md
Add blog post about all integrations importing in the executor
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/112177
=> Add blog post about all integrations importing in the executor

docs/frontend/development.md
The `docker-build` task mentioned in the documentation no longer exists and was replaced by the `Dev Containers: Rebuild Container` command instead.
See: https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers#available-commands
=> Remove reference to docker-build task

docs/frontend/development.md
Improve instructions on how to change devcontainer.json for frontend development
=> Improve instructions on how to change devcontainer.json for frontend development

blog/2024-03-13-deprecate_add_run_job.md
Add blog post about deprecation of async_add_job and async_run_job
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/113260
=> Add blog post about deprecation of async_add_job and async_run_job

blog/2023-11-30-service-exceptions-and-translations.md, blog/2024-03-15-exception-translations.md, docs/internationalization/core.md
Document and publish blog post about changes in `HomeAssistantError` and sub classes with translation support.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/113305
=> Blog post and docs update Exception translations

docs/frontend/custom-ui/custom-strategy.md
The example code provided for the dashboard strategy currently just generates an error.
```
TypeError: Cannot destructure property 'area' of 'config.strategy' as it is undefined.
at StrategyViewDemo.generate
```
This change fix the demo to work as intended. 
=> Update custom-strategy.md - does not currently work

blog/2024-03-20-state_reported_timestamp.md
Add blog about State.last_reported
- https://github.com/home-assistant/core/pull/113511
- https://github.com/home-assistant/core/pull/113798
=> Add blog about State.last_reported

docs/api/supervisor/endpoints.md
Document new `virtualization` field added to `/host/info` API in https://github.com/home-assistant/supervisor/pull/4968
- Link to relevant existing code or pull request: https://github.com/home-assistant/supervisor/pull/4968
=> Document virtualization field in API

docs/api/supervisor/endpoints.md, docs/api/supervisor/models.md
Document new API to change the boot slot created in https://github.com/home-assistant/supervisor/pull/4945
- Link to relevant existing code or pull request: https://github.com/home-assistant/supervisor/pull/4945
=> Document new /os/boot-slot endpoint

docs/creating_integration_tests_file_structure.md, sidebars.js
Document integration tests file structure
=> Document integration tests file structure

docs/api/supervisor/endpoints.md, docs/api/supervisor/models.md
Document new info added to Supervisor's `/hardware/info` API by https://github.com/home-assistant/supervisor/pull/3848
- Link to relevant existing code or pull request: https://github.com/home-assistant/supervisor/pull/3848
=> Add drive info to /hardware/info

docs/development_environment.mdx
Cleanup note about pythonTestAdapter work-a-round
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/114065
=> Cleanup note about pythonTestAdapter work-a-round

docs/development_environment.mdx
Support for Python 3.11 has been dropped for the upcoming 2024.4 release. See https://github.com/home-assistant/core/pull/114220.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/114220
=> Devs should use Python 3.12 when setting up their env

blog/2023-12-19-constant-deprecation.md, blog/2024-04-03-build-images-with-uv.md
Add blog post about the replacing pip with uv in https://github.com/home-assistant/core/pull/112496
=> Add blog post about uv

blog/2024-04-08-deprecated-backports-and-typing-aliases.md
Blog post for https://github.com/home-assistant/core/pull/114883
=> Add blog post for deprecated backports and typing aliases

blog/2024-04-07-deprecate_add_hass_job.md
Add blog post about deprecating `async_add_hass_job`
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/115061
=> Add blog post about deprecating `async_add_hass_job`

docs/api/supervisor/endpoints.md
Document new option to restart core in safe mode added in https://github.com/home-assistant/supervisor/pull/5017
- Link to relevant existing code or pull request: https://github.com/home-assistant/supervisor/pull/5017
=> Document safe_mode option on /core/restart

docs/api/supervisor/endpoints.md
The boot property can either be "auto" or "manual".
=> Supervisor: Fix possible states of add-on's boot property

docs/development_environment.mdx
Update development_environment.mdx with libgammu-dev
=> Update development_environment.mdx with libgammu-dev

docs/documenting/create-page.md
Create page: add related topics section
- as defined in https://github.com/home-assistant/home-assistant.io/pull/32372
- add usage example
- Link to relevant existing code or pull request: https://github.com/home-assistant/home-assistant.io/pull/32372
=> Create page: add related topics section

docs/core/entity.md
Improve icon translation documentation
=> Improve icon translation documentation

docs/documenting/create-page.md
File header description: fix tiny typo
=> File header description: fix typo

blog/2024-04-25-always-reload-after-successful-reauth-flow.md, docs/config_entries_config_flow_handler.md
Document we reload by default after successful reauthentication and add a blog post.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/116026
=> Always reload after successful reauthentication

docs/api/supervisor/endpoints.md
Document endpoints using the Systemd "advanced logs" features.
- Link to relevant existing code or pull request: https://github.com/home-assistant/supervisor/pull/4972
=> Document new logging endpoints in Supervisor API

docs/api/websocket.md
The `return_response` service call property that prevents the "Service call requires responses but caller did not ask for responses" error response wasn't documented anywhere, so I had to read the source code to find it.
This change adds it to the example service call with a note about when to use it.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/98610
=> Add note about return_response to example of calling a service via the WS API

docs/add-ons/publishing.md, docs/add-ons/testing.md, docs/supervisor/development.md
Documentation still points to the Docker hub image, which is deprecated and broken - use the current one on ghcr.io instead.
=> Use Github Docker registry image for amd64-builder commands

docs/config_entries_config_flow_handler.md
=> qualily -> quality, fix typo

blog/2024-05-03-notify-title.md, docs/core/entity/notify.md
Add title param to notify send_message service - add blog post
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/116426
=> Add title param to notify send_message service - add blog post

blog/2024-05-01-improved-hass-data-typing.md
Blog post for https://github.com/home-assistant/core/pull/103844
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/103844
=> Add blog post for improved hass.data typing

blog/2024-05-09-improving-ci-test-execution.md
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/114381
=> Add blog post about CI speed ups

docs/dev_101_hass.md
Fixed broken link in dev_101_hass.md
- [ x ] Spelling or grammatical corrections, or rewording for improved clarity
=> Fixed broken link in dev_101_hass.md

docs/asyncio_thread_safety.md
Fix grammar errors in asyncio thread safety docs
=> Fix grammar errors in asyncio thread safety docs

docs/asyncio_thread_safety.md
Fix broken link in asyncio thread safety docs
=> Fix broken link in asyncio thread safety docs

blog/2024-05-20-llm-api.md, docs/core/llm/index.md, sidebars.js
Document the new LLM helper.
Blog: https://deploy-preview-2178--developers-home-assistant.netlify.app/blog/2024/05/20/llm-api
Docs: https://deploy-preview-2178--developers-home-assistant.netlify.app/docs/core/llm
Core PRs:
- https://github.com/home-assistant/core/pull/115464
- https://github.com/home-assistant/core/pull/117707
Incorporates https://github.com/home-assistant/developers.home-assistant/pull/2164
=> Document the LLM helper

docs/review-process.md
Include PR template in title to make it stand out more
=> Include PR template in title to make it stand out

docs/documenting/create-page.md, docs/documenting/standards.md
Documenting: apply sentence-style capitalization to headings
=> Documenting: apply sentence-style capitalization to headings

docs/add-ons/communication.md, docs/add-ons/configuration.md, docs/add-ons/presentation.md, docs/add-ons/publishing.md, docs/add-ons/security.md, docs/api/native-app-integration/webview.md
Add-ons: apply sentence-style capitalization to headings
=> Add-ons: apply sentence-style capitalization to headings

docs/api/native-app-integration.md, docs/api/native-app-integration/notifications.md, docs/api/native-app-integration/sending-data.md, docs/api/native-app-integration/setup.md, docs/api/native-app-integration/webview.md, docs/api/supervisor/endpoints.md, docs/api/supervisor/models.md, docs/api/websocket.md, docs/architecture/core.md
API: apply sentence-style capitalization to headings
=> API: apply sentence-style capitalization to headings

docs/frontend/architecture.md, docs/frontend/custom-ui/custom-card.md, docs/frontend/custom-ui/custom-strategy.md, docs/frontend/custom-ui/custom-view.md, docs/frontend/custom-ui/registering-resources.md, docs/frontend/external-authentication.md, docs/frontend/external-bus.md
frontend: apply sentence-style capitalization to headings
=> frontend: apply sentence-style capitalization to headings

docs/core/bluetooth/bluetooth_fetching_data.md, docs/core/entity/air-quality.md, docs/core/entity/alarm-control-panel.md, docs/core/entity/binary-sensor.md, docs/core/entity/button.md, docs/core/entity/calendar.md, docs/core/entity/camera.md, docs/core/entity/climate.md, docs/core/entity/conversation.md, docs/core/entity/cover.md, docs/core/entity/date.md, docs/core/entity/datetime.md, docs/core/entity/device-tracker.md, docs/core/entity/fan.md, docs/core/entity/humidifier.md, docs/core/entity/image.md, docs/core/entity/lawn-mower.md, docs/core/entity/light.md, docs/core/entity/lock.md, docs/core/entity/media-player.md, docs/core/entity/notify.md
core-entity-a-m: apply sentence-style capitalization to headings
=> core-entity-a-m: apply sentence-style capitalization to headings

docs/core/entity/notify.md, docs/core/entity/number.md, docs/core/entity/remote.md, docs/core/entity/scene.md, docs/core/entity/select.md, docs/core/entity/sensor.md, docs/core/entity/siren.md, docs/core/entity/stt.md, docs/core/entity/switch.md, docs/core/entity/text.md, docs/core/entity/time.md, docs/core/entity/todo.md, docs/core/entity/tts.md, docs/core/entity/update.md, docs/core/entity/vacuum.md, docs/core/entity/valve.md, docs/core/entity/wake_word.md, docs/core/entity/water-heater.md, docs/core/entity/weather.md, docs/core/llm/index.md, docs/core/platform/application_credentials.md, docs/core/platform/raising_exceptions.md, docs/core/platform/reproduce_state.md, docs/core/platform/significant_change.md
core: apply sentence-style capitalization to headings
=> core: apply sentence-style capitalization to headings

docs/documenting/standards.md
Documentation standard: add examples
=> Documentation standard: add examples

docs/core/llm/index.md
Document `ToolInput.device_id`
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/117884
=> Add `ToolInput.device_id`

docs/api/supervisor/endpoints.md
Document new option added in https://github.com/home-assistant/supervisor/pull/5120
- Link to relevant existing code or pull request: https://github.com/home-assistant/supervisor/pull/5120
=> Document safe mode option for /core/rebuild

docs/development_environment.mdx
=> Add core dependencies for Fedora

docs/frontend/development.md
This PR adds an extra line to the setup instructions, which I found to be necessary to get the web interface to display correctly while doing development. Without this it appeared that every translatable item in the interface was blank.
=> Add instruction to set up translations for development

docs/development_testing.md
=> Add tests requirements installation information

docs/voice/intent-recognition/template-sentence-syntax.md
I forgot to document [permutations](https://github.com/home-assistant/hassil/pull/30) when they were added to HassIL.
- Link to relevant existing code or pull request: https://github.com/home-assistant/hassil/pull/30
=> Add voice template syntax permutations

docs/development_environment.mdx
When working in WSL you are supposed to keep your files work in 1 filesystem. For Home Assistant related work that would be the LInux filesystem
from https://learn.microsoft.com/en-us/windows/wsl/filesystems
>We recommend against working across operating systems with your files, unless you have a specific reason for doing so. For the fastest performance speed, store your files in the WSL file system if you are working in a Linux command line (Ubuntu, OpenSUSE, etc). If you're working in a Windows command line (PowerShell, Command Prompt), store your files in the Windows file system.
Having documentation on changing file permissions might indicate to users that it is a good idea to have code checked out in Windows, but according to official documentation mentioned earlier and own …
=> Simplify Windows instructions

package.json, yarn.lock
SSIA, replaces #2208 and #2209
=> Update Docusaurus to v3.4.0

docs/core/integration-quality-scale/index.md, docs/core/integration-quality-scale/rules/iqs002.md
=> Add IQS002 rule

docs/core/integration-quality-scale/rules/iqs012.md
=> Add IQS012 rule

docs/core/integration-quality-scale/index.md, docs/core/integration-quality-scale/rules/iqs004.md
=> Add IQS004 rule

docs/core/integration-quality-scale/index.md, docs/core/integration-quality-scale/rules/iqs001.md
=> Add IQS001 rule

docs/core/integration-quality-scale/rules/iqs010.md
=> Add IQS010 rule

docs/core/integration-quality-scale/rules/iqs011.md
=> Add IQS011 rule

docs/core/integration-quality-scale/index.md, docs/core/integration-quality-scale/rules/iqs005.md
=> Add IQS005 rule

docs/core/integration-quality-scale/rules/iqs016.md
=> Add IQS016 rule

docs/core/integration-quality-scale/rules/iqs007.md
=> Add IQS007 rule

docs/core/integration-quality-scale/rules/iqs020.md
=> Add IQS020 rule

docs/core/integration-quality-scale/rules/iqs008.md
=> Add IQS008 rule

docs/core/integration-quality-scale/rules/iqs013.md
=> Add IQS013 rule

docs/core/integration-quality-scale/index.md, docs/core/integration-quality-scale/rules/iqs003.md
=> Add IQS003 rule

docs/core/integration-quality-scale/rules/iqs039.md
=> Add IQS039 rule

docs/core/integration-quality-scale/rules/iqs015.md
=> Add IQS015 rule

docs/core/integration-quality-scale/rules/iqs029.md
=> Add IQS029 rule

docs/core/integration-quality-scale/rules/iqs025.md
=> Add IQS025 rule

docs/core/integration-quality-scale/rules/iqs043.md
=> Add IQS043 rule

docs/core/integration-quality-scale/rules/iqs036.md
=> Add IQS036 rule

docs/core/integration-quality-scale/rules/iqs042.md
=> Add IQS042 rule

docs/core/integration-quality-scale/rules/iqs022.md
=> Add IQS022 rule

docs/core/integration-quality-scale/rules/iqs023.md
=> Add IQS023 rule

docs/core/integration-quality-scale/rules/iqs030.md
=> Add IQS030 rule

docs/core/integration-quality-scale/rules/iqs035.md
=> Add IQS035 rule

docs/core/integration-quality-scale/rules/iqs033.md
Co-authored-by: Martin Hjelmare <marhje52@gmail.com>
Add IQS033 rule
=> Add IQS033 rule

docs/core/integration-quality-scale/rules/iqs031.md
=> Add IQS031 rule

docs/core/integration-quality-scale/rules/iqs026.md
=> Add IQS026 rule

docs/core/integration-quality-scale/rules/iqs021.md
=> Add IQS021 rule

docs/core/integration-quality-scale/rules/iqs018.md
=> Add IQS018 rule

docs/core/integration-quality-scale/rules/iqs024.md
=> Add IQS024 rule

docs/core/integration-quality-scale/rules/iqs041.md
=> Add IQS041 rule

docs/core/integration-quality-scale/rules/iqs028.md
=> Add IQS028 rule

docs/core/integration-quality-scale/rules/iqs014.md
=> Add IQS014 rule

docs/core/integration-quality-scale/rules/iqs017.md
=> Add IQS017 rule

docs/core/integration-quality-scale/rules/iqs027.md
=> Add IQS027 rule

docs/core/integration-quality-scale/rules/iqs051.md
=> Add IQS051 rule

docs/core/integration-quality-scale/rules/iqs053.md
=> Add IQS053 rule

docs/core/integration-quality-scale/rules/iqs050.md
=> Add IQS050 rule

docs/core/integration-quality-scale/rules/iqs040.md
=> Add IQS040 rule

docs/core/integration-quality-scale/rules/iqs046.md
=> Add IQS046 rule

docs/core/integration-quality-scale/rules/iqs009.md
=> Add IQS009 rule

docs/core/integration-quality-scale/rules/iqs047.md
=> Add IQS047 rule

docs/core/entity/number.md
Fix typo - device class mismatch.
=> Fix typo in number device classes

docs/core/integration-quality-scale/rules/iqs045.md
=> Add IQS045 rule

docs/core/integration-quality-scale/rules/iqs032.md
Co-authored-by: Martin Hjelmare <marhje52@gmail.com>
Add IQS032 rule
=> Add IQS032 rule

docs/core/integration-quality-scale/rules/iqs034.md
=> Add IQS034 rule

docs/core/integration-quality-scale/rules/iqs052.md
=> Add IQS052 rule

docs/core/integration-quality-scale/rules/iqs049.md
=> Add IQS049 rule

docs/core/integration-quality-scale/rules/iqs054.md
=> Add IQS054 rule

docs/core/integration-quality-scale/rules/iqs044.md
=> Add IQS044 rule

docs/add-ons/configuration.md
Undocumenting the squash add-on build option as it:
1. Helps preventing addon developers from discovering it
1. Is not supported by Docker BuildKit and [will be ignored](https://github.com/home-assistant/supervisor/pull/5974/files#diff-9d9b42663129dffdf9ab9475772d2161c835d56d51ba861d73d93e9340980e74R678-R682)
1. Is dangerous anyway, if not used carefully
Please let me know if you disagree with this.
- Refs https://github.com/home-assistant/supervisor/pull/5974
/cc @agners
=> Undocument squash add-on build option

docs/voice/intent-recognition/contributing.md, docs/voice/intent-recognition/template-sentence-syntax.md, docs/voice/intent-recognition/test-syntax.md
Depending on how you navigate to a particular page the URL may end with a `/` or not. For example, on the 3 pages updated here, navigating to them by clicking a link in the side nav results in a URL without the trailing slash, but refreshing the page or visiting the URL directly (e.g. from a bookmark) results in a URL with a trailing slash.
This causes problems with relative URLs as they assume a fixed number of path segments in the URL.
Update relative URLs to start from the root (i.e. `/docs/…`) to ensure consistency regardless of whether the URLs end with a slash or not. Some of the other links in the voice docs already use this approach.
=> Fix broken links in voice docs
