home-assistant/developers.home-assistant

docs/entity_media_player.md

see this Issue in the architecture fork: https://github.com/home-assistant/architecture/issues/23

Media player: sound mode structure

---

docs/entity_index.md

- Initialize a list of a standardized attributes and explain the expected type, units, etc. for each.
- This idea was referenced [here](https://github.com/home-assistant/architecture/issues/25), a charging attribute will be added in a secondary pull request along with the corresponding constant in the main repo.
- Please propose other standardized attributes if necessary, the main purpose of this PR is to configure the formatting of dev docs.

Define standard attributes for entities

---

docs/entity_index.md

- A continuation of my earlier [PR](https://github.com/home-assistant/developers.home-assistant/pull/23) and in parallel with a HomeKit [PR](https://github.com/home-assistant/home-assistant/pull/14288) to add battery tracking.
- This was already discussed and agreed [here](https://github.com/home-assistant/architecture/issues/25).

Define battery charging standard attribute

---

README.md

* Run `script/bootstrap` to set up the docs.

Fix script name of script to set up docs

---

docs/entity_media_player.md

This PR adds developer documentation for the media player `source` and `source_list` properties, as well as the `select_source` service implementation. This PR clarifies that the source list should contain user friendly names.
Fixes https://github.com/home-assistant/architecture/issues/47

Add dev documentation for media player source

---

docs/hassio_debugging.md

Added HassOS specific instructions for authorized_keys import and noted resinOS instructions as deprecated. Unsure if the CONFIG USB should be described everywhere it is mentioned or if a link should be given for details (format, directory structure), but included a basic description for this particular process of importing the file.

Added HassOS instructions for key import

---

docs/documentation_create_page.md

To avoid confusion, was `list` replaced with `map`.
**Fixes:** #63

Use map (fixes #63)

---

docs/auth_auth_module.md
docs/auth_auth_provider.md
website/i18n/en.json
website/sidebars.json

Accompany with home-assistant/home-assistant#15489

Update auth document

---

docs/auth_auth_module.md

home-assistant/home-assistant#16314
Add MultiFactorAuthModule.async_initialize_login_mfa_step
Change async_validation => async_validate

Add MultiFactorAuthModule.async_initialize_login_mfa_step

---

docs/development_environment.md

In some cases it might be necessary to install `autoconf` before running `tox`.
I've tested Ubuntu 18.04 and it wouldn't install `DTLSSocket` otherwise. This is a requirement for `pytradfri`.

Added autoconf note

---

docs/integration_quality_scale_index.md
website/i18n/en.json
website/pages/en/versions.js
website/sidebars.json

Preview page: https://deploy-preview-92--developers-home-assistant.netlify.com/docs/en/next/integration_quality_scale_index.html
Fixes https://github.com/home-assistant/architecture/issues/20

Add quality scale

---

docs/documentation_create_page.md

As I wanted to check what the available IoT classes are, to update some of the component documentations, I noticed the link did not work, so I fixed it ;)
Unless there's some dedicated documentation available for the different IoT classes, I believe this is the correct information.

Fixed IoT class link to blog

---

docs/development_testing.md

Being new to python, pip and virtual environments, I tried running `tox` without activating the virtual environment. This should make it a little bit more clear for newcomers.

Add virtual environment info to testing (tox) doc

---

docs/development_environment.md

When running `tox` on OSX as instructed at https://developers.home-assistant.io/docs/en/development_testing.html an error is received stating `error: [Errno 2] No such file or directory: 'autoconf': 'autoconf'`. 
By installing `autoconf` via `homebrew`, this error goes away, and the `tox` tests pass. Telling OSX developers to install `autoconf` at this point in the development environment setup procedure (rather than calling it out on the testing page) seemed to make sense to me.

Instruct OSX developers to install autoconf

---

docs/documentation_standards.md

Probably an artifact from the home-assistant.io days.

Fix linkable_title artifact

---

docs/development_environment.md

Updated instructions for Windows, using WSL (Windows Subsystem for Linux).
Basically, through installing this the same instructions as for Linux should work. One "issue" is that the files are installed at `/home/<username>/.homeassistant`, which is not accessible from Windows. If launched with config path it should be possible to skip X11 forwarding completely.
Closes #106

Update instructions for Windows

---

docs/documentation_create_page.md

- Adding a boolean type in the configuration variables requires the use of `default:`.
- Added in a small working change to a `map`/`list` to "should define", since some "legacy" components cannot be described that way.

Type boolean requires documentation default.

---

docs/development_testing.md

Installing `tox-venv` on OSX allows `tox` tests to be run, per https://community.home-assistant.io/t/installing-hass-on-macos-osx/69292
Alternatively, `tox-venv` _could_ be added directly into the https://github.com/home-assistant/home-assistant/blob/dev/script/bootstrap file, but since nobody outside of OSX developers seem to be having this problem it seemed safer to simply note it in the documentation.
Without installing `tox-venv` the following occurs:
ERROR: invocation failed (exit code 100), logfile: /Users/neilcrosby/Documents/git-projects.nosync/home-assistant/.tox/py37/log/py37-0.log
ERROR: actionid: py37
msg: getenv
cmdargs: '/Users/neilcrosby/Documents/git-projects.nosync/home-assistant/bin/python3 -m virtualenv --python …

Use tox-venv to allow tests to run on OSX

---

docs/development_checklist.md

This change clarifies that hass should not be responsible for third party communication details, and that these belong in an external library.

Clarify requirement for external libraries

---

docs/development_validation.md

According to [the styleguide](https://developers.home-assistant.io/docs/en/development_guidelines.html#quotes) we should
> Use single quotes ' for single word and " for multiple words or sentences.
I think an empty string should be handled as a single word,
most of the current code seems to do it like this already.

Use single quotes

---

docs/architecture_hassio.md

Links to HASSOS and BuildRoot due to ResinOS deprecation within the Hassio project

ResinOS is deprecated

---

docs/asyncio_working_with_async.md

Based on the detailed docs `run_coroutine_threadsafe` have 2 params now: `coro` and `loop`, so the example is kinda wrong I think. Reference: https://dev-docs.home-assistant.io/en/master/api/util.html#homeassistant.util.async_.run_coroutine_threadsafe
I've ran the example code and it seems to work correct, the previous version raised `TypeError('A coroutine object is required')`.
Thanks!

Fixed example for run_coroutine_threadsafe util

---

docs/app_integration_index.md
docs/app_integration_sending_data.md
docs/app_integration_setup.md
docs/app_integration_webview.md
website/i18n/en.json
website/sidebars.json

This adds a guide to build a native app for Home Assistant. Currently extracts all the things the iOS app does (or should do). Goal is to be able to use these guide lines for a future Android app too.

Add docs for native app integration

---

docs/creating_component_code_review.md

Added a note to Creating components code review that reflects actual state of event names
reference: https://github.com/home-assistant/home-assistant/pull/17354#issuecomment-439686613

Add note about naming events for components

---

docs/entity_sensor.md

It reads in Homekit component code that the unit_of_measurement should be °C/°F. This updates the docs to match that. 
ref: https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/homekit/type_sensors.py#L52

Update unit_of_measurement Unit in temperature

---

docs/frontend_development.md

- Currently you recommend cloning the `home-assistant-polymer` repository directly. I assume you should instruct people to fork it, like you do in the [development environment documentation](https://developers.home-assistant.io/docs/en/development_environment.html)
- I had some trouble setting `development_repo` in macOS, I believe a trailing slash in the path fixed it. Have updated to a realistic macOS example path

Improve frontend development setup instructions

---

docs/config_entries_index.md
docs/config_entries_options_flow_handler.md
website/sidebars.json

https://github.com/home-assistant/home-assistant/pull/18929

Dev docs for config entry options

---

docs/entity_cover.md

Adds the details to the Covert Entity page and describes the new device class attributes that will be introduced with home-assistant/architecture#153 and home-assistant/home-assistant#21192
Closes home-assistant/architecture#153

Flush out Cover Entity docs

---

docs/creating_component_code_review.md
docs/creating_platform_code_review.md
docs/development_checklist.md

Adding some links to make the checklists easier to follow.
I was thinking about adding a good/bad example too, but adding those consequently to the checklist might make the lists unwieldy.

Dependencies: Always link to their documentation

---

docs/creating_component_code_review.md
docs/dev_101_events.md

This clarifies event naming as discussed here: https://github.com/home-assistant/home-assistant/pull/22402#pullrequestreview-218697100
While at it, I extended the example slightly to also access event data.

Clarify events

---

docs/asyncio_working_with_async.md

This asyncio util function is legacy from when we ran Python 3.4.

use the builtin asyncio function run_coroutine_threadsafe

---

docs/creating_integration_manifest.md

This adds a few fixes and updates to the Integration Manifest documentation, including fixing invalid JSON (eg using single quoted string rather than double-quotes), adds a missing `-e` to the pip install command and updates the version of `pychromecast` used by the Cast platform.

Integration manifest docs: fix JSON, update cmds

---

docs/entity_media_player.md

This documents the new remotely accessible media url property for media player entity.
Fixes https://github.com/home-assistant/architecture/issues/211
Implementation: https://github.com/home-assistant/home-assistant/pull/23337

Add remotely_accessible to media player

---

docs/external_api_rest_python.md
website/i18n/en.json
website/sidebars.json
website/versioned_sidebars/version-0.77.0-sidebars.json
website/versioned_sidebars/version-0.78.0-sidebars.json
website/versioned_sidebars/version-0.79.0-sidebars.json
website/versioned_sidebars/version-0.80.0-sidebars.json
website/versioned_sidebars/version-0.83.0-sidebars.json
website/versioned_sidebars/version-0.87.0-sidebars.json
website/versioned_sidebars/version-0.89.0-sidebars.json
website/versioned_sidebars/version-0.91.2-sidebars.json

By doing so, we make sure that the documentation reflects the removal of the Python REST API since Home Assistant 0.77.0 .
I rewrote the history (how cool!) so that it correctly reflects the status of the API not only from the next version, but for previous versions down to and including 0.77.0
I am not proficient with Docusaurus. Thanks to crosschecks that:
- There is no cleaner way to link the blog post in `docs/external_api_rest_python.md`
- The modifications of `website/i18n/en.json` makes sense
Signed-off-by: Samuel Progin <samuel.progin@gmail.com>

Document the removal of Python REST API 

---

docs/documentation_create_page.md

In recent weeks I have noticed that people add the `redirect_from` to the documentation for new integrations / components by **default** and do not really understand why this option exists (I think).
That is why I have now added a note (correct it if it can be improved), to point out to people not to do this by default and also that this can lead to not being able to see your pages in netlify.

 ✏️ Add note about using the redirect_from

---

docs/creating_component_code_review.md
docs/creating_platform_code_review.md

- We no longer require imports to be inside functions
- If a platform has a component, it will always be set up before setting up the platform. No dependency is necessary.
- Specify that a platform only needs configuration validation if it is set up directly (instead of via the component level)

Update code review requirements

---

docs/device_registry_index.md

Documentation to go along with linked PRs / Issues
See also:
* home-assistant/home-assistant#24360
* home-assistant/home-assistant-polymer#3254
* home-assistant/architecture#212

Rename via_hub to via_device

---

docs/development_environment.md

Just updating name. It's been called macOS for a little over 3 years now (https://www.wired.com/2016/06/apple-os-x-dead-long-live-macos/).

Change OS X to macOS

---

docs/hassio_debugging.md

I tried to make it clearer that the SSH setup here (port 22222) was different to the SSH add-on setup (port 22) and what issues would crop up if the later was used in this context. 
It took me a while to figure out what was going on and I felt that the doc needed this clarification.

Extra warning about use of SSH add-on

---

docs/device_registry_index.md

Param is `config_entry_id`, not `config_entry`
see: https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/helpers/device_registry.py#L93

Fix named param typo in device_registry example

---

docs/documentation_standards.md

Our documentation/website has been updated to not need the `linkable_titles` anymore.
PR that removed it:
<https://github.com/home-assistant/home-assistant.io/pull/9772>

Removes linkable_title requirement from documentation docs

---

docs/documentation_index.md

Gem install will now fail with Ruby 2.3.0, since in [the Gemfile](https://github.com/home-assistant/home-assistant.io/blob/07dcd146eab40038b524e388196e6761045a8b47/Gemfile#L3), Ruby > 2.5.0 is required.

Update minimum ruby version

---

docs/asyncio_categorizing_functions.md

The import and decorator syntax was Python 3.4, with Python 3.5 this
became much nicer and the async keyword is now used.

Clarify declaring function async

---

docs/external_api_websocket.md

It is required. Documentation: https://github.com/home-assistant/home-assistant/blob/4f8a93fb3e1cf61decc05a8e55fa254298168915/homeassistant/components/camera/__init__.py#L92

Add entity_id to camera_thumbnail

---

docs/entity_index.md

This PR adds docs for the added property enabled, that was introduced with [#26236](https://github.com/home-assistant/home-assistant/pull/26236).
This should be in compliance with [#276 Entity Management](https://github.com/home-assistant/architecture/issues/276).

Add enabled property to entity doc

---

docs/device_automation_action.md
docs/device_automation_condition.md
docs/device_automation_index.md
docs/device_automation_trigger.md
website/i18n/en.json
website/sidebars.json

Just a quick write up. Relies on https://github.com/home-assistant/home-assistant/pull/26880

Initial draft device automations docs

---

docs/development_environment.md

`script/setup` will fail due to a path permissions issue if you do not clone the project to a location within the WSL filesytem.

Clarify project location in WSL

---

docs/hassio_hass.md

I was going through this while trying to get the front end set up to work on another PR and noticed it was out of date and had trouble getting everything working.  I'm updating it to hopefully better reflect what I had to do to get it working and update the latter portion as it seems like manually building every time a change is made is no longer necessary.  Also updated the configuration.yaml example as the docs here https://developers.home-assistant.io/docs/en/frontend_development.html#configuring-home-assistant say to set up frontend.development_repo not hassio.development_repo.  
Hopefully this is correct but let me know if I'm completely misunderstanding this document as I'm pretty new to getting everything set up for local development. :)

Update Frontend development documentation

---

docs/documentation_create_page.md

Make the need for newlines more clear in the [example about note html section](https://developers.home-assistant.io/docs/en/documentation_create_page.html#html).

Update documentation_create_page.md with more clear note html example

---

docs/lovelace_custom_card.md

Correcting "Boiler Plate Card" to "Boilerplate Card"

Tiny renaming fix

---

docs/integration_quality_scale_index.md

Added documentation link for "Has a code owner" in the Gold "Integration Quality Scale" standard.

Added docs link for "Has a code owner"

---

docs/documentation_index.md

Changed the location of the integration/platform documentation from source/_components/ to source/_integrations in the developers documentation.

Change location of integrations documentation

---

docs/frontend_external_auth.md

Under the 'Revoke Token' Section the callbacks should be:
```javascript
window.externalApp.revokeExternalAuth({
callback: 'externalAuthRevokeToken'
});
```
and
```javascript
window.webkit.messageHandlers.revokeExternalAuth.postMessage({
callback: 'externalAuthRevokeToken'
});
```

Corrected error in revoke token callback

---

docs/development_testing.md

There are a couple of reports (like this [one](https://github.com/home-assistant/home-assistant/issues/18659)) that there are issues to build stuff and this is problematic for the testing with tox.

Add requirements on OS level for Fedora and Ubuntu

---

docs/app_integration_setup.md

The schema looks to require another parameter, adding it to the documentation.
https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/mobile_app/const.py#L106

mobile_app integration missing parameter

---

docs/creating_integration_manifest.md

Doc update for https://github.com/home-assistant/home-assistant/pull/28285

Update SSDP integration manifest

---

docs/development_testing.md

Fix typo in development_testing.md

---

docs/development_environment.md

I was following the instructions, but they don't work at all for Windows.  Issues fixed:
* The old command would use python3.6, but home assistant requires 3.7
* Picks up the change in https://github.com/home-assistant/developers.home-assistant/pull/335 for the Windows section.
* Explicitly use 3.7 when setting up the venv, since on some systems `python3` points to 3.6, not 3.7

Update Developement Environment Docs for Windows

---

docs/frontend_development.md
docs/hassio_hass.md
docs/lovelace_custom_card.md
website/i18n/en.json
website/i18n/no-NO.json
website/sidebars.json
website/translated_docs/no-NO/frontend_development.md
website/translated_docs/no-NO/hassio_hass.md
website/translated_docs/no-NO/lovelace_custom_card.md

Otherwise trivial, but removed HASS altogether from Hass.io integration development sidebar entry, "Home Assistant" there would make the entry probably too wide, and I think it's not required.

Be consistent with Home Assistant spelling

---

docs/creating_integration_manifest.md

This add the added Integration Quality Scale documentation, that is recently added to the integration manifest.
Wrote it in a way, that we encourage developers to get their integration scored.

Update integration manifest page to include the new quality scale

---

docs/documentation_create_page.md

Several things in this PR:
- Update a couple of links to link to the integrations page (instead of the old components index).
- Some tiny Markdown styling improvements
- Document the rename of `ha_qa_scale` to `ha_quality_scale`
- Document the addition of the `ha_codeowners`

Update documentation frontmatter information to include latest changes

---

docs/external_api_rest.md

The docs don't make it clear that updating a state of an entity does not impact the actual integration and only impacts HA's state. This came up in #homeassistant today so I added a note to hopefully prevent people from getting confused in the future.

Add note under /api/states API endpoint section to distinguish between state updates and service calls

---

docs/entity_registry_disabled_by.md

@frenck  made me realize that our current recommendation for integrations that want to offer options to disable certain type of entities is way too complicated.
This PR updates the recommendation from a hybrid approach where some entities could be enabled, to be black-white: if entity type is disabled, they are removed from the entity registry and will no longer be offered to HA. Easy to follow and easy to reason about.
CC @Kane610

Update disabled_by recommendation

---

docs/integration_quality_scale_index.md

Require gold integrations to clean up entity and device registry entries if it's no longer available via the API (because user removed it from Hue hub etc)

Add cleanup to gold quality scale

---

docusaurus.config.js

These feeds used to be available, but recently disappeared - possibly due to the move to docusaurus 2. This re-enables their generation ([see docs](https://v2.docusaurus.io/docs/blog/#feed)).

Re-enable RSS/Atom feed for the blog

---

docs/lovelace_custom_card.md

HACS is also proposing `module` and it has come to my attention that 'js' should go...

'type: js' updated to 'type: module' (deprecation)

---

docs/entity_climate.md

took the const values for `Supported Features` from https://github.com/home-assistant/home-assistant/blob/master/homeassistant/components/climate/const.py and added to an additional column. Also 1 minor copypastitis in swing_mode prop

Added Const Values to Climate Entity page

---

docs/development_guidelines.md

Adds notation about the preferred way of typing out functions, see https://github.com/home-assistant/core/pull/32255#discussion_r385644660
CC @MartinHjelmare

Add typing to style guidelines

---

docs/frontend_data.md

While trying to learn about how the frontend works, I was looking for a way to see what data was available in `hass` in the frontend, but I could not find a simple way to access it in the docs. I searched #devs_frontend in Discord and found this call suggested by @balloob (and originally @thomasloven). Thought it would be a good idea to add it to the docs for future devs

Add method to return 'hass' object from browser console to docs

---

docs/integration_fetching_data.md

Update docs to use new PR from https://github.com/home-assistant/core/pull/33588

Document using async_on_remove with DataUpdateCoordinator

---

docs/development_catching_up.md

The bit about adding the upstream remote should happen before the rebase, hence it is better to mention it first.

Move remote upstream info to top

---

docs/entity_binary_sensor.md

Parent https://github.com/home-assistant/core/pull/34203

Update binary_sensor for DEVICE_CLASS_BATTERY_CHARGING

---

docs/config_entries_config_flow_handler.md

Just updating the translation example by moving the `"title"` field outside of `"config"` so It matches the latest changes in the translations validator.

Update translation example

---

docs/documentation_standards.md

According to this [comment](https://github.com/home-assistant/home-assistant.io/pull/13005#pullrequestreview-395308177), the configuration section is only for YAML configuration.  This isn't currently stated in the docs.
As a comment, there is no explanation on the preferred documentation style for config flows.  It would be helpful to have a set of standards here for consistencyn across the documentation.

Clarify configuration section

---

docs/development_environment.md

With the Windows 10 20H1 going to the Release Preview, WSL 2 is now available in a stable form. WSL 2 is supported by edge builds of Docker Desktop and so we can use devcontainers on WIndows 10 Home 🎉
Little tweak to the instructions to cover this case. When 20H1 goes to release (May?) WSL 2 should probably be the recommended method for all levels of Windows.
Also, a minor tweak to the heading levels as Docusaurus assumes `#` are Page headings and doesn't put them in the TOC on the right. 
Also also, a minor correction to capitalisation of headings for consistency

Update Docker requirements

---

docs/entity_media_player.md

As discussed in https://github.com/home-assistant/core/pull/34550 and https://github.com/home-assistant/core/pull/34412.

Allow integration-specific media content types

---

docs/entity_cover.md

Documentation update for home-assistant/core/pull/34595

Rename CoverDevice to CoverEntity

---

docs/entity_alarm_control_panel.md

Documentation update for home-assistant/core/pull/34590

Rename AlarmControlPanel to AlarmControlPanelEntity

---

docs/entity_lock.md

Documentation update for home-assistant/core/pull/34594

Rename LockDevice to LockEntity

---

docs/entity_climate.md

Documentation update for home-assistant/core/pull/34591

Rename ClimateDevice to ClimateEntity

---

docs/entity_media_player.md

Documentation update for home-assistant/core/pull/34592

Rename MediaPlayerDevice to MediaPlayerEntity

---

docs/entity_switch.md

Documentation update for home-assistant/core/pull/34673

Rename SwitchDevice to SwitchEntity

---

docs/entity_light.md

Documentation update for home-assistant/core/pull/34593

Rename Light to LightEntity

---

docs/data_entry_flow_index.md

Update the docs with instructions on pre-filling values using either `default` or `suggested_value`, and the differences between them.

Update Data Entry Flow docs with field pre-fill

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.npmrc
.vscode/cSpell.json
.vscode/extensions.json
.vscode/tasks.json
README.md
package.json
yarn.lock

Enables devcontainers, uses `by-node-env` to detect if we are in a devcontainer (set by `ENV NODE_ENV=devcontainer` in `Dockerfile`). If so `--poll` and `--host 0.0.0.0` flags are added to the `start` command. We have to poll for file changes as fs-events and inotify (used to detect file changes normally) don't work in lightweight devcontainers
Also contains some bells and whistles for VS Code and an overhaul of the README.md to match the new development environments.

Enable devcontainer

---

docs/entity_fan.md

Add `oscillating` to the Fan Entity property list.
Related to home-assistant/core#35248

Add oscillating property to Fan Entity

---

docs/instance_url.md
sidebars.js

This PR adds the developer documentation for the new Home Assistant `async_get_url` helper.
Related PRs:
- Core: <https://github.com/home-assistant/core/pull/35224>
- Frontend: <https://github.com/home-assistant/frontend/pull/5755>
- JavaScript WebSocket: <https://github.com/home-assistant/home-assistant-js-websocket/pull/115>
- User documentation: <https://github.com/home-assistant/home-assistant.io/pull/13307>
- Developers blog post: <https://github.com/home-assistant/developers.home-assistant/pull/498>

Add get_url helper documentation

---

docs/creating_integration_manifest.md

Adds documentation for the new `issue_tracker` manifest property.
This property is mainly in place for custom integrations.
For more information, see the parent PR: <https://github.com/home-assistant/core/pull/35153>

Add issue_tracker property manifest documentation

---

docusaurus.config.js

This set a start for the navbar changes in preparation for a bigger move.
This makes a bit more sense, but isn't complete. I make this change to prevent myself from conflicting changes constantly.

Switch item in navbar in preparation of larger move

---

docs/internationalization.md
docs/internationalization/core.md
docs/internationalization/custom_integration.md
docs/translations.md
docusaurus.config.js
sidebars.js
static/_redirects

This PR moves and extract internationalization/translations from the misc menu.
Internationalization is part of Home Assistant and belong in that menu.
For Translations, I've created its own item on the menu bar. Mainly because we get quite often people don't know how this works.

Move and extract internationalization/translations

---

docs/internationalization/core.md

Common strings live in `homeassistant/strings.json` instead of `homeassistant/components/strings.json`

Fix path to common strings

---

docs/documentation_standards.md

This might be more of a discussion, therefor marking it as "WIP".
The standard for docs sates:
> Use capital letters and `_` to indicate that the value needs to be replaced. E.g., `api_key: YOUR_API_KEY` or `api_key: REPLACE_ME`.
And then continues with an example that uses `service: notify.notify` which is misleading in my opinion since most service names have fixed names (for example `media_player.media_play`) but `notify.notify` is not.  Following the above rule I would like to suggest to change the example to:
```
service: notify.YOUR_NOTIFICATION_COMPONENT
```

Change example from notify.notify to notify.YOUR_NOTIFICATION_COMPONENT

---

docs/internationalization/core.md

`::` should be used instead of `.` in string reference. Also, `already_configured` seems not existed in common strings.

Fix common string reference example

---

docs/development_environment.md

This updates the WSL 2 URL in docs/development_environment from https://docs.microsoft.com/windows/wsl/wsl2-install to https://docs.microsoft.com/windows/wsl/install-win10#update-to-wsl-2. The old link points to a 404 and I found that this new link seems to be the appropriate replacement.

Update the WSL 2 URL in docs/development_environment

---

docs/api/rest.md

Update Python Requests Docs URL on [REST API page](https://developers.home-assistant.io/docs/api/rest/). The old URL pointed to a 404 and this new link seems to be the proper replacement.

Update Python Requests Docs URL on REST API page

---

docs/translations.md

Update Lokalise key referencing URL on [translation page](https://developers.home-assistant.io/docs/translations/). The old URL pointed to a 404 and this new link seems to be the proper replacement.

Update Lokalise key referencing URL on translation page

---

docs/documenting/standards.md

Update the create page URL on the [standards page](https://developers.home-assistant.io/docs/documenting/standards/). The old URL pointed to a 404 and this new link seems to be the proper replacement.

Update the create page URL on the standards page

---

docs/development_environment.md

Update "Frontend" URL on ["Set up Development Environment" page](https://developers.home-assistant.io/docs/development_environment/). The old URL pointed to a 404 and this new link seems to be the proper replacement.

Update "Frontend" URL on "Set up Development Environment" page

---

docs/auth_api.md

Fix authentication message URL on [Authentication API page](https://developers.home-assistant.io/docs/auth_api/). The old URL pointed to a 404 and this new link seems to be the proper replacement.

Fix authentication message URL on Authentication API page

---

docs/operating-system/debugging.md

Update "Supervisor Architecture" URL on ["Debugging the Home Assistant Operating System" page](https://developers.home-assistant.io/docs/operating-system/debugging/). The old URL pointed to a 404 and this new link seems to be the proper replacement.

Update "Supervisor Architecture" URL on "Debugging the Home Assistant

---

docs/api/native-app-integration/setup.md

Update "implementing encryption" URL on ["Native App Integration Setup" page](https://developers.home-assistant.io/docs/api/native-app-integration/). The old URL pointed to a 404 and this new link seems to be the proper replacement.

Update "implementing encryption" URL on "Native App Integration Setup

---

src/pages/index.js

Add titles to the iframe elements found on the homepage. This is a web accessibility feature recommended by [Google's Lighthouse Auditing tool](https://web.dev/frame-title/?utm_source=lighthouse&utm_medium=devtools).

Add title to iframes found on homepage

---

docs/config_entries_config_flow_handler.md

The example code uses voluptuous' schema validation, but the library isn't imported, leading to errors if the code snippet is used as-is.

Add import to make example code usable

---

docs/development_environment.md

Adds a tip box explaining what to do if localhost:8123 doesn't work with WSL or WSL2.

Add steps for loading instance in WSL

---

docs/development_environment.md

`ifconfig` has apparently be deprecated for years (I had no idea 😕) and is not included in Ubuntu 20.04 (at least the WSL version). I've updated instructions to use `ip addr` instead.
[Depreciation notice for`net-tools` from 2009!](https://lists.debian.org/debian-devel/2009/03/msg00780.html)

Update WSL IP address steps

---

docs/api/websocket.md

Adds a depreciation notice against the `camera_websocket` websocket.
Maybe the admonition is a little OTT?
- This PR fixes or closes issue: fixes #584
- Link to relevant existing code or pull request: home-assistant/core#32473

Add depreciation notice against camera_thumbnail WS

---

docs/development_environment.md

Streamlines setting up a dev env.
- Remove CentOS instructions
- Point at Microsoft documentation on how to setup WSL
- Merge some instructions that could be in 1 line
- Remove `$` from shell command blocks containing a single command
- Remove `venv` instructions as it will be part of `script/setup`
- Remove `logging` config as it will be part of `script/setup`
Requires core PR: https://github.com/home-assistant/core/pull/37075

Streamline setting up dev env

---

docs/translations.md

Adds language specific guidelines to the developer documentation and set up some guidelines like the formal/informal addressing in German.
As discussed in https://github.com/home-assistant/architecture/issues/346.
I used the "Du-Form" for the German guidelines, but this can be discussed. @fabaff contributed many translations using the "Sie-Form", though I think the "Du-Form" would be more appropiate for us.

Add language specific guidelines

---

docs/frontend/external-bus.md

Propose to add a new external bus feature to allow frontend to trigger writing tags in the app.
CC @zacwest for iOS
CC @bramkragten for frontend
CC @JBassett for Android

Propose to add `tag/write` to frontend external bus

---

.idea/developers.home-assistant.iml
docs/core/entity/water-heater.md

The documentation for the [Water Heater Entity](https://developers.home-assistant.io/docs/core/entity/water-heater/) differs significantly from what is actually implemented in [`WaterHeaterEntity`](https://github.com/home-assistant/core/blob/dev/homeassistant/components/water_heater/__init__.py#L131).  This should bring them more into alignment.
* Fix `temperature`  => `current_temperature` ([Code](https://github.com/home-assistant/core/blob/dev/homeassistant/components/water_heater/__init__.py#L222))
* Fix `away_mode` => `is_away_mode_on` and correct return type ([Code](https://github.com/home-assistant/core/blob/dev/homeassistant/components/water_heater/__init__.py#L242))
* Put backticks around, e.g., `str` and `None`
* Add missing properties:
* [`target_temperature`, …

Improve water heater

---

docs/add-ons/configuration.md

Proposal to add support for a media folder.
The target of this folder is to share media files.
It is exposed to the Home Assistant container and add-ons are allowed to map it (which this PR documents).
- Link to relevant existing code or pull request: https://github.com/home-assistant/supervisor/pull/2034

Add add-on media folder map option

---

blog/2020-10-02-lazyMoreInfo.md

Add blog about lazy loading more info controls

Add blog about lazy loading more info controls

---

package.json
yarn.lock

Docusaurus currently suffers from two known vulnerabilities:
- [CVE-2020-15168](https://nvd.nist.gov/vuln/detail/CVE-2020-15168), low/medium severity:
This is due to `node-fetch < 2.6.1`, which here is called by `flux` which in turn calls a massively out of date version of `fbjs`. See facebook/flux#504. This is patched here by forcing the use of `"fbjs" : "2.0.0"`. This is a pretty huge jump from `0.8.17` but I've seen no adverse reactions locally or on another deployed site. The call chain is
```txt
> yarn why node-fetch
@docusaurus#preset-classic#@docusaurus#plugin-debug#react-json-view#flux#fbjs`
```
So it is only `@docusaurus/plugin-debug` that needs it.
- [CVE-2020-7720](https://nvd.nist.gov/vuln/detail/CVE-2020-7720), high/critical severity:
This comes from `node-forge < 0.10.0` …

Fix security vulnerabilities 

---

docs/api/supervisor/endpoints.md
docs/api/supervisor/models.md

Supervisor version handling over API

---

docs/auth_api.md

It's much easier to grab a long-lived access token via the web frontend, so mention that *first*.
It appears that the previous ordering was just an artifact of the fact that web frontend support was added later than websocket support. See #151.
Mention the easy way to get a long-lived access token *first*; mention the hard way second.

Tweak "Long-Lived Access Tokens" documentation

---

docs/internationalization/core.md

- Add the `progress` key to the translation strings under `config`.

Add progress key to available translation keys

---

docs/entity_analog_switch.md
docs/entity_number.md

Add developer documentation for the new `number` component.
- Link to relevant existing code or pull request: home-assistant/core#42735

Add new number entity support

---

docs/core/entity.md

The battery must be now a sensor, not an attribute.
Following [this](https://github.com/home-assistant/core/pull/43895/files#r543557187) comment, battery state must be now a sensor entity. So related attributes description must be removed. 

Remove battery related attributes description

---

docs/api/websocket.md

Add context to the example outputs.  Brings documentation inline with actual output from these commands.
Adding context to the results of call_service and event websocket results.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/44458

Add "context" to result of websocket calls where applicable

---

blog/2020-10-02-lazyMoreInfo.md

Simply updates the scoped elements URL found in the 2020-10-02 Blog Post from https://open-wc.org/scoped-elements/ to https://open-wc.org/docs/development/scoped-elements/

Update Scoped Elements URL from 2020-10-02 Blog Post

---

docs/add-ons/configuration.md

It is always nice if an add-on doesn't need any options (and thus might not have a schema).
This PR adds a default empty dictionaries to the `schema` and `options` configuration parameters of an add-on configuration, mainly for cleaner add-on configurations.
For a future improvement, it would be nice if we could expose if the add-on has options (and thus a schema) and hide the config from the UI based on that.
- Link to relevant existing code or pull request: https://github.com/home-assistant/supervisor/pull/2421

Set a default for add-on options and schema config

---

docs/add-ons/configuration.md

Set a default for the add-on `startup` configuration, making the configuration parameter optional.
The default is set to `application`. Looking at the add-ons, most use `service`, however, I think `application` is a sane and safe default. Add-ons that have a more specific startup requirement can still use this option of course.
This PR allows cleaning up add-on configurations a bit more and is backward compatible.
- Link to relevant existing code or pull request: https://github.com/home-assistant/supervisor/pull/2419

Set a default for add-on startup config

---

docs/documenting/standards.md

`int` is not a valid documentation type (it breaks in CI even); `integer` should be used instead.
From: https://github.com/home-assistant/home-assistant.io/pull/16268#issuecomment-766788200

Fix use of incorrect variable type

---

docs/add-ons/configuration.md
docs/api/supervisor/endpoints.md
docs/api/supervisor/models.md

New hardware layer Supervisor

---

docs/add-ons/tutorial.md

This fixes a small typo to hopefully help others avoid looking for a button that doesn't exist.
The "Making your first add-on" tutorial simply refers to the "Reload" as the "refresh" button. This PR changes the documentation to use its correct name.

Fix button title from "refresh" to "Reload"

---

docs/add-ons/tutorial.md

I was going through the tutorial and this one stuck out to me.

Fix typo in add-ons tutorial

---

docs/device_registry_index.md

Entities will not be connected to a device if unique_id is not set.
Extend documentation to clearly state the requirement to define a unique_id for entities being connected to a matching device.

Add tip for required unique_id for device_registry

---

docs/creating_platform_code_review.md

> The documentation contains two references
As mentioned in issue #822, two pages refer to a dead website for a PyPI tutorial. Only one link has been replaced in PR #823. This PR also replaces the link on the other page.
- This PR fixes or closes issue: fixes #822 
- Link to relevant existing code or pull request: #823

Replace PyPI tutorial dead link

---

docs/add-ons/configuration.md

Document the new `journald` configuration option available for add-ons that need access to the logs of the host system.
- Link to relevant existing code or pull request: https://github.com/home-assistant/supervisor/pull/2722

Add journald option for add-on configuration

---

docs/data_entry_flow_index.md

Remove comment: `pylint: disable=unused-import`
With pylint `2.7.3`, this isn't necessary anymore.
PR to update pylint: https://github.com/home-assistant/core/pull/48488

Remove pylint unused-import

---

docs/core/entity/light.md

Document updated LightEntity support for color_mode from core PR https://github.com/home-assistant/core/pull/47720

Document updated LightEntity support for color_mode

---

docs/development_testing.md

The command I use in the dev container is `pytest`, however the documentation says the command is `py.test`. Removing the `.` would simplify the documentation as it will match the pytest documentaiton https://docs.pytest.org/en/stable/usage.html

Change py.test -> pytest

---

docs/core/entity/media-player.md

Add the documentation for grouping media players. The actual feature has been discussed in the following arch issue: https://github.com/home-assistant/architecture/issues/364
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/41193

Add documentation for grouping media players

---

docs/development_checklist.md
docs/development_guidelines.md
docs/development_typing.md

Adjusts the dev docs on multiple locations about the changing behavior of our CI in regards of type hinting.
Supports: https://github.com/home-assistant/core/pull/49270
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/49270

Update hints about type hints

---

docs/development_guidelines.md

Follow up to https://github.com/home-assistant/developers.home-assistant/pull/901

Fix typos in type checking section

---

docs/creating_component_index.md
sidebars.js

New developers can easily become overwhelmed by all the details in a project as complex as Home Assistant. When a new developer wishes to create an integration, the first thing they should be directed to do is create a scaffold for their proposed integration.
By describing the file structure and how a `manifest.json` file are formatted implies that the developer needs to create them before running the `script.scaffold` python script. However, that is not the case.
I propose we move "Creating your first integration" to become the first thing a potential developer would read when reading the "Building Integrations" documentation.

Make "Creating your first integration" step 1 in Building integrations

---

docs/supervisor/development.md

It looks like this functionality has been refactored into scripts/supervisor.sh, so the rebuild automatically happens.

Removed reference to "Build Supervisor" as task no longer exists

---

docs/api/native-app-integration/notifications.md

safed_device_name seems to be wrong in this context. saved_device_name seems correct.
On the Push Notifications page, "safed_device_name" is mentioned. This seems wrong in this context and should be "saved_device_name".
https://github.com/home-assistant/developers.home-assistant/blob/master/docs/api/native-app-integration/notifications.md

Update notifications.md to fix possible spelling error

---

docs/core/entity/switch.md

As discussed [architecture#579](https://github.com/home-assistant/architecture/discussions/579,) I suggest to update the documentations that the following properties of the Switch entity are deprecated and should not be used by new integrations:
- `current_power_w`
- `today_energy_kwh`

Deprecate Switch entity properties

---

docs/operating-system/debugging.md

The current documentation does not describe how to stop the SSH access to the host if it is no longer needed. The service will be stopped and the keys removed if the Home Assistant device is booted with an empty CONFIG drive inserted.
Documentation update for clarity
- Link to relevant existing code or pull request: https://github.com/home-assistant/operating-system/blob/59b9d82a55a8141adb86d8d95d3f602428da7c22/buildroot-external/rootfs-overlay/usr/sbin/hassos-config#L80

Add information on turning off OS SSH access

---

docs/core/entity/humidifier.md
docs/core/entity/number.md
docs/core/entity/select.md
docs/core/entity/siren.md

Properties info "Properties should always only return information from memory..." is not consistent among all entities
See:
https://developers.home-assistant.io/docs/core/entity/cover
https://developers.home-assistant.io/docs/core/entity/humidifier

Consistent properties info for all entities

---

docs/core/entity/siren.md

`available_tones` was missed in the original PR for this platform.

Add available_tones property to siren docs

---

docs/core/entity/siren.md

Added dictionary as a possible type for `siren.available_tones` in https://github.com/home-assistant/core/pull/54198 . Dependent on https://github.com/home-assistant/developers.home-assistant/pull/1015 getting merged first.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/54198

Document new dict format for siren.available_tones

---

blog/2021-08-12-sensor_temperature_conversion.md

Add blog post about sensor temperature conversion

Add blog post about sensor temperature conversion

---

blog/2021-08-16-state_class_total.md
docs/core/entity/sensor.md

Update documentation and dev blog post with removal of STATE_CLASS_TOTAL and SensorEntity.last_reset

Update documentation and dev blog post with removal of STATE_CLASS_TOTAL and SensorEntity.last_reset

---

docs/internationalization/core.md

Update developer documentation to make it easier.
After running script.translations develop, the local browser still has old information, even if HA core is restarted.  The need to update browser cache is not intuitive. I have been puzzled by this more than once, so this hint will remind people (including me) and avoid wasting time.

Add hint to refresh browser cache

---

docs/operating-system/debugging.md

It looks like the name of the container has changed, or was always like that.
```
CONTAINER ID   IMAGE                                                      COMMAND                  CREATED          STATUS          PORTS                                   NAMES9fd6cec37393   homeassistant/aarch64-hassio-multicast:2021.04.0           "/init"                  17 minutes ago   Up 17 minutes                                           hassio_multicast
1e9e2e1ceec6   ghcr.io/home-assistant/aarch64-hassio-cli:2021.08.1        "/init /bin/bash -c …"   17 minutes ago   Up 17 minutes                                           hassio_cli
3ce15776c985   ghcr.io/home-assistant/aarch64-hassio-audio:2021.07.0      "/init"                  17 minutes ago   Up 17 minutes …
```

Fix container name

---

docs/add-ons/configuration.md

Updated version and image docs to match logic on supervisor. When image is set it requires version and version should be docker tag name.
- This PR fixes or closes issue: fixes #879

Fixed addon configuration docker image and version notes

---

docs/core/entity/sensor.md

Updates developer documentation on the `native_value` return type for sensors.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/59971

Update sensor documentation for date  & timestamp devices classes

---

docs/core/entity/binary-sensor.md

Binary sensors currently cannot have a None state value (which translates to an "unknown" state). This PR adjusts that.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/60193

Allow binary sensor state to be None

---

docs/network_discovery.md

Didn't know I had to await those functions, so I'm helping out more beginners like me
I'm adding some missing `await`s to Networking and Discovery
Fixing this would stop things like [this](https://discord.com/channels/330944238910963714/554842238073700352/925423705818009640) from happening

Add missing `await`s under SSDP

---

docs/documenting/standards.md

I was working on updating some docs, and realized that `configuration_base` appears nowhere in the code, but `configuration_basic` does. I think that may be what the docs meant to refer to.

Fix a typo in documenting/standards

---

docs/integration_quality_scale_index.md

Clarify gold level quality scale test requirements as when I read it it was unclear to me that we require tests coverage for all modules, does not change any requirement just make them more clear.

Clarify gold level quality scale test requirements

---

blog/2019-07-31-black.md

Change the editor instruction link on the [Adopting Black](https://developers.home-assistant.io/blog/2019/07/31/black/) page from https://github.com/psf/black#editor-integration to https://black.readthedocs.io/en/stable/integrations/editors.html as the old link no longer linked anywhere

Fix black editor link

---

docs/intent_firing.md

- Added "reprompt" for the intent response
https://developer.amazon.com/en-US/docs/alexa/custom-skills/request-and-response-json-reference.html#response-object
"The object containing the outputSpeech to use if a re-prompt is necessary.
Used if your service keeps the session open after sending the response (shouldEndSession is false), but the user doesn't respond with anything that maps to an intent defined in your voice interface while the microphone is open. The user has a few seconds to respond to the reprompt before Alexa closes the session.
If the reprompt doesn't have a value, Alexa doesn't reprompt the user."
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/65256

Add "reprompt" for the intent response

---

docs/add-ons/configuration.md

For https://github.com/home-assistant/frontend/pull/11596

Add note about advanced mode for experimental and deprecated add-ons

---

docs/api/websocket.md

Document new validate_config command https://github.com/home-assistant/core/pull/67057

Document validate_config

---

docs/api/rest.md

Document `no_attributes` flag for history api
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/68352

Document `no_attributes` flag for history api

---

docs/core/entity/update.md

- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/68842

Add documentation for release notes method for update entity

---

docs/core/entity/sensor.md

Document sensor entity options

Document sensor entity options

---

docs/core/entity/vacuum.md

Documents the new `VacuumEntityFeature`.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/69121

Add EntityFeature enum to Vacuum

---

docs/core/entity/media-player.md

Documents the new `MediaPlayerEntityFeature`.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/69119

Add EntityFeature enum to Media Player

---

docs/core/entity/lock.md

Documents the new `LockEntityFeature`.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/69118

Add EntityFeature enum to Lock

---

docs/core/entity/light.md

Documents the new `LightEntityFeature`.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/69103

Add EntityFeature enum to Light

---

docs/core/entity/fan.md

Documents the new `FanEntityFeature`.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/69091

Add EntityFeature enum to Fan

---

docs/config_entries_config_flow_handler.md

When the function `self._abort_if_unique_id_configured()` is used inside the config flow, the key `already_configured` from the text resources can be used to give feedback to the user about what happened. This was not documented before.
https://github.com/kongo09/core/blob/db10c313b5737c08e33b2dccdbf4f6ea01119966/homeassistant/config_entries.py#L1258

Abort config flow for already_configured

---

docs/core/entity/light.md

Documents the `ColorMode` enum for light entities.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/69223

Add ColorMode enum to light platform

---

docs/core/entity/camera.md

All `STREAM_TYPE_*` constants from the Camera platform, have been deprecated. Use the new `StreamType` enum instead.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/69871

Replace Camera STREAM_TYPE_ constants with StreamType enum

---

docs/core/entity/climate.md

Documents the `HVACMode` enum, replacing the `HVAC_MODE_*` constants.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/70286

Replace Climate HVAC_MODE_* constants with HVACMode enum

---

docs/core/entity/climate.md

Documents the new `HVACAction` enum for the climate platform.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/70319

Replace Climate CURRENT_HVAC_* constants with HVACAction enum

---

docs/api/rest.md

Clarification of /api/intent/handle docs
I figured the endpoint is /api/intent/handle and not /api/intent/handling. Also, I had to add `intent:` to my `configuration.yaml` to enable it, otherwise it returned 404s and documented that.
- This PR fixes or closes issue: --
- Link to relevant existing code or pull request: --

Correct /api/intent/handle endpoint route, add `intent:` hint

---

docs/api/native-app-integration/sending-data.md

I've added some documentation for when issuing an encrypted webhook request for a `type` that normally has no `data` key. Most actions *do* contain data, however there are [a couple](https://developers.home-assistant.io/docs/api/native-app-integration/sending-data#get-zones), like `get_zones` and `get_config` that are sent with no data when unencrypted. This documentation does not explicitly state what to do in this scenario, though it does hint at it.
The raised exception when no payload is sent also interferes with upgrading encryption from legacy (the `ATTR_NO_LEGACY_ENCRYPTION` flag).
Things I tried:
* Send no `encrypted` key nor `encrypted_data`: Home Assistant refuses to accept unencrypted webhook.
* Send `encrypted=True`, but no `encrypted_data`: Home Assistant schema requires …

Clarify when an encrypted request has no data

---

docs/api/supervisor/endpoints.md

Document new option in the API to disable use of fallback DNS.
Supervisor parent PR https://github.com/home-assistant/supervisor/pull/3586
- Link to relevant existing code or pull request: https://github.com/home-assistant/supervisor/pull/3586

Document disable fallback DNS option in API

---

blog/2022-05-12-s6-overlay-base-images.md
docs/add-ons/configuration.md

`host_pid` option does not work in s6 v3. Mention this in blog post.

`host_pid` does not work in s6 v3

---

blog/2022-05-24-entity_matches_only_removed_logbook_card.md

Document removal of entity_matches_only from logbook api
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/71657

Document removal of entity_matches_only from logbook api

---

blog/2022-07-08-config_entry_forwards.md

Wait for config entry platform forwards to ensure entries are never reloaded before they are finished setting up platforms and entities.
The following integrations have not been updated as they require more complex refactoring and/or test updates and may still suffer from reload races after this PR (each one will probably need its own PR).  They need to be refactored to replace calls to `hass.config_entries.async_setup_platforms` with `hass.config_entries.async_forward_entry_setups` and/or await all `hass.config_entries.async_forward_entry_setup`
- ambient_station
- axis
- deconz
- cast
- deconz
- esphome (race still present since it loads late)
- fjaraskupan
- heos
- homekit_controller
- homematicip_cloud
- islamic_prayer_times
- knx
- konnected
- mikrotik
- nest (legacy)
- openthrem_gw …

Add blog post about waiting for config entry platforms

---

docs/core/platform/significant_change.md

Fix missing HomeAssistant import.
Fix missing `:` in method signature.
Fix missing #pylint: disable=unused-arguement.
The provided code sample does not work.  I adjusted it to make it work. 

Fix missing

---

docs/network_discovery.md

Document async_track_unavailable in bluetooth
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/75582

Document async_track_unavailable in bluetooth

---

docs/creating_integration_manifest.md

As requested by @bdraco some info on how to convert a match for Bluetooth service data with a 16 bit uuid (0x16) to a 128 bit uuid.

Add info about 16 bit uuid conversion for Bluetooth service data

---

blog/2022-07-29-device-tracker_source-type-deprecation.md
docs/core/entity/device-tracker.md

Update `device_tracker` `source_type` properties to new `SourceType` enum.
https://github.com/home-assistant/core/pull/75892
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/75892

Update device_tracker source_type properties

---

docs/asyncio_working_with_async.md
docs/dev_101_config.md
docs/dev_101_events.md
docs/dev_101_hass.md

change links in developer documentation from pointing to the master
branch to point to the dev branch. The master branch online docs are
missing much information.
Changes all references to documentation hosted on the master branch to instead point to the dev branch.
The online docs at https://developers.home-assistant.io/docs/development_index/ have links pointing to API documentation hosted on the master branch, which shows an API reference with either no information or limited information.  
This can be verified by visiting [accessing the core introduction](https://developers.home-assistant.io/docs/dev_101_hass) and then clicking on the API reference documentation for any of the "see available methods" links in the `hass` object table near the top of the page.  
All existing links were …

change doc links master -> dev

---

blog/2022-08-15-automation-action-type-deprecation.md
docs/device_automation_trigger.md

Blog post for changes to `AutomationActionType`, `AutomationTriggerInfo`, and `AutomationTriggerData`.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/76790

Blog post for AutomationActionType deprecation

---

docs/development_testing.md

As I understand correctly the pytest command does not support anymore the option --asyncio-mode=strict.
So I suggest to remove it in the documentation.
Also if I run the command with the option I get an error:
```
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --asyncio-mode=strict
inifile: /workspaces/core/pyproject.toml
rootdir: /workspaces/core
```

Fix the pytest command on testing page

---

docs/creating_integration_manifest.md
docs/network_discovery.md

Fix incorrect match examples for bluetooth.
These matchers do not take lists, they take a single value
https://github.com/home-assistant/core/blob/0881ff2d1fe4034b33821775fa236589d8836912/homeassistant/loader.py#L90

Fix incorrect match examples for bluetooth

---

docs/core/entity/device-tracker.md

The current device_tracker entity documentation lists longitude and latitude Type as `string`. However, these properties are of `float` type. Returning these properties as strings results in a TypeError when developers don't define the location_name property.
- Link to relevant existing code or pull request: [Relevant code](https://github.com/home-assistant/core/blob/be34fdc3447c75dc637a0aa5678122a80ae2e674/homeassistant/components/device_tracker/config_entry.py#L232-L240)

Set device_tracker latitude/longitude Type as float

---

docs/bluetooth.md

- Adds missing `async_last_service_info` API
- `async_address_present` is no longer expensive to call
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/80349

Update bluetooth documentation for bleak 0.19 changes

---

src/pages/index.js

Currently, the calendar embed are set to use `America/Los_Angeles` as the timezone (with no note about it)
This PR changes that to use UTC and adds a note at the bottom of the embed about it.

Use UTC as TZ and show TZ note for calendar embed

---

docs/documenting/yaml-style-guide.md

Where the keep operator is mentioned, it wrongly shows the folded strip operator instead of the folded keep operator.
Correct the folded keep operator.

Fix folded keep operator in yaml-style-guide.md

---

docs/core/entity/number.md
docs/core/entity/sensor.md

Add mV as a new unit for voltage.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/84805

Add mV unit to number and sensor entity documentation

---

docs/core/entity/calendar.md

Update timezone requirements for calendar events to be more flexible with respect to timezones. Previously the wording said it required UTC, which actually isn't true nor ideal.
A calendar event start datetime may be represented as UTC, in a particular timezone, or without a timezone and interpreted as floating -- and all of these are valid and useful.
Examples scenarios of where floating vs non-floating is useful:
- With local calendar, you can specify floating dates without a timezone. If you have a home routine schedule (e.g. dim lights at 9pm) then you move to another timezone, you don't need to adjust anything beside the system timezone.
- With cloud calendars, you may care about the specific timezone of the event if its somewhere else.
When putting events on a timeline (e.g. …

Update timezone requirements for calendar events

---

docs/bluetooth.md
docs/config_entries_config_flow_handler.md

- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/83733

Add async_scanner_devices_by_address to Bluetooth

---

blog/2023-02-09-hassgetstate.md

Blog post about new `HassGetState` intent for queries in Assist.

Blog post about HassGetState intent

---

blog/2023-02-21-deprecated-callback-removed.md

https://github.com/home-assistant/core/pull/88543 removes some deprecated callback signatures, The blog article explains this.

Deprecated callback removed for MQTT subscribe

---

blog/2023-02-03-responses.md

There was a small typo in the blogpost describing whitespace changes for intent templates.
The example shows the before and after matching "light" and "light" when I believe it should be "lights" and "light s"

Fix typo in blog post on intent whitespace

---

blog/2023-03-28-calendar_best_practices.md
docs/core/entity/calendar.md

Add additional details about the responsibilities of a calendar entity with respect to timezone handling, all day events, and event ordering.
Related: https://github.com/home-assistant/architecture/discussions/853
- This PR fixes or closes issue:
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/90386

Add blog post and updated documentation for Calendar Entity timezone handling

---

blog/2023-03-28-calendar_best_practices.md

Current link to the Calendar entity documentation is wrong and leads to 404 page.
This change fixes the link.

Fix link to Calendar entity documentation page in blog

---

docs/core/entity/date.md

Adds documentation for the new date entity
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/81948

Add `date` entity developer docs

---

blog/2023-06-14-service-calls.md

Add a developer blog post for upcoming service API changes that remove the limit from service calls and change the return value.
We can either merge this incrementally, or add more as we change the API more (including service response data).
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/94657

Add a developer blog post for upcoming service API changes

---

docs/core/entity/humidifier.md

Add `current_humidity` attribute to `humidifier` entity
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/94874

Add current_humidity attribute to humidifier entity

---

docs/core/entity/weather.md

Add Apparent temperature to Weather
As per decision in https://github.com/home-assistant/architecture/discussions/785
Core PR: https://github.com/home-assistant/core/pull/95070
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/95070

Add Apparent temperature to Weather

---

docs/core/entity/weather.md

Adds `wind_gust_speed` as attribute and forecast attribute to Weather component
Core PR: https://github.com/home-assistant/core/pull/95065
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/95065

Weather add wind gust speed to Weather entity component

---

docs/api/supervisor/endpoints.md

Updates the supervisor add-on API documentation to include the "default_backup_mount" key returned by the /mount endpoint.
I found that the endpoint returns this additional key which AFAICT isn't provided anywhere else.  I'm assuming its just an oversight and not intended to be undocumented.
Document what values to expect from the /mount endpoint.

Document default_backup_mount in the /mount endpoint

---

docs/core/entity/vacuum.md

Remove unimplemented `error` property from `vacuum` documentation
According to the documentation, there's an `error` property which must be set when the vacuum is in state `error. It's however not implemented by the `vacuum` entity integration and there's no special support for it in frontend.
Out of the 6 core integrations which support the `error` state, 3 integrations (`ecovacs`, `sharkiq`, `xiaomi_mioo`) set an `error` state attribute themselves by implementing an `extra_state_attributes` method.
An alternative to this PR would be to add the `error` property to the `vacuum` base class.

Remove unimplemented error property from vacuum documentation

---

blog/2023-07-10-translating-services.md
blog/2023-07-11-translating-services.md
docs/dev_101_services.md
docs/internationalization/core.md

Documentation for https://github.com/home-assistant/core/pull/95984
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/95984

Add developer documentation about translations for services

---

docs/development_environment.mdx

Assuming this was meant to reference "production" and not "productive"
none

Fix spelling mistake in development_environment.mdx

---

docs/add-ons/tutorial.md

Fix an old value for `startup` option that is deprecated in one example of the Add-On tutorial.
The example is deprecated and gives this supervisor warning:
`Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of Hello world`

Update a deprecated value for "startup" option for Add-On

---

blog/2023-08-29-hass-format-state.md
docs/frontend/data.md

Adds entity state formatting documentation. A blog article has also been added to explain the new feature for custom card developers.
- Link to relevant existing code or pull request: https://github.com/home-assistant/frontend/pull/17249

Add entity state formatting documentation and blog article

---

blog/2023-09-14-entity_cached_property.md

Add blog post about use of cached_property in Entity
Note `translation_key` is not documented since there was no core usage outside of `entity.py` and it would likely be noise given how new it is.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/95315

Add blog post about use of cached_property in Entity

---

docs/core/entity.md

Reverts home-assistant/developers.home-assistant#1908
Parent PR has been reverted: https://github.com/home-assistant/core/pull/100422

Revert "Document how entity properties are consumed"

---

docs/api/rest.md

The curl command samples for the history end point were missing required parameters (`filter_entity_id`).
none

Fix curl samples for history end point in REST API documentation

---

docs/api/supervisor/endpoints.md
docs/api/supervisor/models.md

Document new API options added in https://github.com/home-assistant/supervisor/pull/4591
- Link to relevant existing code or pull request: https://github.com/home-assistant/supervisor/pull/4591

Document API options for excluding DB from backups

---

docs/development_environment.mdx

If make not installed, the setup will fail with:
error: [Errno 2] No such file or directory: 'gmake'
Include this in `brew install`
Discovered while setting up dev env on MacOS

fix: add make to macos brew install

---

docs/core/entity/climate.md

Reverts home-assistant/developers.home-assistant#2001
It seems the setting was there afterfall. Probably had a blind spot.

Revert "Document `target_temperature_step` for climate"

---

docs/creating_integration_manifest.md

https://github.com/home-assistant/core/pull/107411 adds a better algorithm for the matchers that does not regress the performance.
The no wildcards in the first 3 characters still applies
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/107411

Remove restriction on bluetooth local name matcher length

---

docs/development_environment.mdx

Updating libavresample-dev to libswresample-dev as per
https://github.com/home-assistant/developers.home-assistant/issues/1353
Replace broken dependency when setting up development environment
- This PR fixes or closes issue: fixes #1353

Update development_environment.mdx to fix broken dependency #1353

---

docs/core/entity/device-tracker.md

- The device tracker latitude and longitude have been made optional.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/108838

Make device tracker latitude and longitude optional

---

docs/add-ons/tutorial.md

Updated text for ["I don't see my add-on?!" section of addon tutorial](https://developers.home-assistant.io/docs/add-ons/tutorial#i-dont-see-my-add-on) to include refreshing browser cache as a first troubleshooting step.
The problem is also discussed on the [forum](https://community.home-assistant.io/t/local-add-on-not-showing-up-in-addon-store/352406/4).
- This PR fixes or closes issue: none
- Link to relevant existing code or pull request: none

Added note about refreshing browser cache when local addon does not show up in store

---

docs/bluetooth.md

Missing the `.md` suffix to link correctly to manifest docs.
This fixes the link to the manifest file instead of trying to go to `docs/bluetooth/creating_integration_manifest#dependencies` it now goes to correctly to `docs/creating_integration_manifest#dependencies`

Fix link to manifest.json in bluetooth docs.

---

docs/config_entries_config_flow_handler.md

Update the config flow reauth example to make use of the update, reload and abort helper. This also fixes a small error in the `if` statement.

Use update, reload and abort helper in reauth documentation

---

blog/2024-02-11-single-instance-only-manifest-option.md
blog/2024-02-26-single-instance-only-manifest-option.md
docs/creating_integration_manifest.md

Add the `single_config_entry` manifest option, so signal that only one config entry is supported (https://github.com/home-assistant/core/pull/109505)
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/109505

Add new `single_config_entry` manifest option

---

docs/api/supervisor/endpoints.md
docs/api/supervisor/models.md

Document option to make a read only mount for share or media usage added in https://github.com/home-assistant/supervisor/pull/4872
- Link to relevant existing code or pull request: https://github.com/home-assistant/supervisor/pull/4872

Document read_only option for mounts

---

docs/dev_101_events.md

Fix broken link to event helpers on “Listening for events” page
https://github.com/home-assistant/developers.home-assistant/blob/7e76189ae8966218da7a34b224add39ef8f42e34/docs/dev_101_events.md?plain=1#L60
Unsure if I've selected the correct type of change as the template doesn't have an obvious choice for fixing broken links.  Please consider adding.

Fix broken link

---

blog/2024-02-27-deprecate-bind-hass-and-hass-components.md
docs/auth_permissions.md
docs/frontend/extending/websocket-api.md

Add a dev blog about deprecating the `@bind_hass` decorator and the use of `hass.components`.
Also fix some code examples that use `hass.components`.
Logging PR in core: https://github.com/home-assistant/core/pull/111508
Related https://github.com/home-assistant/core/pull/111522 https://github.com/home-assistant/core/pull/111494

Add dev blog about deprecating `@bind_hass` and `hass.components`

---

blog/2024-03-10-climate-aux-heater-deprecated.md
docs/core/entity/climate.md

Start deprecation of `ClimateEntity` aux heater property and methods as outlined in https://github.com/home-assistant/architecture/discussions/932
Core PR: https://github.com/home-assistant/core/pull/112532

Deprecate aux heater in Climate Entity

---

docs/core/entity/climate.md
docs/core/entity/humidifier.md

Change `humidity` property types for `climate` and `humidifier` from `int` to `float`.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/111297

Update humidity property types to float

---

blog/2024-04-13-deprecate_async_track_state_change.md

Add blog post about deprecating async_track_state_change
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/115558

Add blog post about deprecating async_track_state_change

---

docs/api/supervisor/endpoints.md

Document the new Accept header option. This was added in https://github.com/home-assistant/supervisor/pull/4963 and available since Supervisor 2024.03.1.
- Link to relevant existing code or pull request: https://github.com/home-assistant/supervisor/pull/4963

Document "Accept: text/x-log" in Supervisor host logs API

---

docs/operating-system/debugging.md

Correct and tweak the instructions on SSH access to HAOS. 
Before, the instructions said to use an "ANSI encoded" `authorized_keys` file. But there is no such thing as "ANSI character encoding". [Windows-1252](https://en.wikipedia.org/wiki/Windows-1252) is commonly mislabeled as "ANSI", but I don't think this is what was meant. Thus I figured it can only be [ASCII](https://en.wikipedia.org/wiki/ASCII). Please correct me if I'm wrong!
(Note that as long as you're using only characters from the ASCII set, ASCII, Windows-1252 and UTF-8 are exactly the same.)

Tweak SSH access instructions

---

blog/2024-04-30-store-runtime-data-inside-config-entry.md

Blog post for `entry.runtime_data` implemented in https://github.com/home-assistant/core/pull/115669.
/CC @frenck

Add blog post for entry.runtime_data

---

docs/asyncio_thread_safety.md
sidebars.js

Add asyncio thread safety docs.
Since introducing the thread safety checks in 2024.5, I've been watching for matching GitHub issues. Some changes to custom components refer to these checks as "undocumented breaking changes" in Home Assistant. These comments show that developers need help understanding `asyncio` concepts and thread safety. If they do not realize they have been using the wrong APIs or doing unsafe thread operations and think the check is a breaking change, they may likely create new non-thread-safe operations.
I've also seen some custom components bypass the checks by switching to `asyncio.ensure_future` or calling `loop.create_task` directly, which sadly makes the problem worse because the unsafe operation is now harder to find, and users end up reporting crashes that are …

Add asyncio thread safety docs

---

docs/documenting.md

Ruby 2.7 doesn't work anymore
> `bundler (= 2.5.3)` required by `user-specified dependency`
Ruby 3.3 also doesn't work
```sh
bundle exec rake generate
NoMethodError on line ["89"] of /opt/homebrew/lib/ruby/gems/3.3.0/gems/compass-1.0.3/lib/compass/configuration/helpers.rb: undefined method `exists?' for class File
```
Current Ruby version is 3.1.4 https://github.com/home-assistant/home-assistant.io/blob/current/.ruby-version

Update required ruby version for documentation

---

blog/2024-05-19-fix_zoneinfo_blocking_io.md

Handling time zones without blocking the event loop blog post
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/117721

Handling time zones without blocking the event loop blog post

---

blog/2024-04-30-store-runtime-data-inside-config-entry.md

Update old blog post to use PEP 695 type alias for `ConfigEntry`. This also avoids the confusion around the quotes inside the annotation.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/117632

Use PEP 695 type alias for ConfigEntry

---

blog/2023-07-27-avoiding-unnecessary-callbacks-with-dataupdatecoordinator.md
docs/integration_fetching_data.md

The `DataUpdateCoordinator` can now reduce unnecessary updates when API data can be compared.
When using the `DataUpdateCoordinator`, the data being polled is often expected to stay mostly the same. For example, if you are polling a light that is only turned on once a week, that data may be the same nearly all the time. The default behavior is always calling back listeners when the data is updated, even if it does not change. If the data returned from the API can be compared for changes with the Python `__eq__` method, set `always_update=False` when creating the `DataUpdateCoordinator` to avoid unnecessary callbacks and writes to the state machine.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/97268

The `DataUpdateCoordinator` can now reduce unnecessary updates when API data can be compared
