home-assistant/developers.home-assistant

docs/config_entries_index.md

This is a set of rewordings that I found clearer (for me -- maybe not for everyone!). Please feel free to copy/paste / use parts of this PR in your own branch without merging it directly.
I added URLs to examples in the 0.68.0 release. However, I think that long-term, it would be nice to have a "minimal" example Config Entry that shows best practices. Maybe this should be a whole minimal component showing current best-practices that people can use as a skeleton for developing their own.

suggestions for config entries

---

docs/development_environment.md

Change few lines regarding Amazon Linux (CentOS base)

Update setup dev env document

---

docs/external_api_websocket.md

Add docs for the camera websocket command.

Add camera websocket command

---

docs/external_api_websocket.md

Docs for fetching media player thumbnails via the websocket connection.

Add media player websocket command

---

docs/creating_component_deps_and_reqs.md

https://github.com/home-assistant/home-assistant.github.io/pull/5199

Add content from #5199

---

docs/entity_alarm_control_panel.md
website/sidebars.json

https://github.com/home-assistant/home-assistant/pull/14686

Add stub for ACP entity, includes code_format

---

docs/frontend_add_card.md
docs/frontend_add_more_info.md

I am fresh new for HA frontend part, I found that current page seems outdated a little bit. I am trying my best to understand and try to fix the doc.

Fix frontend add card / more info page

---

docs/creating_platform_example_light.md

* Nothing is checking the return value of `setup_platform`.
fixes #21

Fix return value of platform light example

---

docs/creating_platform_code_review.md

* I write this so often in code review, that my mobile keyboard app knows my standard phrase for it.

Add point about hass in entity checklist

---

docs/development_typing.md
website/i18n/en.json
website/sidebars.json

I'm not sure where we want this page. I added it under "Developing a feature" in backend section for now. I'm happy to move it.
Addresses https://github.com/home-assistant/home-assistant/pull/14440#issuecomment-395566168.

Add page on typing

---

README.md
script/setup

* Addresses https://github.com/home-assistant/developers.home-assistant/pull/29#issuecomment-397873301.
* I copied the script from home assistant main repo.

Add setup script

---

docs/lovelace_card_types.md

Love UI: Add entity_id filter

---

docs/lovelace_card_types.md
docs/lovelace_custom_card.md
docs/lovelace_index.md

Lovelace next (>0.72.1)

---

README.md

Minor change to make `script/setup` better visible.

Make needed command better visible

---

docs/development_guidelines.md

Corresponding PR: https://github.com/home-assistant/home-assistant/pull/15278

Add isort section

---

docs/entity_vacuum.md

As we discussed in https://github.com/home-assistant/architecture/issues/29 I have added documentation for the vacuum component.
Feedback is welcome!

Added entity_vacuum

---

docs/internationalization_index.md

Update internationalization_index.md (corrected typo)

---

docs/development_environment.md

Added sudo to the apt commands to make it easier and match other apt commands.

Updated windows instructions

---

docs/hassio_addon_config.md

is allowed now: https://github.com/home-assistant/hassio/pull/608

other docker registries in  hassio_addon_config

---

docs/hassio_debugging.md

Changed log example commands to be relevant to HassOS

Change commands for HassOS

---

docs/documentation_create_page.md

Remove `{% raw %}` and `{% endraw %}`
**Fixes:** #62

Remove {% raw %} and {% endraw %} (fixes #62)

---

docs/data_entry_flow_index.md

With home-assistant/home-assistant#16100

Allow finish flow callback change result type

---

docs/auth_api.md

Add documentation for revoking refresh tokens: https://github.com/home-assistant/home-assistant/pull/16095

Update auth API

---

docs/development_guidelines.md

Per https://github.com/home-assistant/home-assistant/pull/16498#discussion_r217877385

Encourage new style string formatting

---

docs/creating_component_code_review.md
docs/creating_platform_code_review.md

**Related issue (if applicable):** fixes https://github.com/home-assistant/architecture/issues/84

Add additional section

---

docs/entity_sensor.md

See https://github.com/home-assistant/architecture/issues/24

Add pressure sensor device class

---

docs/integration_quality_scale_index.md

Fixes https://github.com/home-assistant/architecture/issues/82

Add internal to IQS

---

docs/hassio_debugging.md

Add missing header for generating keys

---

docs/development_environment.md

While this was documented elsewhere in the docs, this is the first thing I was looking for after invoking the dev environment and spent an inordinate amount of time tracking it down.

Config folder location clarification

---

docs/entity_water_heater.md
website/i18n/en.json
website/sidebars.json

Doc for https://github.com/home-assistant/home-assistant/pull/17058

Added water heater doc.

---

docs/development_index.md

With a reference to the Debian stable docs.

Made the minimum Python version explicit

---

docs/auth_api.md

Docs for https://github.com/home-assistant/home-assistant/pull/17759

Add docs for signed path

---

docs/creating_component_generic_discovery.md

One of my custom_components got burned by the changes in home-assistant/home-assistant#17952, so fix for the discovery docs...

Update load_platform docs

---

docs/creating_component_deps_and_reqs.md

took me a while to realize toplevel imports was the reason of all my fails writing a custom component.

add notice about putting imports inside functions

---

docs/creating_component_code_review.md

This gives us official documentation of this preference. I believe until now we've only been asking for this after-the-fact.

Document our preference for smaller component PRs

---

docs/entity_sensor.md

This adds the timestamp device class
Closes https://github.com/home-assistant/architecture/issues/39
UI support https://github.com/home-assistant/home-assistant-polymer/pull/2087

Add timestamp device class

---

docs/entity_air_pollutants.md

Additionally to https://github.com/home-assistant/home-assistant/pull/18707.

Add Air Pollutants Entity

---

docs/documentation_index.md

Had to install a few packages on a fresh ubuntu 18.04 and added them for others

Add needed dependencies

---

docs/frontend_add_card.md
docs/frontend_add_more_info.md

common/const is a typescript file, not js

Broken link in docs

---

docs/asyncio_categorizing_functions.md

Change reference from "yield from" to "await".

Fix change from "yield from" to "await"

---

docs/documentation_index.md

Minor spelling error

---

docs/lovelace_custom_card.md

Just had this issue myself so propose letting people know that Hass needs a re-start to find the www folder under the config folder.

A tip to get the /home/ folder to not 404

---

website/core/Footer.js

Makes it easier to contribute here as well... ;-)

Footer: Adds link to this GitHub repository

---

website/core/Footer.js

Reverts home-assistant/developers.home-assistant#184

Revert "Footer: Adds link to this GitHub repository"

---

docs/development_environment.md

Re: home-assistant/home-assistant#21700
I suggest to install venv in a separate folder

Create a separate venv folder should be better

---

docs/external_api_websocket.md

The ping and pong functionality is in commands.py but is not documented anywhere from what I can tell.

Document ping and pong functionality

---

docs/external_api_rest.md

More appropriate place in the docs for this PR https://github.com/home-assistant/home-assistant.io/pull/8780

Add Home Assistant RESTful command example

---

docs/auth_permissions.md

https://github.com/home-assistant/home-assistant/pull/21953

Update docs for admin service helper

---

docs/development_environment.md

This is based on an issue as seen here https://github.com/home-assistant/home-assistant/issues/22068.

Dev 0.91 needs some extra tox dependencies to run

---

docs/config_entries_index.md

Signed-off-by: Alan Tse <alandtse@gmail.com>

Fix typo in lifecycle

---

docs/integration_quality_scale_index.md

Closes https://github.com/home-assistant/architecture/issues/83

Require component for IQS silver level

---

docs/creating_platform_example_light.md
docs/creating_platform_example_sensor.md

Updates the two platform examples (custom components) to follow the new embedded structure after the great migration.

Embedded platforms

---

docs/creating_component_code_review.md

Updates the component code review page to mention the following:
- Limit initial PRs to MVP
- Write tests (encouraged)

Update component check list to describe MVP

---

docs/entity_sensor.md

add device_class_power to sensor
See home-assistant/architecture#140
**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#22691

add device_class_power to sensor

---

docs/entity_sensor.md

See home-assistant/architecture#165
**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant):** home-assistant/home-assistant#22738

Add signal_strength to device_class of sensor

---

docs/development_checklist.md

Related PRs: https://github.com/home-assistant/home-assistant/pull/22751 https://github.com/home-assistant/home-assistant/issues/22700

Add docs about The Manifest File

---

docs/app_integration_notifications.md
docs/app_integration_sending_data.md
docs/app_integration_sensors.md
docs/app_integration_setup.md
website/i18n/en.json
website/sidebars.json

Todo:
- Registration: encryption, recommended value formatting, discovering HA
- Notifications: how to configure in HA, what server needs to do
- Sensors: registration and updates

Mobile App Documentation Improvements

---

docs/hassio_addon_communication.md

http://hassio/homeassistant/stream does not exist in routing.

Fix stream api url

---

docs/development_submitting.md

Suggest to use the imperative mood in the subject line.

Commit message in imperative

---

docs/entity_climate.md

Add Climate documentation

---

docs/entity_fan.md

added fan doc

---

docs/creating_integration_manifest.md

I spent too long debugging why my requirements weren't loading, until I realized that the manifest is only from 0.92.0 on, while I was running 0.91.3.
Hope this saves someone else from searching for this.

Make versioning clearer

---

docs/entity_media_player.md

Add device classes to docs for media_player for: https://github.com/home-assistant/home-assistant/pull/23236

Add device classes to media player

---

website/blog/2019-04-12-new-integration-structure.md

looks like our great leader got a bit too "copy pasta" happy with the links and nested manifest.json inside the integrations link. <3

tweak to integrations link.

---

docs/entity_fan.md

There had been some spelling errors I hadn't noticed. My apologies.

Fixed Spelling errors on fan doc

---

docs/creating_integration_manifest.md

Fix typo in creating_integration_manifest.md

---

docs/entity_registry_index.md

Changed "integraion" to "integration"

[DOCS] Fix typo

---

docs/hassio_addon_security.md

Here are several changes to this file to make it more readable in English.

Make hassio_addon_security.md more readable

---

docs/entity_switch.md

Source issue: https://github.com/home-assistant/home-assistant/pull/23149

Add device classes to switch

---

docs/entity_media_player.md

Add media_type_app as a constant. PR #[23666](https://github.com/home-assistant/home-assistant/pull/23666)

Add media type app

---

docs/entity_index.md

Update the example for better understanding of that function

Clerify use case of `async_added_to_hass`

---

docs/hassio_addon_communication.md

Just cleaned up some of the language a bit. If any of the intended meaning is lost, feel free to reject.

Grammar and typo edits for clearer direction.

---

docs/frontend_creating_custom_panels.md
docs/frontend_creating_custom_ui.md
website/sidebars.json

Add deprecation notice to custom UI docs.

Deprecate custom UI

---

docs/creating_integration_manifest.md

Document SSDP and Zeroconf discovery.
CC @Kane610

Document discovery

---

website/pages/en/index.js
website/static/css/custom.css

Embed dev calendar.
placeholder, need a better place than this.

Embed dev calendar

---

docs/creating_integration_manifest.md

https://github.com/home-assistant/architecture/issues/248
https://github.com/home-assistant/home-assistant/pull/24225

Add HomeKit discovery docs

---

docs/entity_cover.md

Found a simple error and figured I'll fix it while I'm at it.

Fixed simple copy/paste error.

---

docs/config_entries_config_flow_handler.md
docs/creating_integration_manifest.md
docs/data_entry_flow_index.md

Update config entry docs:
- Document external step
- Document Discoverable config flow helper
- Properly document how to make integrations discoverable
- Document manifest `config_flow` key

Update config entry docs

---

docs/frontend_external_bus.md
website/i18n/en.json
website/pages/en/index.js
website/sidebars.json

This adds the missing documentation for the external bus.

Add external bus docs

---

website/blog/2019-07-03-climate-cleanup.md

Add blog post about climate cleanup.

Add blog post about climate cleanup

---

website/blog/2019-07-03-climate-cleanup.md

:pencil2: Tweaks climate cleanup blog post

---

docs/entity_climate.md

Update the climate docs for the new architecture

Update climate docs

---

docs/development_environment.md

This adds "Developing with devcontainer" to the backend "Set up Development Environment" section, to promote that setup as a viable option for developers.

Add notes about devcontainer

---

docs/development_guidelines.md

This incorporates Black and some common sense :)

Update code formatting advice

---

docs/entity_index.md

Document https://github.com/home-assistant/home-assistant/pull/26011

Document entity disabled property

---

docs/hassio_addon_tutorial.md

The link to the mosquitto add-on no longer worked, this PR solves that.

🔨 Fix url link

---

docs/config_entries_config_flow_handler.md

For https://github.com/home-assistant/home-assistant/pull/26059

Document init subclass

---

docs/entity_registry_disabled_by.md
website/i18n/en.json
website/sidebars.json

Add some docs how to work with disabled_by.

Add disabled_by docs

---

docs/lovelace_custom_card.md

As a new developer to HA & Custom Cards, I would have found these resources VERY helpful.

Added Recommended Design Elements & Resources Section to Lovelace Custom Card Docs

---

docs/creating_component_index.md
website/i18n/en.json

https://github.com/home-assistant/home-assistant/pull/26777

Add scaffold intro

---

docs/creating_platform_code_review.md

Headline numbers were in wrong order

Fix headline numbering for platform creation doc

---

docs/app_integration_setup.md

https://github.com/home-assistant/home-assistant/pull/30460

Document mobile app device_id

---

docs/frontend_external_auth.md

https://github.com/home-assistant/home-assistant-polymer/pull/4461

Document 'force' in external_auth

---

docs/config_entries_config_flow_handler.md

Document the new features in 104.

Add unique ID config flow docs

---

docs/frontend_data.md

it's good to know that's available

is_admin added to the hass.user example

---

website/blog/2019-10-05-simple-mode.md
website/blog/2020-02-04-new-zwave.md
website/i18n/en.json

Add Z-Wave MQTT blog post

---

docs/integration_fetching_data.md
website/i18n/en.json
website/sidebars.json

Adds an introduction about fetching data for integrations.

Add fetching data intro

---

docs/dev_101_services.md
website/i18n/en.json

Document the new recommended way of doing platform services.

Document platform services

---

docs/integration_fetching_data.md

- Missing import `datetime`
- Unused import `debounce`
- The `DataUpdateCoordinator` doesn't have a `failed_last_update` property.

Fix Fetching Data example

---

docs/hassio_addon_communication.md
docs/hassio_addon_config.md
docs/hassio_addon_index.md
docs/hassio_addon_presentation.md
docs/hassio_addon_publishing.md
docs/hassio_addon_repository.md
docs/hassio_addon_security.md
docs/hassio_addon_testing.md
docs/hassio_addon_tutorial.md
docs/hassio_debugging.md

I know it is not perfect and not what we should have at the end, but it's a good start and makes sure that new developments need not rewrite the configs soon.

Small fixes for Hass.io/HA

---

docs/creating_integration_manifest.md

A missing part of https://github.com/home-assistant/home-assistant/pull/23148
Had to learn it hard way so think it needs to be improved.

add after_dependencies

---

docs/app_integration_sending_data.md
website/i18n/en.json

See also https://github.com/home-assistant/home-assistant/pull/31743

Add documentation about enable_encryption

---

blog/2020-02-18-106-custom-card-changes.md

In the move to DSv2 blog from #410 was not merged properly

Reinstate #410

---

src/pages/index.js
static/js/discourse_discussion.jsx

* Remove the scrollbar from the embedded discourse comments
* Also removing the commented out code from `src/pages/index.js`

Remove discourse scrollbar

---

docusaurus.config.js
netlify.toml

Site should have been re scrapped by now and redirects all seem to be working nicely. Closes #416

Re enable search 🔎

---

docusaurus.config.js

Add open graph image

---

docs/integration_fetching_data.md

PR: https://github.com/home-assistant/core/pull/32452

Mention update coordinator handles timeout/client error

---

docs/development_environment.md

Im not sure but i believe since the name change into core and the other homeassistant version the fork instruction is faulty. So i changed it and added a small little note, which might be a little overkill.

Updated the Fork instruction and shell command

---

docs/entity_cover.md

Gates are found outside of a structure and are typically part of a fence.
https://github.com/home-assistant/frontend/pull/5299
https://github.com/home-assistant/core/pull/33074

Add DEVICE_CLASS_GATE

---

docs/frontend_development.md

While trying to follow the instructions to setup a fevelopment environment for the frontend discovered some parts are not actual anymore

Update development instructions for frontend

---

docs/development_environment.md

This updates the setting up the dev env docs to promote dev containers.

Promote dev containers more in dev env docs

---

docs/entity_fan.md

- Limit allowed speed values to one of the constants SPEED_OFF, SPEED_LOW, SPEED_MEDIUM, SPEED_HIGH.
- Add methods.
- Clean up.

Update fan entity docs

---

docs/development_catching_up.md

Credits to CoMPaTech over on Discord for reporting this.

Fix repo link

---

docs/lovelace_custom_card.md

Fix add to card-picker example

---

docs/entity_media_player.md

This needs to be a property, not a function.

Fix documentation for media_content_type

---

blog/2020-04-23-frontend-translations.md
docs/internationalization_backend_localization.md
docs/internationalization_custom_component_localization.md
docs/internationalization_index.md

Update translations docs + add blog

---

docs/data_entry_flow_index.md

Docs for https://github.com/home-assistant/core/pull/34629

Document advanced mode for flows

---

docs/instance_url.md

Renamed async_get_url -> get_url as per parent PR: https://github.com/home-assistant/core/pull/35382

async_get_url -> get_url

---

docusaurus.config.js
src/pages/index.js
src/pages/styles.module.css

Formats file, small wording changes and extended footer.

Minor site config changes

---

docs/add-ons/configuration.md
docs/add-ons/presentation.md
docs/add-ons/publishing.md
docs/add-ons/tutorial.md

- Ensures all examples use Bashio
- Updates an older URL of the Home Assistant instance
- Fixes filename for add-on documentation
- Some Markdown & language fixes

Small updates to add-on documentation

---

docs/config_entries_config_flow_handler.md

Looks like the path to this link changed at some point.

Fix broken link

---

docs/documenting/standards.md

Change formatting for italics to match "ALL CAPITALS"

Include italics

---

docs/development_environment.md

To avoid confusions on different Python versions available for e.g. Ubuntu 18.04 and Ubuntu 20.04 all python3.x installation instructions are changed to python3.
- Link to relevant existing code or pull request: https://github.com/home-assistant/developers.home-assistant/pull/553

Change instructions mentioning python3.x to python3

---

docs/add-ons/presentation.md

Add apparmor skelleton

---

docs/entity_registry_index.md

Fixed typo

---

docs/development_environment.md

The current installation instructions for WSL instruct the user to install `Ubuntu` without specifying a specific version. When the user chose 18.04 some dependencies cannot be installed because the ffmpeg version is too old.
This adds additional instructions to upgrade ffmpeg for Ubuntu 18.04.
- This PR fixes or closes issue: fixes #552

Add instructions to update ffmpeg on Ubuntu 18.04

---

docs/core/entity/light.md

Fix typo; "minreds" should be "mireds".

Fix minreds typo

---

docs/add-ons/testing.md

update add-on testing to reflect available devcontainer options and include basic instructions for local builds via hassio-builder

update add-on testing

---

docs/frontend/custom-ui/lovelace-custom-card.md

Change docs for async `getCardSize`

Update getCardSize docs

---

blog/2020-06-01-getCardSize.md

Create blog about getCardSize.

Create blog about getCardSize

---

docs/entity_registry_index.md

Add extra detail regarding the unique_id property specifically, including a code example.
I read this page, but had no idea how to implement it, until someone on Discord explained it, so I'm adding this to make it clearer what to actually do in your code.
Thanks.

Add unique_id attribute detail

---

docs/frontend/extending/adding-state-card.md

Fixing broken link from .js to .ts

Fixing broken link

---

docs/add-ons.md

Rename to Supervisor from Hass.io.

Rename to Supervisor

---

docs/add-ons/tutorial.md

Rename to homeassistant

---

docs/operating-system/debugging.md

Updates the example given in debugging to reflect the default hostname. I use hostname as a term without explanation as anyone that doesn't understand the meaning shouldn't be using this doc (as stated at the top).

Update OS debug example hostname

---

docs/frontend/development.md

The previous upstream URL in the code example was invalid, having a duplicate directory in the path. This corrects that URL.

Fix upstream repo URL in code clone example

---

docs/operating-system/debugging.md

This line was left behind when the documentation splitted.
For debugging the OS, one of course does not need to be in dev mode or have the remote add-ons.
- This PR fixes or closes issue: fixes #568

Remove unrelated comment from supervisor debug

---

docs/config_entries_config_flow_handler.md

Parent PR: https://github.com/home-assistant/core/pull/36754
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/36754/files

Add documentation for discovery without unique ID

---

static/_redirects

To cover the `.html` form used by iOS app, will update app side too.

Additional translation redirect

---

docs/translations.md

Just correcting the text lead in to the list of Lokalise projects to reflect the correct number of projects (four).

Correct number of Lokalise projects

---

docs/api/native-app-integration/sending-data.md

Adds the request to retrieve streaming information about cameras.
- Link to relevant existing code or pull request: home-assistant/core#36839
https://github.com/home-assistant/core/blob/212660330f4fed8d35e263e52f56b2e291fd5c05/homeassistant/components/mobile_app/webhook.py#L245-L268

mobile_app: stream_camera information

---

docs/api/rest.md

Noticed this was out of date when fixing https://github.com/home-assistant/core/pull/36979

Update rest api for latest history and logbook changes

---

docs/entity_humidifier.md

Support for new humidifier entity.
home-assistant/home-assistant#28693

Add new humidifier entity integration

---

docs/development_submitting.md

and add link to main repo
Add more clarity and detail to commit message guidelines including use of imperative voice.
The previous version had a point about adding tests in the commit message details, so this is moved to the testing section.
Add a link to the main repo where it refers to it.

Update commit message details, move test reference

---

docs/api/websocket.md

Remove some legacy websocket API docs that are no longer supported.

Remove legacy API from websocket API docs

---

docs/frontend/data.md

Replace Hass.io

---

docs/add-ons/communication.md

Remove Hass.io

---

docs/add-ons/configuration.md

Various updates (typos, removal of Hass.io, style, etc.)

Update table content

---

docs/frontend/custom-ui/lovelace-custom-card.md

Simple typo in example code. Fixes so it runs again.
- This PR fixes or closes issue: fixes #NA
- Link to relevant existing code or pull request: NA

Fix error in code

---

docs/creating_platform_code_review.md

Remove redundant phrasing

---

docs/documenting/create-page.md

I discovered a small improvement, and followed the scout rule: leave any camping site just a little bit better compared to how you found it.
https://martinfowler.com/bliki/OpportunisticRefactoring.html:
"scout rule - always leave the code behind in a better state than you found it."

trivial fix

---

docs/creating_component_code_review.md

Fix minor typo

---

docs/config_entries_index.md

Per https://github.com/home-assistant/core/pull/37741#discussion_r455668639
As discussed in https://github.com/home-assistant/core/pull/37741#discussion_r455668639 this example needs an update

Switch example to create_task

---

blog/2020-07-13-alpine-python.md

Very minor typo corrections to recent blog post on improvements to python spped

Minor typo correction

---

docs/frontend/custom-ui/lovelace-custom-card.md

Remove recommended design elements
As it is really hard to get working in a custom card.

Remove recommended design elements

---

docs/development_submitting.md

Change 'component' to 'integration'

Change 'component' to 'integration'

---

docs/add-ons/configuration.md

Some of the options on the add-on configuration page have broken grammar.  This PR is my attempt to fix as many as I could find.
N/A

Grammar and clarity add-on fixes

---

docs/integration_fetching_data.md

Update DataUpdateCoordinator example to use CoordinatorEntity
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/39388

Update DataUpdateCoordinator example to use CoordinatorEntity

---

package.json
yarn.lock

Updates docusaurus to 2.0.0-alpha62

Docusaurus 2.0.0-alpha62 Update

---

docs/frontend/custom-ui/creating-custom-panels.md

Add custom panel example

---

docs/core/entity/weather.md

- Complete missing weather attribute information.

Complete weather attributes

---

docs/core/entity/remote.md

Improve remote documentation

---

docs/core/entity/media-player.md

Add mention of new receiver device class
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/38381

Add documentation of receiver device class

---

docs/instance_url.md

Add missing documentation for missing `require_current_request` option on the `get_url` helper.

Add current request context to get_url helper documentation

---

docs/documenting/create-page.md

Documents the `any` variable type, introduced in https://github.com/home-assistant/home-assistant.io/pull/14458

Document 'any' variable type for configuration documentation

---

docs/creating_integration_manifest.md

Document changes in https://github.com/home-assistant/core/pull/39877

Update zeroconf manifest with new specifiers

---

docs/creating_integration_manifest.md

Update info on available SSDP data.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/39984

Update info on available SSDP data

---

docs/add-ons/testing.md

Corrected Hass.io to Home Assistant

---

docs/add-ons/tutorial.md

`before` value in startup of example is not according to published documentation: https://developers.home-assistant.io/docs/add-ons/configuration.

Update startup in the example according to docs

---

docs/add-ons/publishing.md

Fix spelling/typo. I know it's a very small change. But I couldn't help myself.
- This PR fixes or closes issue: n/a
- Link to relevant existing code or pull request: n/a

Fix spelling in add-on publishing

---

docs/config_entries_config_flow_handler.md

Correct typos in config flow developer docs

---

docs/development_testing.md

- Add instructions for writing tests for integrations.

Add how to write tests for integrations

---

docs/integration_fetching_data.md

Update MyEntity example to invoke super().  Found this as I was implementing an entity following this example.
Fix syntax error in one of the examples, found while following along and implementing my own entity.

Fix syntax error in DataUpdateCoordinator example

---

docs/translations.md

Updates the Lokalise translation workflow documents on the translations page from https://docs.lokalise.co/category/iOzEuQPS53-for-team-leads-and-translators to https://docs.lokalise.com/en/collections/652216-translation-workflow
Thanks, @TomBrien for point out the correct URL.
- This PR fixes or closes issue: #661

Update translation workflow documents on translations page

---

docs/development_environment.md

Fixed a little typo in Setup Local Repository

Fix Typo in Setup Local Repository

---

docusaurus.config.js
src/css/custom.css
src/pages/index.js
src/pages/styles.module.css

Adds the Home Assistant logo (white variant) to the hero banner on the home page. Also does:
- Forces the text in `heroBanner` to always be white regardless of dark mode
- Tweaks the site tag line from "... Documentation" to ".. Docs" to keep tidy (and friendlier).
- Moves the `heroText` CSS class definition to be scoped locally to `src/pages` only

Add Home Assistant logo to home page banner

---

docs/documenting/standards.md

Change documentation from frontmatter redirects to redirects file to reflect the changes introduced in the PR's and issues listed below
- This PR fixes or closes issue: 
https://github.com/home-assistant/home-assistant.io/issues/14662
https://github.com/home-assistant/home-assistant.io/pull/14794

Change documentation from frontmatter redirects to redirects file

---

docs/config_entries_config_flow_handler.md
docs/creating_integration_manifest.md

Document MQTT integration discovery
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/41332

Document MQTT integration discovery

---

docs/api/supervisor/endpoints.md
docs/api/supervisor/examples.md
docs/api/supervisor/models.md
docusaurus.config.js
sidebars.js
src/css/custom.css

Move https://github.com/home-assistant/supervisor/blob/dev/API.md to dev docs.
Preview: https://deploy-preview-666--developers-home-assistant.netlify.app/docs/api/supervisor/endpoints

Move Supervisor API

---

docs/internationalization.md

Updated repository links

---

docs/core/entity/sensor.md

I want to add 4 new device_classs, to handle the electrical measurement
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/36800

Add device classes for electrical measurement

---

docs/api/supervisor/endpoints.md

https://github.com/home-assistant/supervisor/pull/2113

Update snapshot API for remove

---

docs/api/native-app-integration/sending-data.md
docs/api/supervisor/endpoints.md
docs/api/supervisor/models.md
docs/auth_api.md
docs/dev_101_hass.md
docs/integration_fetching_data.md
docs/translations.md

There were some typos that are fixed now

Fix some typos

---

docs/api/supervisor/endpoints.md

Adds documentation for https://github.com/home-assistant/supervisor/pull/2124
- Link to relevant existing code or pull request: https://github.com/home-assistant/supervisor/pull/2124

Add /resolution endpoint

---

docs/api/supervisor/endpoints.md

Add suggestion endpoints for /resolution
- Link to relevant existing code or pull request: https://github.com/home-assistant/supervisor/pull/2125

Add suggestion endpoints for resolution

---

docs/api/native-app-integration/sending-data.md
docs/api/rest.md
docs/creating_component_code_review.md
docs/dev_101_events.md

Was adding events to the android app and did not know there was a character limit for the `event_type` as we only mention this in the Data docs lets make sure to mention it when developers are looking up what is expected.  
- Link to relevant existing code or pull request: https://github.com/home-assistant/android/pull/1041

Mention event data structure when we talk about firing events

---

docs/config_entries_config_flow_handler.md

Add description on how to migrate Config Entries as this was not documented anywhere.
I needed to handle migration from an old to a new version of my Config Entry. I did not find any documentation for it, but found some examples in HA components. Decided I'll make it easier for others in the future and documented it briefly.

Added description on how to migrate a Config Entry to a new version

---

docs/api/supervisor/endpoints.md
docs/api/supervisor/models.md

Fix API for new resolution center

---

docs/api/supervisor/endpoints.md

Add resolution as info

---

docs/api/rest.md

Up date rest api docs to reflect the supervisor api docs

Update Rest API Style

---

docs/api/rest.md

Add some missing `>` to the Rest API headers

Fix some Rest API headers

---

docs/api/rest.md

Fix right carrots

---

docs/api/supervisor/endpoints.md

Show internal network settings on info

---

docs/api/supervisor/endpoints.md

Supervisor: Auth cache reset

---

docs/api/rest.md
docs/api/supervisor/endpoints.md
src/css/custom.css
static/js/api_endpoint.jsx

Adds a new `ApiEndpoint` element to replace the current  `details` hack that is used for API endpoint definitions.
- Changes the color for the method boxes.
- Replaces all instances of ` [...]` with  `<...>` for placeholders

Custom API endpoint element

---

docs/add-ons/communication.md
docs/add-ons/security.md

Update supervisor links

---

docs/creating_platform_code_review.md

Prevent code block from braking up and second part being slightly de-indented.
Fixes brake-up of code block

Prevent code block brake up

---

docs/add-ons/configuration.md

Fix typo: Allow read-oly access -> Allow read-only access

Fix typo in add-on configuration

---

docs/frontend/custom-ui/lovelace-custom-view.md
sidebars.js

Docs: New File for Custom Views

---

docs/add-ons/testing.md

Improve docs for local add-on development using dev container in VS Code.
Added special note regarding WSL 2 not working.
Brought this up in discord and pvizili confirmed what I'm writing here, that the boostrap script is currently not working with WSL 2.

Improve Add-On testing steps

---

docs/device_registry_index.md

The exact device registry behaviour is somewhat unclear. Clarify how devices are matched exactly.

Clarify how devices are matched in device registry

---

docs/development_testing.md

Add line of code to check code coverage for a component

Add codecov command to dev instructions

---

docs/api/supervisor/endpoints.md

Document `ingress/validate_session` API of https://github.com/home-assistant/supervisor/pull/2223

Add a validate ingress session endpoint

---

docs/frontend/development.md

Corrects typo "rebuilt"

---

docs/api/supervisor/endpoints.md

Adds documentation for https://github.com/home-assistant/supervisor/pull/2218

Dockerhub registry

---

docs/data_entry_flow_index.md

- Add docs for new data entry flow helper show progress.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/42419

Document data entry flow show progress

---

blog/2020-11-09-system-health-and-templates.md

Add blog post about template and streaming

---

docs/device_automation_action.md
docs/device_automation_condition.md
docs/device_automation_trigger.md
docs/device_registry_index.md
docs/integration_events.md
sidebars.js

Document integrations firing events.

Document firing events

---

docs/api/supervisor/endpoints.md
docs/api/supervisor/models.md

New network API doc

---

docs/api/supervisor/endpoints.md
docs/api/supervisor/models.md

- Link to relevant existing code or pull request: https://github.com/home-assistant/supervisor/pull/2241

Use technology neutral "auto" instead of "dhcp" for IP configuration

---

docs/api/supervisor/endpoints.md

Adds documentation for 2 new keys in the `/network/info` endpoint response
- Link to relevant existing code or pull request:  https://github.com/home-assistant/supervisor/pull/2225

Add new keys to /network/info

---

docs/api/supervisor/endpoints.md

Add unhealthy flag for resolution center

---

docs/data_entry_flow_index.md

- Make a more complete show progress flow example and add more important details to the text.

Improve data entry flow show progress docs

---

docs/creating_integration_manifest.md

Update wording in developer docs to clarify 'after_dependencies'
The update is partly based on Frenck's comment here:
https://github.com/home-assistant/core/pull/43329#issuecomment-731554583
- This PR fixes or closes issue: fixes #729

Clarify description of 'after_dependencies'

---

docs/api/supervisor/endpoints.md

Supervisor restart

---

docs/development_catching_up.md

Using the safer `--force-with-lease` is usually recommended to avoid loosing work done from other workspaces or by other contributors: 
See https://blog.developer.atlassian.com/force-with-lease/
and https://thoughtbot.com/blog/git-push-force-with-lease
and https://stackoverflow.com/a/52823955/316805

Recommend safer "git push --force-with-lease"

---

docs/device_automation_trigger.md
docs/integration_events.md

Add additional documentation for firing events and triggers, based on what I have learned trying to implement them.  In particular, I tried to better connect the high level explanation for how triggers and events work to the actual code and steps needed to implement them, using a real example of triggers related to events on the bus.
Part of this request is to also confirm my understanding of how this works is correct as I am currently building triggers for `nest` integration.

Add additional trigger documentation

---

docs/device_automation_trigger.md

Add extra instructions for updating translations based on discussion in pull #733

Add device trigger translation documentation

---

docs/device_automation_trigger.md

Address additional feedback from #734

Update device automation translation steps

---

docs/api_lib_auth.md

Fix sync example

---

docs/api/supervisor/endpoints.md

Add API for network reload command

---

docs/entity_number.md

Add number entity value property
- Link to relevant existing code or pull request: home-assistant/core#43902

Add number entity value property

---

docs/add-ons/publishing.md

Updated wording to reflect behaviour for add-on config fetch location
n/a

Updated wording to reflect behaviour

---

docs/frontend/custom-ui/lovelace-custom-view.md

Update Docs to add Events that will Add, Delete or Edit a Lovelace Card via a custom view
- Link to relevant existing code or pull request: https://github.com/home-assistant/frontend/pull/7861

Add new Events to Custom View Docs

---

docs/api/native-app-integration/sending-data.md

Fixed typo: Date -> Data

---

docs/frontend/custom-ui/lovelace-custom-view.md

Very Small updated after using the Custom Views

---

docs/config_entries_config_flow_handler.md
docs/integration_quality_scale_index.md

Document an example of how to implement reauth for an OAuth2 example based on `script.scaffold` templates.  The motivation is to make it easier for developers to understand how to build an integration on the silver quality scale.
During development of https://github.com/home-assistant/core/pull/44202 for `nest` I had the following questions:
Questions that I had during development include:
- how do i pop up a notification to the user?
- how do i restart the integration after reauth completes?
- how do i reset a config flow during setup?
- how do i handle updating an existing config entry?
These are expected to be answered by this example.
- Example `script.scaffold` template for OAuth is here: …

Document an OAuth2 reauth example

---

docs/translations.md

Add french translation rule for Blueprint: decision to not translate this word to avoid confusion with *map* and *template* french translation. It will simplify blueprints search on Internet to import them.

French translation rules for Blueprint

---

docs/api/supervisor/endpoints.md

Small update on auth doc

---

docs/add-ons/presentation.md

Add some note about the Ingress added request header `X-Ingress-Path`. It might be interesting when your addon uses some reverse proxy that has issues with relative paths (e.g. Octoprint)
I did not find any mention about this when creating some reverse proxy. Even by googeling the correct header I found *4* results, only *1* lead me towards the right direction.

Add note about X-Ingress-Path

---

docs/core/entity/remote.md

We recently created a service to [delete commands](https://github.com/home-assistant/core/pull/40605). This PR adds documentation for developers.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/40605

Add documentation for the remote.delete_command service

---

docs/api/supervisor/endpoints.md

I added a method to the supervisor auth API described at https://github.com/home-assistant/supervisor/pull/2407. This PR updates the documentation accordingly.
- Link to relevant existing code or pull request:  https://github.com/home-assistant/supervisor/pull/2407

Document supervisor /auth GET method

---

docs/api/supervisor/endpoints.md

Fix the header name to have basic authentication
-  Commit introducing the error: https://github.com/home-assistant/developers.home-assistant/commit/b7495603df71726eea5f9cebc606a95d583930b4 
-  Code with the right header name: https://github.com/home-assistant/supervisor/blob/bff4af25349c8b3c3de45d993720cd2ab1b92208/supervisor/const.py#L59
- #760

Corrrection on auth doc

---

docs/core/entity/weather.md

Adding barometric pressure forecast per HA Architecture Issue:
https://github.com/home-assistant/architecture/issues/467
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/44965

Add pressure forecast to weather entity model

---

docs/add-ons/configuration.md

Small suggested change to add-on configurations; make the boot parameter optional and give it the default of auto.
It seems that most add-ons use this value, as manual is rare. Making it optional and setting the default to auto allows to clean up the add-on configurations a bit more.
- Link to relevant existing code or pull request: https://github.com/home-assistant/supervisor/pull/2418

Set a default for add-on boot config

---

docs/intent_builtin.md

Add intents for `humidifier` integration.
- Link to relevant existing code or pull request: home-assistant/core#37335

Add humidifier intents

---

docs/config_entries_config_flow_handler.md
docs/creating_integration_manifest.md

Document DHCP discovery
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/45087

Document DHCP discovery

---

docs/core/entity/device-tracker.md
sidebars.js

- Add a page for device tracker entities.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/blob/852136ccfe6012434e8302cc1b98ab5b31b6aa25/homeassistant/components/device_tracker/config_entry.py#L82-L164

Add device tracker entity page

---

docs/creating_integration_manifest.md

Add documentation for the version key in the manifest for custom integrations.
- Link to relevant existing code or pull request:  https://github.com/home-assistant/core/pull/45523

Add version to the manifest

---

docs/documenting.md

ruby3 not supported. instructions for mac

---

docs/integration_quality_scale_index.md

httpx is a new async web client that has also been adopted within Home Assistant. Both are now allowed to be used to reach platinum.

Allow httpx for platinum quality scale

---

docs/reproduce_state_index.md
docs/significant_change_index.md
sidebars.js

Add docs for significant changes

---

docs/core/entity/fan.md

Update entity model for the switch from named speeds to percentages
- This PR fixes or closes issue: fixes # https://github.com/home-assistant/architecture/issues/127
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/45407

Document fan entity model change to seperate fan speeds into percentages and presets modes

---

docs/core/entity/device-tracker.md

Expand device tracker docs
We recently added docs for `device_tracker`, this change adds information on which code to import to derive the entity and information about how the data can be used for `dhcp` discovery.

Expand device tracker docs

---

docs/add-ons/configuration.md

Update documentation for the new handling of tmpfs.

Update documentation for tmpfs

---

docs/api/supervisor/endpoints.md

- Link to relevant existing code or pull request:  https://github.com/home-assistant/supervisor/pull/2531

Add core state to Supervisor API

---

docs/add-ons/configuration.md

We have to escape the special chars in the REGEX.

Typo in add-on's configuration REGEX example

---

docs/documenting/standards.md
docs/documenting/yaml-style-guide.md
docusaurus.config.js
sidebars.js

This PR formalized the YAML styling guide discussed in this architecture issue:
<https://github.com/home-assistant/architecture/discussions/495>

Add YAML Style Guide

---

docs/add-ons/configuration.md

Fix add-on config mistype

---

docs/add-ons/configuration.md

Small update for kernel module options

---

docs/supervisor/debugging.md

Clarification on purpose, scope, and location.

---

docs/add-ons/presentation.md

App Armor was inop and the instructions were invalid for modern HassOS and caused applications to crash before being started.   These settings should be evaluated by someone more familiar with the requirements of an Add-On, as I am not.  I simply set things permissively and made a working example.  
Added instructions for a basic no-dependencies Ingress implementation  
Added security points based on research here https://community.home-assistant.io/t/add-on-security-calculation/269497

AppArmor, Ingress, and Security Points

---

docs/significant_change_index.md

Fix page title typo in "Significant"

---

docs/add-ons/presentation.md

Fix Apparmor profile for what we need

---

docs/api/supervisor/endpoints.md

options/config add-on endpoint

---

docs/add-ons/presentation.md

Fix apparmor signal line end

---

docs/add-ons/configuration.md

Add-on full access

---

docs/core/entity/fan.md

Document `speed_count` (used to populate `percentage_step`)
This was deferred from the original implementation of https://github.com/home-assistant/architecture/issues/127 to contain scope (https://github.com/home-assistant/frontend/pull/8216#issuecomment-766355828), I've opened https://github.com/home-assistant/core/pull/46512 to implement the step sizes.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/46512

Document speed_count for fans and the utility

---

docs/core/entity/fan.md

Fix typing on fan speed count
https://github.com/home-assistant/developers.home-assistant/pull/804#discussion_r579092664

Fix typing on fan speed count

---

docs/add-ons/configuration.md

Add-on option realtime

---

docs/dev_101_services.md

The docs on `services.yaml` need to be updated to account for the updated schema.

Update service documentation to add target and selector info

---

docs/api/supervisor/endpoints.md

Supervisor resolution healthcheck

---

docs/development_submitting.md

Replace the link to travis CI with GitHub Actions.
- This PR fixes or closes issue: fixes #824

Replace link to CI

---

docs/add-ons/configuration.md
docs/add-ons/repository.md
docs/api/supervisor/endpoints.md

Adds documentation for newly added features.
Repository/Add-on configuration files (build/config/repository) can now be .yaml and .yml in addition to .json
Add-ons can supply translation files.

Adjust documentation for add-ons

---

docs/creating_component_code_review.md

Replace dead link with way back machine version until an alternative is found.
Replace dead link with way back machine version until a replacement is found.
- This PR fixes or closes issue: fixes #822

Replace dead link

---

docs/core/entity/remote.md

Update remote entity for activities
Arch: https://github.com/home-assistant/architecture/discussions/526
Core: https://github.com/home-assistant/core/pull/47237
Frontend: https://github.com/home-assistant/frontend/pull/8506
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/47237

Update remote entity for activities

---

docs/translations.md

People keep translating curly placeholders and keep re-translating green/square bracket ones. No wonder, since not clearly spelled out int he docs :) .

Added some clarifications reg. Lokalise translations

---

docs/core/entity/fan.md

Improve fan preset mode documentation

Improve fan preset mode documentation

---

docs/config_entries_config_flow_handler.md

Add config entry unique id requirements guide

Add config entry unique id requirements guide

---

docs/supervisor/development.md

Add badges for the development repo and the remote proxy addon

Add my badge for addon repository

---

docs/entity_registry_index.md

Update entity registry unique id guide

---

docs/config_entries_config_flow_handler.md

- Merge comments from other PRs
- Cleanups

Update config entry Unique ID Requirements

---

docusaurus.config.js

Consistent spelling for API menu items (no hyphen)

---

docs/core/entity/sensor.md

Update sensor device classes with two new classes for Carbon Mono/Dioxide concentration, introduced in https://github.com/home-assistant/core/pull/47487
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/47487

Update Sensor device classes

---

docs/api/rest.md

```
$ curl -H "Content-Type: application/json" -H "Authorization: Bearer SECRET" http://localhost:8123/api; echo ''
404: Not Found
$ curl -H "Content-Type: application/json" -H "Authorization: Bearer SECRET" http://localhost:8123/api/; echo ''
{"message": "API running."}
$
```

Api endpoint is with slash at the end

---

docs/config_entries_config_flow_handler.md
docs/development_checklist.md

Following up @bdraco's PR on things that are often raised during a PR, I'm not finding any reference to the required inclusion of `config_flow` in `.coveragerc` nor the 100% requirement. Sifting through the pages it could be placed on multiple docs, but the main "Development Checklist" and the "Configuration" docs seemed the most obvious. 

Document more explicit the config_flow requirements for integrations

---

docs/api/supervisor/endpoints.md

Add documentation for new store API

Add documentation for new store API

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

The VS Code containers have more basic utilities available that are great for development.

Update dev container

---

docs/api/supervisor/endpoints.md
docs/api/supervisor/models.md

For: https://github.com/home-assistant/supervisor/pull/2703

API calls for the check management

---

docs/development_environment.md

Add note for WSL about turning the computer off, then back on again, this has bitten me several times.

Add note for Windows about turning WSL off, then back on again

---

docs/add-ons/configuration.md

The early version of Supervisor was allowed to disable the validation, but we changed it before the release that this allows disabling the options for the UI. Look like we don't clean the docs right.

Fix description around options

---

docs/development_testing.md

As confirmed by Paulus: https://discord.com/channels/330944238910963714/330990195199442944/798321546673389618
Add some clarification about what should be done as a minimum.

Note about PR and tox requirements

---

docs/core/entity/vacuum.md

The documentation is quite outdated:
- cleaning_modes are actually not supported: fan_speeds are. (cleaning_modes support would better be added soon because it is crucial for vacuums...)
- also, supported features were not being documented

Update Vacuum Entity documentation

---

docs/device_registry_index.md

Document that device info can also contain `default_manufacturer`, `default_model`, `default_name`.

Document default_* keys for device info

---

docs/api/supervisor/endpoints.md

Add content-trust to API

---

docs/architecture_index.md

Removes invert from the architecture figure, It was a bit to bold when inverted. Original colours seem ok in both cases

Remove invert from architecture figure

---

docs/data_entry_flow_index.md

Make it easier to find details for `strings.json`.

Added link to backend translation page

---

docs/api/supervisor/endpoints.md

Force security options endpoint

---

docs/creating_integration_manifest.md

Add section about custom component requirements. Based on discussion at https://github.com/home-assistant/wheels-custom-integrations/pull/343#pullrequestreview-617244610

Add section about custom component requirements

---

docs/add-ons/configuration.md

Update `journald` option to mention that journal may be available at either `/var/log/journal` or `/run/log/journal` depending on how the addon is built. Also fix `/var/logs/journal` because that's not a real thing.
- Link to relevant existing code or pull request: https://github.com/home-assistant/supervisor/pull/2742 and https://github.com/home-assistant/supervisor/pull/2751

Include volatile journal information

---

docs/add-ons/configuration.md

Addons using the `journald` option will usually have the journal mapped into the addon at `/var/log/journal`. However after https://github.com/home-assistant/supervisor/pull/2765 the journal will be available at `/run/log/journal` in some cases. Noting that in the option documentation.
- Link to relevant existing code or pull request: https://github.com/home-assistant/supervisor/pull/2765

Include alternate journal path for journald option

---

docs/frontend/custom-ui/lovelace-custom-view.md

Discussion:
I have found no actual code relating to this feature.

Rename layout option for cards to view_layout

---

docs/integration_fetching_data.md

Modify DataUpdateCoordinator example with async_config_entry_first_refresh
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/48451

Modify DataUpdateCoordinator example with async_config_entry_first_refresh

---

docs/creating_integration_manifest.md

Clarify dependency requirements.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/48241

Clarify dependencies requirements

---

docs/api/websocket.md

Correctly document error codes being a string.
Fixes https://github.com/home-assistant/core/issues/48678

Update error codes docs for websocket API

---

docs/integration_quality_scale_index.md

Add to `integration_quality_scale_index` docs about async and `ConfigEntryNotReady` to "Raise `PlatformNotReady` *or `ConfigEntryNotReady`*  if unable to connect during platform setup (if appropriate)"

Add more info to docs

---

docs/device_automation_action.md
docs/device_automation_condition.md
docs/device_automation_trigger.md

Extend docs for device automation

---

docs/creating_integration_manifest.md

Add manufacturer filter support to zeroconf
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/48810

Add manufacturer filter support to zeroconf

---

blog/2021-04-09-astral-2.2.md

- Add blog to notify custom integration authors of upgrade to astral 2.2.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/48573

Add astral 2.2 upgrade blog

---

docs/integration_fetching_data.md

Add example usage of ConfigEntryAuthFailed to the coordinator
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/48962

Add example usage of ConfigEntryAuthFailed to the coordinator

---

docs/integration_fetching_data.md

Fix wording error in DataUpdateCoordinator code comments
https://github.com/home-assistant/developers.home-assistant/pull/880#discussion_r611060708

Fix wording error in DataUpdateCoordinator code comments

---

docs/auth_api.md

s/thee/the/
Nothing else needed.

Typo: s/thee/the/

---

docs/creating_integration_manifest.md

Add a short note about lowercase/uppercase requirements for the zerconf filters. I ran into this recently when an uppercase letter made discovery not work. (https://github.com/jlvaillant/intellicenter/pull/7)
Filter implementation that I had to find to get this working:
https://github.com/home-assistant/core/blob/41ff6fc27846e4ead0cc0a3648b80317020a8c31/homeassistant/components/zeroconf/__init__.py#L272-L287

note case requirements of zeroconf config

---

docs/add-ons/testing.md

Too many times now have I seen folks use the instructions with the setup from this link, that does not work.
To limit confusion I think this link should just be removed.

Remove reference to standalone addon testing

---

docs/add-ons/presentation.md

Small fix with profile path

---

docs/core/entity.md

instead of deprecated `SwitchDevice`

use `SwitchEntity` in example

---

docs/creating_integration_manifest.md

Updates integration manifest documentation for the addition of the IoT class property.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/46935

Add IoT Class to manifest

---

docs/add-ons/configuration.md

Add labels support for build to docs

Add labels to build

---

docs/dev_101_services.md

So far the default behavior was not documented.

Notes about default values in services.yaml

---

docs/reproduce_state_index.md

Rename HomeAssistantType to HomeAssistant.
HomeAssistantType has been removed https://github.com/home-assistant/core/pull/49593.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/49593

Rename HomeAssistantType to HomeAssistant

---

docs/development_environment.md

When using devcontainers on Windows 10 it is a common mistake to access a cloned repository over the WSL2 windows shares which degrades performance a lot. An extra note is added to make sure developers place their files files at the right spot.

Windows performance devcontainer note

---

docs/frontend/custom-ui/creating-custom-panels.md
docs/frontend/custom-ui/lovelace-custom-card.md
docs/frontend/custom-ui/lovelace-custom-strategy.md
docs/frontend/custom-ui/lovelace-custom-view.md
docs/frontend/custom-ui/registering-resources.md
sidebars.js

Document the new frontend strategy feature. (and clean it up some Lovelace docs around it)

Document frontend strategy

---

docs/core/entity/light.md

Improve light docs

---

docs/core/entity/light.md

Correct table in light entity documentation

Correct table in light entity documentation

---

docs/creating_integration_manifest.md

Improve the documentation about the "domain" key in an integration's manifest.json file.

Make manifest.json documentation more clear

---

blog/2019-07-19-building-all-the-things.md
docs/add-ons/presentation.md
docs/api/native-app-integration/notifications.md
docs/api/native-app-integration/sending-data.md
docs/api/supervisor/endpoints.md
docs/api/supervisor/models.md
docs/config_entries_config_flow_handler.md
docs/core/entity/number.md
docs/core/entity/remote.md
docs/documenting/yaml-style-guide.md
docs/frontend/custom-ui/lovelace-custom-card.md
docs/significant_change_index.md
docs/supervisor/development.md

Spelling and grammar fixes

---

docs/config_entries_config_flow_handler.md

- Added the missing `hassio` step
- Changed the `discovery` step description
I think the discovery step description was wrong, or am I missing something? 
Discovery step description was added in https://github.com/home-assistant/developers.home-assistant/pull/273
Hassio step core: https://github.com/home-assistant/core/blob/e1a3ef3d6988bd2d31e7cabe5ef5cbd131238089/homeassistant/config_entries.py#L1263
Discovery step core: https://github.com/home-assistant/core/blob/e1a3ef3d6988bd2d31e7cabe5ef5cbd131238089/homeassistant/config_entries.py#L1237

Update system reserved config steps

---

docs/core/entity/light.md

Update light color_mode documentation

Update light color_mode documentation

---

docs/dev_101_services.md

Adjusts the documentation for the change made in #50015, which makes this typing wise correct now.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/50014

Adjust documentation for entity service registration

---

blog/2021-05-07-switch-pytz-to-python-dateutil.md

Blog post for https://github.com/home-assistant/core/pull/49643

Add blog about pytz

---

docs/documenting.md
docusaurus.config.js

Currently the getting started guide for setting up the home-assistant.io developer environment was not easily findable as it was missed from the top menu. Instead you had to go to another docs page and use the side menu to get back up to it. This fixes that by adding a "Getting Started" link as the first item in the "Documenting" top menu.
Also, I made the dependency installation shortcuts full-on code blocks so the "copy" button is present and removed the `$` for correctness and again to allow the content to be copy-able.

Add docs getting started to top menu

---

docs/development_environment.md

Let's be explicitly clear which repository we're telling them to clone.

Added link to Home Assistant core repository

---

docs/core/entity/sensor.md

Document sensor state_class
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/50063, https://github.com/home-assistant/architecture/discussions/557

Document sensor state_class

---

blog/2021-05-07-switch-pytz-to-python-dateutil.md

Update TZ blog post with info from latest PR.

Update the TZ blog post

---

docs/api/supervisor/endpoints.md
docs/api/supervisor/models.md

Add snapshot content

---

blog/2021-01-29-custom-integration-changes.md

- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/49916

Adjust note about future version

---

docs/api/websocket.md
docs/frontend/extending/websocket-api.md

Update the WS API docs with latest info.

Update the WS API docs

---

blog/2021-05-19-lit-2.0.md

Add a blog post about the upgrade to Lit 2.0

Create Lit 2.0 blog post

---

blog/2021-05-19-lit-2.0.md

Change the link to the RC announcement instead of the Early Preview Release

Change link to Lit blog post

---

docs/core/entity.md

Add information about using entity class attributes.
PR: <https://github.com/home-assistant/core/pull/50925>
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/50925

Add information about using entity class attribute

---

docs/architecture/core.md

Minor rammatical fixes to core.md.

Minor grammatical fixes to core.md

---

docs/core/entity/fan.md

Directions say to derive entity platforms from 'homeassistant.components.fan.FanDevice' but FanDevice doesn't exist. It is still called FanEntity
Fix typo in reference doc
- [X ] Spelling or grammatical corrections, or rewording for improved clarity

Update fan.md for typo

---

docs/core/entity/sensor.md

Document sensor last_reset

---

blog/2021-05-25-sensor_attributes.md

Add blog post about new sensor properties

Add blog post about new sensor properties

---

docs/core/entity/sensor.md

Add sensor state_class examples

Add sensor state_class examples

---

docs/network_discovery.md
sidebars.js

Document network and discovery helper APIs

Document network and discovery helper APIs

---

docs/core/entity/switch.md

Remove `is_standby` from SwitchEntity
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/51400

Remove is_standby from SwitchEntity

---

docs/network_discovery.md

Update ssdp callback matching to support MATCH_ALL
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/51382

Update ssdp callback matching to support MATCH_ALL

---

docs/core/entity/light.md

https://github.com/home-assistant/core/blob/c43bdbf7c889acb472f364943e18066401b6aa43/homeassistant/components/light/__init__.py#L645

Supported color modes is a set not a list

---

docs/core/entity/light.md

Clarify brightness calculation for RGB lights.

Clarify brightness calculation for RGB lights

---

docs/core/entity/light.md

Clarify rgb to hs/xy color conversion

Clarify rgb to hs/xy color conversion

---

docs/translations.md

The translation workflow documents collection has been removed. The articles moved to different categories. The most useful articles for Home Assistant translators are now under the translate and collaborate collection.
Changed the link to: https://docs.lokalise.com/en/collections/2909016-translate-and-collaborate.
Khaled from Lokalise:
>That page specifically is no longer available, but the content that was in it can mostly be found here: https://docs.lokalise.com/en/collections/2909016-translate-and-collaborate
And if you wish to check the exact same webpage that was up before, you can check this archived version of it: https://web.archive.org/web/20201201172616/https://docs.lokalise.com/en/collections/652216-translation-workflow
Note that some articles that were in that collection were …

Replace Lokalise documents link

---

docs/add-ons/configuration.md

Document snapshot_pre/_post configuration options
- Link to relevant existing code or pull request:  https://github.com/home-assistant/supervisor/pull/2941

Document snapshot_pre/_post configuration options

---

docs/add-ons/configuration.md

Very minor grammatical tweak. Deliberately does not consider snapshot/backup at this stage

Minor grammatical adjustment to snapshot_pre/post descriptions

---

docs/add-ons/configuration.md

[https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config](https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config) before:
[https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config](https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config) after:

Update add-ons configuration.md

---

docs/core/entity/select.md
sidebars.js

Adds basic developer documentation for the select entity.
- Link to core pull request: <https://github.com/home-assistant/core/pull/51849>
- Link to frontend pull request: <https://github.com/home-assistant/frontend/pull/9422>
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/18194
- Link to brands pull request: <https://github.com/home-assistant/brands/pull/2636>

Add select integration

---

docs/add-ons/configuration.md

Add snapshot modes

---

docs/development_environment.md

Bump python version development requirement from `3.7` to `3.8`. Usage of `typing.Final` added in [`50013`](https://github.com/home-assistant/core/pull/50013), [specifically](https://github.com/home-assistant/core/blob/076227acbe925b1ec1a0c45e1c184fd92526acac/homeassistant/const.py#L4) is only supported in python 3.8+.
See: https://docs.python.org/3.8/library/typing.html#typing.Final
- Link to relevant existing code or pull request: Updates docs to reflect changes made in [`50013`](https://github.com/home-assistant/core/pull/50013)

Bump python dev version in docs to 3.8 b.c. home-assistant/core#50013

---

docs/core/entity/air-quality.md

This PR adjusts the documentation, to make clear that AirQuality entities should not be used anymore.
See: <https://github.com/home-assistant/architecture/discussions/573>

Add AirQuality deprecation notice

---

blog/2021-05-25-sensor_attributes.md
docs/core/entity/sensor.md

Correct information on how to generate a 0-timestamp

Correct information on how to generate a 0-timestamp

---

docs/core/entity/fan.md

Fix typo in Fan entity

---

src/pages/index.js

Re adds a list of recent blog posts to the homepage. This just pulls out the info used in the sidebar of the blogs. Also fixes alignment of the calendar iframe

Add recent blog posts to homepage

---

docs/device_automation_action.md
docs/device_automation_condition.md

Follow up to https://github.com/home-assistant/core/pull/52007
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/52007

Add docs about device condition and action dynamic schema validation

---

docs/add-ons/configuration.md

Add documentation for `ingress_stream` add-on option.
https://github.com/home-assistant/supervisor/pull/2982

Add ingress_stream add-on option

---

docs/api/supervisor/examples.md

In the current version I had to ping `http://<host>/supervisor/ping`, instead of `http://<host>/ping` as implied by the docs.
```
$ curl -sSL -H 'Authorization: Bearer <TOKEN>' 'http://homeassistant.local/ping'
404: Not Found
$ curl -sSL -H 'Authorization: Bearer <TOKEN>' 'http://homeassistant.local/supervisor/ping'
{"result": "ok", "data": {}}
```

Fix supervisor ping URL

---

docs/api/supervisor/endpoints.md

Fix host feature haos

---

package.json
yarn.lock

Revert #980

---

docs/core/entity/alarm-control-panel.md

- Link to relevant existing code or pull request: ~~https://github.com/home-assistant/core/pull/38284~~ https://github.com/home-assistant/core/pull/45980

Document alarm control panel vacation mode

---

docs/config_entries_options_flow_handler.md

Updates the instructions for attaching an update listener for config entry option changes to match current preferred practices.

Update options update listener steps

---

docs/core/entity.md

Tweak documentation about _attr-style shorthand for properties

Tweak documentation about _attr-style shorthand for properties

---

docs/core/entity/siren.md
sidebars.js

Adding a new platform for sirens here: https://github.com/home-assistant/core/pull/48309. This adds developer docs for the siren base entity.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/48309

Add entity doc for siren platform

---

docs/core/entity/remote.md

Tweak language for remote turn_on, turn_off, toggle services

Tweak language for remote turn_on, turn_off, toggle services

---

docs/core/entity.md
docs/core/entity/air-quality.md
docs/core/entity/device-tracker.md
docs/core/entity/fan.md
docs/core/entity/vacuum.md

Further tweak documentation about _attr-style shorthand for properties

Further tweak documentation about _attr-style shorthand for properties

---

docs/core/entity/lock.md

Update lock for locking, unlocking, jammed
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/51455

Update lock for locking, unlocking, jammed

---

docs/core/entity/sensor.md

Add device class monetary

---

docs/core/entity/sensor.md

Add section about what's necessary for long term stats.

Clarify long-term stats

---

docs/core/entity/sensor.md

Fix small typo

---

docs/add-ons/tutorial.md

fix install/update error 'No build stage in current context' for Step 3

fix install/update error ' No build stage in current context' for Step 3

---

docs/core/entity/sensor.md

Add device class gas
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/54110/files#diff-f864c7480678e548519b8ba7f8dd17d8dfd2518f04a231b6553f277d54bd110dR66

Add device class gas

---

docs/core/entity/camera.md
sidebars.js

Add camera entity docs
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/53835

Add camera entity docs

---

docs/core/entity/sensor.md

Document sensor total and total_increasing state classes

Document sensor total and total_increasing state classes

---

docs/core/entity/sensor.md

Add dev documentation for https://github.com/home-assistant/core/pull/54075.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/54075

Add air quality device classes

---

docs/core/entity/binary-sensor.md

This will add a new device class to binary sensor platform which represent the state of an available update.
- Link to relevant existing code or pull request: home-assistant/core#53945

Add device class update

---

docs/device_registry_index.md

As a follow up to https://github.com/home-assistant/core/pull/54797#discussion_r691060744, `async_get_registry` is legacy and needs to be replaced with `async_get`.

Update device registry code sample

---

blog/2021-08-16-state_class_total.md

Fixed title of post "2021-08-16-state_class_total"

---

docs/config_entries_config_flow_handler.md
docs/creating_integration_manifest.md

Document USB discovery
https://github.com/home-assistant/core/pull/54904
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/54904

Document USB discovery

---

docs/core/entity/camera.md

Fix typo in camera docs

---

docs/core/entity/sensor.md

Doc update for https://github.com/home-assistant/core/pull/55050.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/55050.

Add volatile_organic_compounds

---

docs/core/entity/sensor.md

Document `native_unit_of_measurement` and `native_value` for sensor

Document `native_unit_of_measurement` and `native_value` for sensor

---

docs/core/entity/camera.md

- When working on home-assistant/frontend#9690 with `bramkragten`, we discovered
we need a minimum width and height to ensure the frontend images remain crisp and
the docs were not clear on what do to when aspect ratios were not the same.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/55033

Adjust camera docs to provide clarity on how to handle aspect ratios

---

docs/core/entity/sensor.md

Document `sum` statistics for sensors with state_class measurement

Document `sum` statistics for sensors with state_class measurement

---

docs/core/entity/light.md

Improve light documentation

---

docs/core/entity/sensor.md

made correction to a typo i found

Fix typo in sensor entity docs

---

docs/development_environment.md

Remove version number from Windows

---

docs/config_entries_config_flow_handler.md

Recommend ConfigEntryAuthFailed for reauthentication

---

docs/add-ons/communication.md
docs/api/rest.md

Remove refrences to `/api/discovery_info`
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/56097

Remove refrences to /api/discovery_info

---

docs/api/supervisor/endpoints.md

DataDisk feature

---

docs/api/supervisor/endpoints.md

Host agent version on API (for CLI debugging)

---

docs/core/entity/fan.md

Clarify fan preset_mode property when no preset is active

Clarify fan preset_mode property

---

docs/api/supervisor/endpoints.md
docs/api/supervisor/models.md

Datadisk list feature

---

docs/api/supervisor/endpoints.md

Docs for https://github.com/home-assistant/supervisor/pull/3136

Add docs for boot_timestamp and startup_time

---

blog/2021-09-20-state_class_total.md

Add blog post about new sensor state class total

Add blog post about new sensor state class total

---

docs/core/entity/sensor.md

Clarify state class total_increasing

Clarify state class total_increasing

---

docs/core/entity/sensor.md

Document sensor state class total

Document sensor state class total

---

docs/development_environment.md

Add tips about how to build cryptography module on macOS. This information is missing and error can rise during `script/setup` step.
- This PR fixes or closes issue: fixes #1070 

Add tips about how to build cryptography module on macOS

---

docs/device_registry_index.md

- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/58414

Add note about homeassistant scheme

---

docs/config_entries_config_flow_handler.md

Update config entity migration developer instructions to follow current best practices based on review in https://github.com/home-assistant/core/pull/59033

Update ConfigEntry migration to follow current best practices

---

docs/core/entity/sensor.md

Currently the link for ISO 4217 Currency codes goes to the list of unofficial codes used by crypto currencies, this PR changes it to go to the list of active fiat currency codes.

Fix ISO 4217 Link

---

docs/core/entity/button.md

Adds developer documentation for the button entity.
Architecture discussion: <https://github.com/home-assistant/architecture/discussions/643>
Backend PR: <https://github.com/home-assistant/core/pull/57642>
User docs PR: <https://github.com/home-assistant/home-assistant.io/pull/20105>
Brands PR: <https://github.com/home-assistant/brands/pull/2923>
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/57642

Add button entity

---

sidebars.js

Add buttton entity to navigation

---

docs/core/entity.md

Fix minor typos

---

docs/core/entity/button.md

This method was missing in the documentation.

Document async button press method

---

docs/core/entity/sensor.md

Add CBAR to units in pressure
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/58762

Update sensor.mb for CBAR

---

docs/add-ons/security.md

Added "to" in the paragraph under API Role in the first sentence.
Minor text fix

Minor Correction

---

docs/core/entity/sensor.md

Add tamper device class for binary sensor
home-assistant/architecture#600
home-assistant/core#59700

Add frequency device class for sensor

---

docs/core/entity/fan.md

Since home-assistant/core/pull/59649 implements the support for property attribute shorthand, the hint about not supporting it can be removed
- Link to relevant existing code or pull request: home-assistant/core/pull/59649

Add support for property attribute shorthand in Fan entity

---

docs/core/entity.md

Fix typos in code example

---

docs/add-ons/configuration.md

CAS function on build.json

---

docs/core/entity/camera.md

Update text wrapping since it causes the text to fall out of the table.

Update text wrapping on camera.md

---

docs/core/entity/button.md

Add initial documentation for the `restart` and `update` button entity device classes.

Add device class support for button entity

---

docs/api/supervisor/endpoints.md

Add missing options and remove obsolete options of the Supervisor's core/options endpoint.

Add missing options to Supervisor's core/options endpoint

---

docs/entity_registry_disabled_by.md

- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/60424

Make entity registry disabled_by an enum

---

docs/documenting/standards.md

Section name configuration_base does not exist, it is configuration_basic

Fix section name

---

docs/api/supervisor/endpoints.md

Documentation for https://github.com/home-assistant/supervisor/pull/3300
- Link to relevant existing code or pull request: https://github.com/home-assistant/supervisor/pull/3300

Add documentation for /supervisor/available_updates

---

docs/device_registry_index.md

https://github.com/home-assistant/core/pull/61650
https://github.com/home-assistant/architecture/discussions/685
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/61650

Update for support of hw_version in device registry

---

docs/creating_integration_manifest.md

Adjust zeroconf manifest for properties filter
See https://github.com/home-assistant/core/pull/62133
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/62133

Adjust zeroconf manifest for properties filter

---

docs/core/entity/sensor.md

Clarify energy sensor statistics calculation

---

docs/core/entity/sensor.md

Document apparent and reactive power sensor device classes
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/62010

Document apparent and reactive power sensor device classes

---

docs/api/supervisor/endpoints.md

- Link to relevant existing code or pull request:  https://github.com/home-assistant/supervisor/pull/3369

Add update backup payload

---

docs/core/entity/binary-sensor.md

- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/61962

Add CO to binary_sensor device classes

---

docs/dev_101_services.md

Just fixing a small typo.
Simply fixing a small typo, nothing huge

Fixing small typo

---

docs/core/entity/camera.md

Update developer docs to mention RTSP to WebRTC with some context about how it works and our design standards for using an external service.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/62962

Update developer docs to mention RTSP to WebRTC

---

docs/add-ons/security.md

Fixing a broken link inside the documentation.

Fix link to Auth backend documentation

---

docusaurus.config.js
package.json
yarn.lock

Replaces Algolia search with https://github.com/easyops-cn/docusaurus-search-local

Switch to local search

---

docs/core/entity/climate.md

Makes the docs agree with the code in lieu of https://github.com/home-assistant/core/pull/61456

Fix type for `current_humidity`

---

docs/core/entity/binary-sensor.md
docs/core/entity/remote.md
docs/core/entity/sensor.md
docs/core/entity/vacuum.md
docs/core/entity/water-heater.md
docs/core/entity/weather.md

Add link to source for different entities

---

docs/api/websocket.md

Document the subscribe_trigger in a websocket. As added in home-assistant/core#39109
- Link to relevant existing code or pull request: home-assistant/core#39109
- https://github.com/home-assistant/core/blob/198ade5e2be84580d4d7918789efe85b44bcafa5/homeassistant/components/websocket_api/commands.py#L437 
There is also a "variables" but i do not get what this does.
I hope my spellling is oke.

Document Subscribe to trigger websocket

---

docs/development_testing.md

Minor change to save developer time when following test code snippets

Update testing code samples for python 3.9

---

docs/api/websocket.md

Add documentation for a new command "fire_event" on the Websocket API.
Has to merged together with https://github.com/home-assistant/core/pull/63378.
- [x Document new or changing features which there is an existing pull request elsewhere
- Link to relevant existing code or pull request:  https://github.com/home-assistant/core/pull/63378

Add documentation for 'fire_event' command in websocket api

---

docs/api/supervisor/endpoints.md

https://github.com/home-assistant/supervisor/pull/3409

Add size to backup list endpoint

---

docs/development_environment.mdx

Update minimum Python version to 3.9

---

docs/api/supervisor/endpoints.md

- Link to relevant existing code or pull request: https://github.com/home-assistant/supervisor/pull/3413

Add new root endpoints

---

docs/api/native-app-integration/sending-data.md

Document https://github.com/home-assistant/core/pull/62725

Document delivering webhooks over WS

---

docs/api/rest.md

Added a Python POST example underneath the `/api/services/<domain>/<service>` section.
I have been learning Python and I noticed that there was no Python example in that section, a few months ago I was looking myself for a Python example in that section. I've tried to closely follow other examples on the same page in terms of their layout and format. The code has been tested, is working and in use.

Added Python Example

---

docs/add-ons/testing.md

I changed some minor problems about the Local add-on testing page that I noticed while reading it.

Minor tweaks of the Local add-on testing page

---

docs/internationalization/core.md

Fix strings.sensor.json key sample as domain, which is mandatory, is missing

Improve strings.sensor.json key wording 

---

docs/translations.md

Adds information about when a change in Localise goes live in Home Assistant.

Adds information about process

---

docs/core/entity.md

Currently "architecture" repo points to Issues page which probably prompts people to create issues there. Changing it to point to Discussions which is what people should use instead

Changed architecture discussions link from issues to discussions

---

docs/api/native-app-integration/notifications.md

Document how websocket push notifications work.
Also documents how to opt a registration in to only support websocket push. https://github.com/home-assistant/core/pull/63208

Document native app websocket push

---

docs/auth_api.md

Document the Python `async_sign_path` function.

Update async sign path docs

---

docs/api/supervisor/endpoints.md
docs/api/supervisor/models.md

- This PR fixes or closes issue: 
- Link to relevant existing code or pull request: https://github.com/home-assistant/supervisor/pull/3378

API: Mention compressed parameter for performing backups

---

docs/core/entity/binary-sensor.md

https://github.com/home-assistant/developers.home-assistant/pull/1161 added None as the default state, but that messed up the description. The last column was now hidden from view.
- ~This PR fixes or closes issue: fixes #~
- Link to relevant existing code or pull request: https://github.com/home-assistant/developers.home-assistant/pull/1161

Fix columns not lining up

---

docs/add-ons/tutorial.md

Reload -> Check for updates

---

docs/core/entity/sensor.md

Document `RestoreSensor`
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/66068

Document `RestoreSensor`

---

docs/api/rest.md

This is just a curl command addition, I didn't see an example of this documented anywhere, or the api endpoint listed with the others.
I'm setting up intents with rhasspy, but don't always want to speak my intents out loud when I'm just working on my intent scripts in configuration.yaml.
- This PR fixes or closes issue: fixes # N/A

Added intent handle api endpoint

---

docs/add-ons/communication.md

Use yaml instead of json for add-on config file

---

docs/creating_integration_manifest.md

If an integration wants to receive discovery flows to update the IP Address of a device when it comes
online, but a `hostname` or `oui` match would be too broad (or the existing entries do not cover newer or not yet known OUIs), and it has registered in the device registry with mac address using the `CONNECTION_NETWORK_MAC`,
it should add a DHCP entry with `registered_devices` set to `true`.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/66528

Add support for registered_devices to DHCP

---

docs/dev_101_services.md

Change example of developer tool service call from partial JSON to correct YAML format.
- Link to relevant existing code or pull request: https://github.com/home-assistant/developers.home-assistant/blob/master/docs/dev_101_services.md

YAML format for dev tool service call example

---

docs/development_testing.md

Add legacy-resolver option to manual pip command

Add legacy-resolver option to manual pip

---

docs/development_testing.md

Update section about lint errors

Update section about lint errors

---

docs/config_entries_options_flow_handler.md

Minor grammar fix. Possessive form of inanimate object should have apostrophe, or preferably be avoided.

Minor grammar fix

---

blog/2022-02-18-paper-elements.md

Remove wrong information from blog post

---

docs/integration_fetching_data.md

Add some more docs for the data update coordinator.
CC @janiversen 

Update some docs for data update coordinator

---

blog/2022-02-18-paper-elements.md

Requires https://github.com/custom-cards/boilerplate-card/pull/50

Update Blog post for scoped elements

---

docs/device_registry_index.md

- Add config entry remove device signature.

Add config entry remove device signature

---

package.json
yarn.lock

Replaces #1234
Replaces #1233 

Bump docusaurus from 2.0.0-beta.16 to 2.0.0-beta.17

---

docs/core/entity.md
docs/core/entity/sensor.md

Document impact of `extra_state_attributes` on frequently updating entities and recommended solution.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/68224 https://github.com/home-assistant/core/pull/68481 https://github.com/home-assistant/core/pull/68347 https://github.com/home-assistant/core/pull/68360 https://github.com/home-assistant/core/pull/68479

Document impact of `extra_state_attributes` on frequently updating entities

---

docs/core/entity/update.md

Adjustment to the signature of the install methods of backup entities.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/68553

Adjust backup type of Update entity

---

docs/data_entry_flow_index.md

Document show_menu step for data entry flows.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/68203 (merged)

Document show_menu data entry flow

---

docs/add-ons/communication.md

The Websocket API protocol should be ws:// not http://

Fix WebSocket API URL

---

docs/core/entity/button.md

The description for the "update" device class was partially outside the table.

Fix description of button device class "update" partially out of table

---

blog/2022-03-30-2022.4-new-dev-features.md
docs/creating_integration_manifest.md
docs/data_entry_flow_index.md

Add blog to notify custom integration devs of new features. Marked as draft as not all documentation linked yet.

Add blog about some new features

---

docs/core/entity/update.md

Move all supported features in Update entities to enum

---

docs/core/entity/update.md

- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/69054

Add documentation for the auto_update property in Update entities

---

docs/core/entity/alarm-control-panel.md

Add documentation for the entity feature flags of the alarm control panel entity component.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/69044

Add EntityFeature enum to Alarm Control Panel

---

docs/core/entity/cover.md

Documents the new `CoverEntityFeature`.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/69088

Add EntityFeature enum to Cover

---

docs/core/entity/climate.md

Documents the new `ClimateEntityFeature`.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/69077

Add EntityFeature enum to Climate

---

docs/core/entity/camera.md

Documents the new `CameraEntityFeature`.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/69072

Add EntityFeature enum to Camera

---

docs/core/entity/humidifier.md

Documents the new `HumidiferEntityFeature`.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/69092

Add EntityFeature enum to Humidifier

---

docs/core/entity/update.md

The `current_version` attribute of the `update` platform has been renamed to `installed_version`; to make it more consistent.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/69093

Rename current_version to installed_version in Update platform

---

docs/core/entity/water-heater.md

Documents the new `WaterHeaterEntityFeature`.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/69123

Add EntityFeature enum to Water Heater

---

docs/core/entity/remote.md

Documents the new `RemoteEntityFeature`.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/69120

Add EntityFeature enum to Remote

---

blog/2022-04-02-support-constants-deprecation.md

Adds dev blog post about the deprecation of all `SUPPORT_*` constants.
Upstream PRs:
- https://github.com/home-assistant/core/pull/69044
- https://github.com/home-assistant/core/pull/69072
- https://github.com/home-assistant/core/pull/69088
- https://github.com/home-assistant/core/pull/69077
- https://github.com/home-assistant/core/pull/69092
- https://github.com/home-assistant/core/pull/69091
- https://github.com/home-assistant/core/pull/69103
- https://github.com/home-assistant/core/pull/69118
- https://github.com/home-assistant/core/pull/69119
- https://github.com/home-assistant/core/pull/69120
- https://github.com/home-assistant/core/pull/69121
- https://github.com/home-assistant/core/pull/69123

Blog: Deprecating all SUPPORT_ constants

---

blog/2022-04-02-support-constants-deprecation.md
docs/core/entity/siren.md

Add documentation for the entity feature flags of the siren entity component.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/69585

Add EntityFeature enum to Siren

---

docs/core/entity/sensor.md

https://en.wikipedia.org/wiki/Power_(physics) vs https://en.wikipedia.org/wiki/Energy are easily confused in common simple English; but have more precise meanings in science and how they are used in HomeAssistant.
This explicitly points out the two are different.
Related:
- https://github.com/home-assistant/home-assistant.io/pull/22319
- https://github.com/home-assistant/home-assistant.io/pull/22325
- https://github.com/home-assistant/home-assistant.io/issues/21564

Device Classes: Slightly improve the definitions of energy vs power for device classes

---

docs/core/entity/calendar.md

Add documentation for CalendarEntity that describes the API, since it is currently ambiguous.
This proposes some specific behaviors around start/date times that may be inconsistent
which are inconsistent with some existing integrations as a path forward to making all
integrations have consistent behavior.
- Link to relevant existing code or pull request:  https://github.com/home-assistant/core/pull/68843

Add a CalendarEntity documentation

---

docs/add-ons/configuration.md

Adds missing note about translating port descriptions.

Add note about network translations

---

blog/2022-04-16-local-oauth2.md

Add blog post for Local OAuth2 breaking changes.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/69507

Add blog post for Local OAuth2 breaking changes

---

docs/core/entity/alarm-control-panel.md

Updates the developer documentation for the changes in the parent PR.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/69861

Replace Alarm Control Panel FORMAT_ constants with CodeFormat enum

---

docs/integration_listen_events.md
sidebars.js

Add docs on listening for events
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/69643#issuecomment-1100642887

Add docs on listening for events

---

blog/2022-04-20-saying-goodbye-to-event_time_changed.md

Add blog post about the removal of time_changed

Add blog post about the removal of time_changed

---

blog/2022-04-20-saying-goodbye-to-event_time_changed.md

Fix typo in EVENT_TIME_CHANGED blog post
`timed_changed` -> `time_changed`

Fix typo in EVENT_TIME_CHANGED blog post

---

docs/development_checklist.md

Require issue trackers to be enabled for external Python libraries that has communication with external devices or services
From discussion https://github.com/home-assistant/architecture/discussions/759#discussioncomment-2604627

Update development checklist - issue trackers for external packages

---

docs/core/entity/sensor.md

Clarify when sensors will be displayed as line-charts

Clarify when sensors will be displayed as line-charts

---

docusaurus.config.js

Fix broken Netlify logo in main page, fixes #1312
See https://answers.netlify.com/t/netlify-badge-link-giving-404/55643
- This PR fixes or closes issue: fixes #1312

Fix Netlify logo link

---

docs/creating_integration_manifest.md

- Document supported brands.
- https://github.com/home-assistant/architecture/discussions/734
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/67015

Add supported brands manifest item

---

docs/api/supervisor/endpoints.md

Integrity check

---

docs/core/entity/climate.md

Adds `HVACAction.Fan` to the climate entity documentation
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/70319

Add missing HVACAction.Fan to climate entity documentation

---

docs/add-ons/configuration.md

Basic SEO optimization to help find this option in future.
It took a while to find this option as searching for the technical terms "directory" or "bind mount" didn't turn anything up. "folder" is not the correct term to use going by this definition: https://en.wikipedia.org/wiki/Directory_%28computing%29#Folder_metaphor
> There is a difference between a directory, which is a file system concept, and the graphical user interface metaphor that is used to represent it (a folder).
Thanks!

Tweak description of `map` addon config option

---

blog/2022-05-12-s6-overlay-base-images.md
docs/add-ons/presentation.md

Add blogpost about new base image

---

docs/api/rest.md

Add documentation for the existing APIs, based on the limited set of fields that are now returned. We may add additional fields, and wanted to establish the baseline first, since the current set is undocumented.
- Related issue  https://github.com/home-assistant/core/issues/71581

Add documentation for the existing calendar rest APIs

---

docs/core/platform/application_credentials.md

Add more detailed examples for how to import credentials from `configuration.yaml` into the application_credentials store.

Add more detailed application_credentials import instructions

---

docs/core/platform/application_credentials.md

Add documentation for the application credentials platform for providing a custom authentication implementation.
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/71808
- Related arch discussion: https://github.com/home-assistant/architecture/discussions/692

Add documentation for custom auth implentations in application credentials

---

docs/api/rest.md

This PR updates documentation for the https://github.com/home-assistant/core/pull/71887 change
- Link to relevant existing code or pull request: https://github.com/home-assistant/core/pull/71887

Update calendar event rest AP with description and location

---

docs/core/entity/update.md

https://github.com/home-assistant/developers.home-assistant/pull/1265#pullrequestreview-928767731

Adjust auto_update for update entity

---

docs/api/native-app-integration/sensors.md

Add docs for https://github.com/home-assistant/core/pull/71561 and https://github.com/home-assistant/core/pull/71562
preview: https://deploy-preview-1325--developers-home-assistant.netlify.app/docs/api/native-app-integration/sensors#keeping-sensors-in-sync-with-home-assistant

Update mobile app

---

docs/creating_integration_manifest.md

Document `loggers` manifest field

Document `loggers` manifest field

---

docs/add-ons/configuration.md

After attempting to setup codenotary signatures for my addons I followed the documentation, only to realise after looking at other addons, I required the codenotary option along with an email in the config.yaml which was not documented

Add codenotary to add-on config.yaml documentation 

---

docs/config_entries_options_flow_handler.md

Update options flow examples to including typing information to conform to latest standards.

Update options flow examples to including typing

---

docs/internationalization/core.md

I changed home-assistant (old repo) to core (new repo)

Change home-assistant to core

---

docs/development_environment.mdx

I updated a few of the outdated links.

Update some URLs

---

docs/api/rest.md

I renamed 'api component' to 'api integrations' and changed the URL from components to integrations.

Rename component to integration

---

docs/documenting/create-page.md

I updated the URL of template sensor from .../components/... to .../integrations/...

Components to integrations

---

docs/supervisor/development.md

For https://github.com/home-assistant/core/pull/72601

Use supervisor envs instead of hassio

---

docs/operating-system/debugging.md

"Import from USB" is not available from the UI anymore, only from the CLI.
This PR updates the docs accordingly.
- This PR fixes or closes issue: fixes #1321

Updates outdated procedure to SSH host access
